### ISSUE TITLE
"Reset iCloud3 Interface" Not Functioning

### ISSUE THREAD

**Issue by auberonkai** [gcobb321/icloud3_v3#1]
I'm having an authentication issue with icloud3 v2.4.7 such that it tells me in the logs:

"iCloud3 Error > iCloud Account Authentication needed > Will use iOS App Tracking Method until the iCloud account is authentication is complete. See the HA Notification area to continue. iCloud3 will then be restarted."

The HA notification area remains empty even after waiting 10 minutes after clicking 'Reset iCloud3 Interface' on the iCloud3 event log card. 

This integration worked until about a week or so ago for me. I'm guessing that was when this particular authentication session ended, since they expire every 30 days or so. Is there a "correct" process to force this that doesn't include the "Reset iCloud3 Interface" button?

**Comment by gcobb321** [comment]
The code is not actually generated until an authentication is done, Try `Event Log ? Actions > Restart iCloud3` or restarting HA.

**Comment by auberonkai** [comment]
Thanks for the response.

I have restarted HA over 100 times over the last 3 days, and once I got the
Event Log card set up, tried "Restart iCloud3" and "Reset iCloud3
Interface" between 50 and 80 times.

In other news, the iCloud3 config notification I was waiting for popped up
with no rhyme or reason while I slept this morning. I don't know what
changed to allow authentication to complete, but my configurations are
identical to what they were before this issue came up. The integration is
working as expected now.

Thank you for creating a highly useful integration, and for continuing to
support it!

**Comment by gcobb321** [comment]
The timing of the authentication window and code is all determined by Apple. I ran into an issue working on v3 where a notification would be displayed several times and then not for several hours. Glad it's working now.

**Comment by gcobb321** [comment]
**iCloud3 v3.0.0 beta 1 is available**
OK guys. Here it is. Have fun and be kind. 

iCloud3 v3.0.0 beta 1 has been uploaded to the iCloud3_v3 repository. It can be found on the [v3 Releases page here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta.1).
