### ISSUE TITLE
Big fix: device_tracker

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#10]
Ho All,

the device_tracker shows: `Home` or `Away` instead of `home` or `away`

It's a cosmetic fix but all states are always low characters... :)

**Comment by jcbshw** [comment]
Not just cosmetic as HA is case sensitive. It's a pain to rewrite automations/templates for my device trackers.

**Comment by gcobb321** [comment]
Fixed in beta 3 which I hope to release Friday (12/23) or Saturday (12/24)

**Comment by poudenes** [comment]
Hey,

This big is back in latest releaseBeta 13 (2/24/2023)

**Comment by gcobb321** [comment]
Get beta 13a uploaded a few hours ago

**Comment by poudenes** [comment]
> Get beta 13a uploaded a few hours ago

already installed and solved!

**Comment by JtwoA** [comment]
Is 13a what I pulled down last night around 21:00 ET?

--
John Alan

01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110110 01100001 01101100 01110101 01100001 01100010 01101100 01100101 00100000 01100110 01100101 01100001 01110100 01110101 01110010 01100101 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01101100 01101100 01101001 01100111 01100101 01101110 01110100 00100000 01101100 01101001 01100110 01100101 00101110

**Comment by gcobb321** [comment]
The version you are running is (1) in the device_tracker attributes at the bottom (icloud3 version - v3.0.0b13a) or (2) at the beginning and end of the setup process in the event log.

I uploaded around 9am EST this morning (Saturday)

**Comment by JtwoA** [comment]
Got it - thanks!

--
John Alan

01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110110 01100001 01101100 01110101 01100001 01100010 01101100 01100101 00100000 01100110 01100101 01100001 01110100 01110101 01110010 01100101 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01101100 01101100 01101001 01100111 01100101 01101110 01110100 00100000 01101100 01101001 01100110 01100101 00101110
