### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer - When trying to add last_zone sensors

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#101]
I'm receiving the error above when I tried to add last_zone sensors...

This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/helpers/messaging.py:371
Integration: iCloud3 v3 (documentation, issues)
First occurred: 14:08:08 (2 occurrences)
Last logged: 14:08:09

►INTERNAL ERROR (UpdtSensorUpdate-'str' object cannot be interpreted as an integer)
►INTERNAL ERROR (UpdtSensorUpdate-'NoneType' object is not iterable)

**Comment by gcobb321** [comment]
Fixed in b16. Also fixed the icons for the zone & last zone sensors and changed the direction-of-travel sensor icons when going to/away from home
