### ISSUE TITLE
What is the difference between the 2 iphone options when adding a new tracked device?

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#102]
What is the difference between the 2 iphone options when adding a new device? Or they are just duplicate?

![image](https://user-images.githubusercontent.com/11551691/230156736-ab37d7da-14b4-493a-b4b0-1bcc50cdc885.png)

**Comment by gcobb321** [comment]
It's a duplicate and i've just deleted it. The secone one was to catch 'phone' but that would cause more problems if it was selected. Good spot.

btw, the lost_device_alert is almost done. One final test to actually send the message to my phone when I have my wife's phone handy to take it out of a lost mode.

**Comment by marceloaf** [comment]
Great! Thanks!
