### ISSUE TITLE
Suggestion: Put the messages in green when they are successfully saved/executed

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#103]
Just as a suggestion, put the messages in green, instead of red, when action was successfully saved/executed.

![image](https://user-images.githubusercontent.com/11551691/230157207-9d79043a-e0d8-4ed0-a13a-2ca9a342982b.png)

**Comment by gcobb321** [comment]
Good idea but that is all controlled by the HA front end. The HA docs describe this as a error message area but it's always nice to have some confirmation that the update was done.
