### ISSUE TITLE
Apple ID verification code problem

### ISSUE THREAD

**Issue by u20p17** [gcobb321/icloud3_v3#104]
Hello,
i got a message to reconfigure the icloud3 v3. I got the code on my iphone but accidentally pressed ok there without remembering it. Now i only get the following message when I try input the 2FA code:

![image](https://user-images.githubusercontent.com/63282286/230564068-26fd5fdc-c630-4d86-bafb-19117dfb5afe.png)

How can I get another 2FA code? It does not pop up again on my apple devices...

BR

**Comment by JigSawFr** [comment]
Restart of HA should do the trick

**Comment by gcobb321** [comment]
Or Event Log > Actions > Reset iCloud Interface

**Comment by u20p17** [comment]
> Or Event Log > Actions > Reset iCloud Interface

Restarting HA didn't help. But the answer of @gcobb321 helped - thank you very much!
