### ISSUE TITLE
B15: Recorder Size Warning for Attributes

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#105]
Still seeing recorder size warning for attributes in B15. #89 

```
2023-04-10 17:03:40.116 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.icloud3_event_log exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```
<img width="1095" alt="Screenshot 2023-04-10 at 6 55 42 PM" src="https://user-images.githubusercontent.com/6526076/231017012-8232dae3-71b3-4df9-837d-b76bb581127e.png">

**Comment by gcobb321** [comment]
I looked a at this earlier and couldn’t find a problem. The length of the state value for Sensor at the time was over 21k. iCloud3 hacks into the recorder and and sensors to be excluded. Somehow yours is not being added. Try adding a recorder exclude statement in HA configuration.ymal to exclude the event log sensor using the real HA method.

**Comment by gcobb321** [comment]
b16 released
