### ISSUE TITLE
Clickthrough for sensor.xxx_dir_of_travel refers to wrong service

### ISSUE THREAD

**Issue by DvdEnde** [gcobb321/icloud3_v3#106]
When including 'Direction' (sensor.xxx_dir_of_travel) in the dashboard the clickthrough refers to command-event-log-gary (see image)

![image](https://user-images.githubusercontent.com/114862353/231809094-c887cf6d-7586-4f1d-8b79-ff83dbf0c9c7.png)

**Comment by gcobb321** [comment]
I’m not sure what you mean by ‘clickthrough’. When I tap on the direction sensor on a Lovelace screen, it displays the history. What prices are you doing to get that error?

**Comment by DvdEnde** [comment]
When I tap tap on the direction sensor on the Lovelace screeen, it displays the message above.

**Comment by gcobb321** [comment]
fixed in b16

**Comment by DvdEnde** [comment]
Thank you Gary!
