### ISSUE TITLE
Error message on initialisation

### ISSUE THREAD

**Issue by RealGandy** [gcobb321/icloud3_v3#107]
Hi

Using b15, my first foray into iCloud3.

I get the following error message on an iCloud3 or HA restart, but I do not have this entry in my configuration.yaml file.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/305484/232913853-5a1eec41-5229-4a76-a859-f080faff85f5.png">

Is this something I should be concerned about?

**Comment by gcobb321** [comment]
Could it be in another file that contains your device _tracker platform statements? Look for an _include_ statement.

**Comment by RealGandy** [comment]
Nope, no includes. 

🤷‍♂️

**Comment by gcobb321** [comment]
Did you have v2 installed before installing v3?   
Did you have the HA iCloud integration installed?
HA is starting the custom_component device_tracker icloud3 file like it does from a platform: icloud3 statement. The message is only a warning and doesn’t affect anything.

**Comment by FireROR** [comment]
I can confirm this issue but it only happened when starting the v3. Everything is running well. I guess this is just false alarm.

**Comment by RealGandy** [comment]
I used it on a previous installation and copied some config to this but removed references to icloud3 from the configuration.yaml. Been running for about six months and recently added icloud3 v3 b15 and now see this message on startup.

**Comment by gcobb321** [comment]
That is an informative message only. It is only displayed when HA has started the icloud3 device_tracker the old way with the platform statement. I have made a change to beta 16 tthat will only display the message during the initial install and not again after it has been set up with the Configuration Wizard.
