### ISSUE TITLE
B15: How to Re-Trigger Apple Authorization?

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#108]
Yesterday, I got the Apple Authorization popup on my iPhone to re-auth iCloud3 v3. However, I was not in a place where I could enter the code into HA so I just hit Ok and Ok. Now, I cannot sort out how to get the Auth to re-trigger on my iPhone.

I've followed the instructions from the log:
<img width="484" alt="Screenshot 2023-04-22 at 11 09 48 AM" src="https://user-images.githubusercontent.com/6526076/233792843-509a280d-8d5a-4176-accb-3e1d4ed286d3.png">

But that gives me the place to enter the key but doesn't seem to trigger it on the iPhone. I've tried restart iCloud3 v3 and HA but it doesn't seem to trigger it either.

**Comment by gcobb321** [comment]
Event Log > Actions > Request Apple-ID Verification Code

**Comment by Snuffy2** [comment]
I don't have that option:
<img width="736" alt="Screenshot 2023-04-22 at 11 24 00 AM" src="https://user-images.githubusercontent.com/6526076/233793127-324c7880-ebd5-4717-ae85-6fa4816ab406.png">

**Comment by gcobb321** [comment]
Event Log Actions > Reset iCloud Interface. I changed the item description in beta 16 which has not been release yet.

**Comment by Snuffy2** [comment]
That worked, thanks.
