### ISSUE TITLE
Error log in HA (iCloud3_Beta3)

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#11]
I see 2 times this error. Then no errors again (I have 2 iPhones in the integration)

```
2022-12-21 17:58:37.022 ERROR (SyncWorker_2) [icloud3] 'notify'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/iosapp_interface.py", line 128, in get_mobile_app_notifications
    notify_services = dict(services.__dict__)['_services']['notify']
KeyError: 'notify'
```

**Comment by gcobb321** [comment]
This has to do with the iOS App notify service not being set up before iCloud3 starts. There is a delayed retry and it should be set up later and iCloud3 sets up the interface then. Beta 3 removes this error message.

I’ll close this issue when beta 3 is available.

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary
