### ISSUE TITLE
☢☢ The FmF (Find-my-Friends) Tracking Method is not working due to a change Apple made

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#111]
Apple has made a change to the data returned from iCloud Location Services. The the url links to that would return the FmF data are no longer returning any FmF data. It looks a lot like the FamShr data but I can not be sure if it is the same data or only part of it.

The location for the friends is still being reported correctly in the FindMy app but not being sent with iCloud3 requests it.

I will be investigating the issue and see what can be done. In the meantime, the FamShr tracking method is working fine.

**Comment by woopstar** [comment]
+1 on this.

**Comment by SaturnusDJ** [comment]
Hey Gary @gcobb321,

Have you found anything yet?

**Comment by gcobb321** [comment]
Not a thing. I found a web site with a lot of Apple links but nothing useful.

**Comment by KairuByte** [comment]
Just to check, does this change on apples side likely mean that the FMF method is dead for the foreseeable future? I ask because that's pretty much how all the users in our instance are tracked.

**Comment by gcobb321** [comment]
Yes for now. I’ve done since digging but have not found anything solution yet
