### ISSUE TITLE
Unable to re-authenticate icloud account

### ISSUE THREAD

**Issue by bpennypacker** [gcobb321/icloud3_v3#113]
I'm running beta 15 of icloud3 on HAOS 10.1 running Home Assistant 2023.4.6. I've been using it for a couple months now and have upgraded from a couple earlier betas as they've been released. I just recently received a notification that I needed to re-authenticate my account  but inadvertently dismissed the message with the 6-digit code before I could enter it into HA. It's now stuck such that when I click on the Reconfigure button in the iCloud3 integration I only see the the dialog that prompts for me to enter the 6 digit code. I am unable to get to the configuration pages where I can see or edit my configuration settings, including my iCloud username & password.

Since I don't have an authentication code I entered 000000 to try to get past the verification dialog. It, unsurprisingly, returned an error message "The Apple ID Verification Code is invalid. Requested a new code", however I never received any new codes.

I have taken my other Apple devices like my iPhone, gone into the password & security section for my Apple ID and requested a new code by clicking on the "Get Verification Code" button. This immediately returns a new code, but iCloud3 doesn't recognize any of them at this point.

I'm now effectively stuck, unable to log out or back into my iCloud account within iCloud3. I'm unable to validate my Apple ID in iCloud3. I've tried removing iCloud3, restarting HA, and re-installing, but it's still stuck on the verification dialog and still doesn't recognize any of my codes I generate from my iPhone.

**Comment by gcobb321** [comment]
Event Log > Actions > Reset iCloud Interface will ask for a new code

**Comment by bpennypacker** [comment]
Thanks! I forgot I could get to it that way.
