### ISSUE TITLE
core 2023.5.0b...   more and more faults upcoming with 2023.5

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#114]
with HA Core 2303.5. betas I have more and more faults in the logs:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:179 
First occurred: 18:34:53 (1 occurrences) 
Last logged: 18:34:53

Error setting up entry iCloud3 for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 45, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```
```
Logger: icloud3
Source: helpers/entity.py:578 
First occurred: 18:34:53 (24 occurrences) 
Last logged: 18:36:02

Attribute hass is None for <DeviceSensor: icloud3_event_log>
Attribute hass is None for <DeviceSensor: icloud3_wazehist_track>
Traceback (most recent call last):
  File "/config/custom_components/icloud3/sensor.py", line 1236, in async_update_sensor
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 578, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <DeviceSensor: icloud3_event_log>
```

**Comment by gcobb321** [comment]
The 'Error setting up entry iCloud3 for device_tracker' above comes from HA when it is being added on the Integrations screen and it has already been set up. I would suspect everything else comes from that error. 

Go to the Devices & Settings > Integrations and delete the iCloud3 integration. Then restart HA. Go back to the Devices & Settings > Integrations and see if iCloud3 is still there. If so, delete it again, restart and continue until it is no longer displayed. Then Add it.

Your configuration and iCloud session cookies are not deleted so when you add it back, all your devices and parameters are used and it should start without any problems.

**Comment by criticallimit** [comment]
does it clear the: `Attribute hass is None for <DeviceSensor:` also?

I have since 2023.5.0b... this fault more and more in the logs: `Attribute hass is None for <DeviceSensor:` 


The `Error setting up entry iCloud3 for device_tracker` is coming from time to time, but not very often. After reloading the integration everything is fine.

**Comment by gcobb321** [comment]
The only other thing I can think of is a timing issue that HA is starting iCloud3 before the Event Log Sensor has started/finished setting up. I'd like to see your home-assistant.log file to look at the sequence of how HA is loading. 

The Event Log is getting set up before HA has created the sensors but nothing should be using posting anything to it before the sensors are set up. That is why I wanted to look at the log file.

Does it only happen when HA starts or also at various times after it has started tracking devices?
Are you running a plain HA setup (RPi) or are you rinning in a virtual environment?

email the log file to geekstergary@gmail.com.

After I look at it, I'll email you 2-files, one that sets up the Event Log after the sensors have been set up and another with some error trapping when writing to the sensors that might make the error go away.

**Comment by criticallimit** [comment]
Problem solved!

Deleted   iCloud3 Integration in the UI
Deleted   /config/costum_components/icloud3 Folder
Deleted   /config/.storage/icloud3 Folder
Deleted   /config/.storage/icloud Folder

Restartet RPi and HA, checking for Faults. No Faults in Log

Reinstalled iCloud3 from scratch, configured it and restartet HA.

All Faults gone.


Thanx

**Comment by gcobb321** [comment]
Good. I wonder what was causing it. Maybe some parameter converted to something causing the error.
