### ISSUE TITLE
Debug Logging started after Restart of HA

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#115]
You can Start/Stop debug logging in the settings, which is working.
But every time i restart HA it is set to started again.
This results in a warning message in the core log that max. log is reached and attribute logging is cancelled.

**Comment by gcobb321** [comment]
Are you start/stopping the Debug logging in the Configuration Wizard or on the Event Log > Actions. In the Wizard, set it to info in the Other Parameters or Format Parameters screen depending on the version.

**Comment by criticallimit** [comment]
I start/stop it in the Configuration Wizzard.

**Comment by gcobb321** [comment]
I just updating my note (above) after remembering what was going on.

**Comment by gcobb321** [comment]
changed in b16

**Comment by criticallimit** [comment]
installed already and is working
