### ISSUE TITLE
Services icloud3_update not accessible

### ISSUE THREAD

**Issue by GerdRuetten** [gcobb321/icloud3_v3#117]
Dear all,

under v2, i use the service "icloud3_update" with command "location" or "resume" to fresh-up the location for all devices or resume the polling for all devices.

Under v3 is this service not accessible.

Is their a new service for do this?

In the documentation i can't find anything 

TIA

Gerd

**Comment by gcobb321** [comment]
This was added in beta 12 but I have not updated the docs. My next project.

The 'icloud3_update' svc call was changed to 'icloud3_action' for clarity and to be the same as the Event Log > Actions menu.
2.  New 'locate' Service call - Added the 'locate' Action to the icloud3.action Service Call. This action
    lets you locate a device (or all devices) immediately or in after a specific time has elapsed.
    This replaces the set_interval service call in v2.
    The following examples explains how it can be used:
        Calling method:
            service: icloud3.action
            data: {action: locate xx min, device_name: xxx}

        Examples:
            - Locate gary_iphone in 4 minutes: {action: locate 4 min, device_name: gary_iphone}
            - Locate gary_iphone immediately:  {action: locate, device_name: gary_iphone}
            - Locate all phones in 4 minutes:  {action: locate 4 min}
            - Locate all phones immediately:   {action: locate}

**Comment by GerdRuetten** [comment]
Dear @gcobb321 Gary,

thank you!

And the equivalent to the v2 command:resume is {action: resume} ??

Best regards

Gerd

**Comment by gcobb321** [comment]
Yes.

service: icloud3.action
data:
  action: resume
  device_name: gary_iphone
