### ISSUE TITLE
iCloud3 v3, Translations File

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#119]
The Configuration Wizard uses a typical HA translations file with a *"textkey": "display-text"* format that is used to display all of the text messages, field descriptions, etc for the various screens.

Several of you have offered to provide a translations file for your native language. 

I have attached the en.json file and would be glad to include the translated text file when iCloud3 v3 is released. If you would like to provide a translated file, edit the en.json.txt file attached to this note (display_text only, leave the text key alone). Include your file with a reply.

Thanks.

Gary

[en.json.txt](https://github.com/gcobb321/icloud3_v3/files/11415800/en.json.txt)

**Comment by thiago-s-medeiros** [comment]
Brazilian Portuguese, pt-BR

[pt-BR.json.txt](https://github.com/gcobb321/icloud3_v3/files/11454543/pt-BR.json.txt)
