### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#12]
I can't even get beta 2 to start, I get the following error:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:166
First occurred: 2:32:13 PM (1 occurrences)
Last logged: 2:32:13 PM

Error setting up entry iCloud3 for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 44, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

```

and all my devices show "• • Starting iCloud3 • •"

**Comment by gcobb321** [comment]
I haven’tseen that one before. I’m still working on beta 3, which fixes some errors, but haven’t made a release yet. The current version of it is on the iCloud3_v3 repository. Download and install and see if it works better.

————————
Gary Cobb

**Comment by gcobb321** [comment]
The only thing I could think of that there was a duplicate device name that was trying to be set up a second time, which doesn’t make sense. Others have had problems with the migration program where old or unused device names in the config files were causing problems creating the HA sensors and HA device_tracker entities before the migration results were reviewed and corrected. I have changed the migration to make the first valid device name tracked, all of the others are set to an Inactive status that must be changed in the Configurator during the review.

I will probably upload Beta 3 Saturday (12/24) in the afternoon.

Delete the _/config/.storage/icloud3_ directory to redo the migration, download and install the beta 3 and try again. I’ll send a notification and close this issue when beta 3 is available.

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary

**Comment by gcobb321** [comment]
Beta 4 is available for download. See the Releases page
