### ISSUE TITLE
Debug Logging started after Restart of HA

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#120]
Beta 16 installed and debug looging is not startet in the config assistant. But still in the logs:

```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:585 
Integration: Recorder (documentation, issues) 
First occurred: 07:02:43 (2 occurrences) 
Last logged: 07:02:50

State attributes for sensor.icloud3_event_log exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

**Comment by criticallimit** [comment]
ok. it´s not the debugging, its the monitored decives in the sensor.icloud3_event_log attribute: logs

![Bildschirmfoto](https://user-images.githubusercontent.com/5613811/236749943-fc0869e6-a0b5-468b-aa58-4431d2b254c9.jpg)

It´s growing fast. How to set it only to sensors I want to log?

**Comment by gcobb321** [comment]
There HA recorder statement in the configuration.yaml file can be used to exclude sensors that should not be added to the data base. Info is [here](https://www.home-assistant.io/integrations/recorder/). Google _home assistant recorder _ to get examples

When iCloud3 starts, it adds sensors to the recorder using some undocumented routines to add sensors it creates to the recorder exclude list just like HA does when the config file is processed. It appears that that is not succeeding in your case. See below for a list of the sensors

Confiuration.yaml statemens
```
recorder:  
  purge_keep_days: 5  
  exclude:    
    entities:  
      - sensor.icloud3_event_log
      - ensor.icloud3_wazehist_track
```

        Sesors excluded from the recorder:
                - icloud3_event_log
                - icloud3_wazehist_track
                - *_info
                - *_last_located
                - *_last_update
                - *_next_update
                - *_last_zone
                - *_last-zone_display_as
                - *_last_zone_name
                - *_last_zone_fname
                - *_last_zone_datetime
                - *_zone_daetime

**Comment by criticallimit** [comment]
Thank you very much for your help.
Added recorder to configuartion.yaml to exclude the sensors.
will let it run for few hours now and report back

**Comment by gcobb321** [comment]
Your original understanding is correct.  Excluded entities are still available in HA. They are only excluded from the history.  heir states value can still be seen under Developer Tools > States.

**Comment by criticallimit** [comment]
Think this can be closed now. My Fault
