### ISSUE TITLE
Phone stuck in Stationary Zone 32 metres from Home zone

### ISSUE THREAD

**Issue by Nuuki9** [gcobb321/icloud3_v3#121]
Running Beta 16a. For some reason my wife's iPhone is showing as in a Stationary Zone, 0.02 miles from the Home Zone. Been like that for close to an hour, and has persisted when I sent a location update request from the Event Log. In the Log it shows the app reporting her location as Home.

**Comment by Snuffy2** [comment]
I'm seeing the same.

Red box is the HA iPhone App
Blue box is iCloud3_v3
![Screenshot 2023-05-08 at 8 39 38 AM](https://user-images.githubusercontent.com/6526076/236952368-b56f9502-74bd-4d07-9147-bbe03448a568.png)

I'll try to get some logs too.

**Comment by gcobb321** [comment]
I’ll add another check to make sure a stationary zone is not created in another zone and to remove it if it is. There are already some tests to not create one based on distances between zones but it obviously isn’t working correctly.  I’ll also kill all Stationary zones on a relocate request.

**Comment by FredWst** [comment]
Hi,
I've same issue at home with good address but seen Away. (Absent)

![Capture d’écran 2023-05-09 à 12 00 13](https://github.com/gcobb321/icloud3_v3/assets/41281764/f2174458-730c-4702-9d80-f5b8f14b259e)

**Comment by Snuffy2** [comment]
Adding another screenshot and the icloud logs from this morning. Notably, it seems I am not seeing the tracker stuck in a stationary zone, but instead it is just not going all the way home. I can split this into a new incident if desired.

![SNAG-1766](https://github.com/gcobb321/icloud3_v3/assets/6526076/02b027f3-8a56-4a17-9729-6e64cc43b69f)

[icloud3-debug-deid.log](https://github.com/gcobb321/icloud3_v3/files/11432623/icloud3-debug-deid.log)

**Comment by gcobb321** [comment]
Hey Guys,
I think I fixed these issues.  I wanted to give you a chance to try it out to see if the issues are actually fixed and have not updated the general release yet

Unzip this file into the icloud3 directory.

Beta 16b - 5/9/2023
~~~~~~~~~~~~~~~~~~~~
1.  Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a
    test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked,
    the update was not being processed since the data had not changed when it should have been processed on the initial
    trigger.
2.  Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to
    another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.

[icloud3_v3-beta-16b.zip](https://github.com/gcobb321/icloud3_v3/files/11436158/icloud3_v3-beta-16b.zip)

**Comment by Nuuki9** [comment]
I've copied it over - will need to run it for a while to see if it seems to be working but I'll feedback once I have something to report...

**Comment by FredWst** [comment]
Update to 16b icloud3 running but error in log


Logger: icloud3
Source: custom_components/icloud3/support/pyicloud_ic3.py:1298 
Integration: iCloud3 ([documentation](https://gcobb321.github.io/icloud3_v3/#/), [issues](https://github.com/gcobb321/icloud3_v3/issues)) 
First occurred: 12:51:39 (2 occurrences) 
Last logged: 12:51:41

list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1063, in create_FamilySharing_object
    self.FamilySharing = PyiCloud_FamilySharing(self,
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1186, in __init__
    self.refresh_client(device_id)
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1268, in refresh_client
    self.update_device_location_data(requested_by_devicename, self.response.get("content", {}))
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1298, in update_device_location_data
    offline_msg = ', OFFLINE' if device_data[ICLOUD_DEVICE_STATUS] == '201' else ''
TypeError: list indices must be integers or slices, not str

![Capture d’écran 2023-05-10 à 12 53 54](https://github.com/gcobb321/icloud3_v3/assets/41281764/776ca28b-3373-4aad-afbf-8b02f01eacfa)

**Comment by gcobb321** [comment]
Beta 16b - 5/10/2023 (11:07:33am US EDT)
...................

Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked, the update was not being processed since the data had not changed when it should have been processed on the initial trigger.

Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.

Configuration Wizard - Fixed a problem displaying the 'Next Page' on the Update Devices and Display-Text As screens.

Here is an updated b16b

[icloud3_v3-beta-16b.zip](https://github.com/gcobb321/icloud3_v3/files/11443575/icloud3_v3-beta-16b.zip)

**Comment by gcobb321** [comment]
Fixed in b16b
