### ISSUE TITLE
iCloud3 v3, Beta 16b (5/10/2023) has been uploaded

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#125]
@avd706 @andrzejf1994 @B-Hartley @broyuken @bgnzo818 @beyondwatts @bakerkj @andrzejf1994
@confusedsecuritydudes @chupacabra71 @chr04213 @criticallimit
@daneboom @denac @derekoharrow @diothar @DerDon1302
@Exit2Studios @freshairr @gekberlin @garyak @freekode @FredWst
@hvddrift @hellotomtom @ihf1 @JtwoA @HA_n00b @J-Fartz @joselito1
@kalkocz @kamkilt @kingy444 @lukkigi
@marceloaf @MarkGardiner @marting @mobiledude @myMartek @morrisonpeter
@Nuuki9
@pauly7300 @poudenes @polskikrol
@rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3
@townsmcp @tm24fan8 @t077584 @u20p17

And sorry if I missed you, 

### Important Links
- **Download and Install** - Go to the iCloud3 [Releases page here](https://github.com/gcobb321/icloud3_v3/releases). Scroll down past the notes, then select *Assets*, then select *icloud3.zip*. Download the zip file and unzip it into the */config/custom_components/icloud3* directory. Then restart HA.
- **Installing using HACS** - iCloud3 is not available on HACS unless you have set it up as a custom repository. 
See [here](https://gcobb321.github.io/icloud3_v3/#/chapters/2.0-installing-and-configuring?id=step-1-install-icloud3) for instructions on how to do that and then install it. If you just go to HACS and do the installation, you will be installing v2.4.7, not v3.
- **Migrating from v2.4.7** - See [here](https://gcobb321.github.io/icloud3_v3/#/chapters/0.1-migrating-v2.4-to-v3.0?id=migrating-icloud3-from-v24x-to-v30) for instructions on migrating from from an older version. 
- **iCloud3 v3 Documentation** - It is still in process, does not include the latest updates to iCloud3 and can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)
- **Change Logs** - See the notes below:

### Update Notes for Beta 16b
1.  Enter Zone - Fixed a problem where an iOS App Enter Zone trigger was being not being processed. There was a test for entering a track_from_zone (Home) that was was being delayed. The next time the trigger was checked, the update was not being processed since the data had not changed when it should have been processed on the initial trigger.
2.  Stationary Zone - Added another check to make sure the Stationary Zone will not be created when it is close to another zone. The gps accuracy + 25m is now also used in the minimum distance calculation.
3.  Stationary Zone Friendly Name - The stationary Zone sequence number will only be inserted into the zones name if the '#' is specified. Otherwise, the value Friendly Name will be displayed and assigned to all zones for all devices.
4.  Configuration Wizard - Fixed an issue displaying page 2 of the Update Devices or Display Text As screens.

### Update Notes for Beta 16
This beta is probably the last one, I hope. It includes a lot of small items dealing with Event Log messages, changes to the icons based on the state of the sensor entity,  changes to sensor updates, enter zone delay handling, a new  icloud3_update service call to activate the lost device alert, enhancements to Watch zone exits and updates, better handling of near by devices and some bug fixes.

**These are important ones**:

The Stationary Zone has been redesigned so it is no longer associated with a device. It is created when a device has not moved like it always has been. Now, any other nearby device will also use that zone instead of creating another one for the same location. It's name can still assigned on the Special Zones >Stationary Zone screen but it now takes the form of a zone name followed by a number (default is StatZon#). The iOS App device_tracker and person entities now will show the same zone name as iCloud3 instead of the device being in it's stationary zone and the other entities displaying another zone.

The Configuration Wizard menus have changed. The Enter/Request Apple ID Verification and Change Device Order screens are now on the first menu page so it now displays all iCloud and device related screens. All other screens are displayed on he second menu page.

HACS - I had requested that iCloud3_v3 be added to HACS so those using v2 would still have their HACS entry and v3 users would have another. This was turned down by those responsible for HACS. They said that it is in beta and has not be officially released. When it is officially released, it should be merged into the main iCloud3 listing so it will be available to all users. HACS will support it with 2 methods, (1) Adding the iCloud3_v3 repository to HACS as a special repository and (2) by treating it as a pre-release that makes it available to anyone that has the HACS Show pre-release updates checked.

I added instructions to the iCloud3 docs on setting up v3 betas as a custom repository. After beta 16 has been downloaded by a significant number of users (beta 15 has been downloaded over 300 times), and after I have completed the documentation, I will create a release candidate and update the current iCloud3 HACS version.

Gary

### Beta 16 - Complete List of Updates
1.  Event Log - Fixed a problem where the 'event-log-card.js file would not be installed if the 'www' directory did not exist. Now, the 'www' directory is checked and will be created if it didn't exist.
2.  inZone and Old Location - If a device not using the iOS App or a Watch, was in a zone and the location data was old but newer than the last update, the device was not being updated with newer location data and would be stuck retrying the update on a larger and larger interval, resulting in the device never being updated. This has been fixed so the device will always be updated with newer location data, even if that location is old.
3.  Event Log - Made some minor changes to device location status messages for consistency.
4.  Configuration Wizard -
    - Reorganized the menus so all the screens dealing with the iCloud account, devices and sensors are on the first page and parameter configuration are on the second page,
    - Apple Verification Code - Added it to the menu. Added an option to request a new code.
    - Change Device Order screen - Added it to the menu.
5.  Stationary Zone - The Stationary Zone handling has been completely rewritten. Now, the Stationary Zone is no longer assigned to a device when iCloud3 starts but is a general zone that is created when it is needed. If several devices are near each other, they are will all move into the same Stationary Zone. Devices can exit the zone just like they exit a normal zone. When all of the devices have left, it is hidden and moved back to it's base location like before. This eliminates the problem of having iCloud3 move a device into it's own zone while HA moves it into another nearby device's zone.

     The Stationary Zone assigned by iCloud3 and the zone assigned HA for the person, the device_tracker state value and the iOS App are now all the same zone.

     The zone's friendly name defaults to 'StatZon#' where '#' is a number assigned to the zone. It is still specified on the Special Zones > Stationary Zone setup screen, where you can assign it's name another value. Using a 7-letter name ('StatZon#') insures it will not be truncated on the Lovelace screen when the device_tracker state value is displayed. The zone's full entity name is 'zone.ic3_statzone_#'.
7.  iOS App Zone Handling - The device's zone is assigned by iCloud3 from the location data from iCloud (FamShr and FmF) and when it is moved into a Stationary Zone. The iOS App device_tracker state value may lag behind this zone change and, in many cases, is not changed at all. iCloud3 will now issue an iOS App location request if the iOS App and iCloud3 zones are not the same after 2-minutes has elapsed. The iOS App will/should then recognize the zone change.
8.  Exit Zone - When a device leaves a zone based on an iOS App Exit Zone trigger, it will schedule an immediate FamShr location update if there are other devices in the same zone. This should help trigger an exit zone update immediately for the other devices that are not using  the zone on their next scheduled location update.
9.  'lost_device_alert' service call - With this service, a phone can be locked and placed in a 'Lost Mode'. A message and phone number can be sent to a device, indicating it has been lost, asking the person that found it to call the number. For more information about this service, review the Apple iCloud User Guide/Use Lost Mode in iCloud.com. It also explains how to turn Lost Mode on or of using the Dind My app. The documentation can be found here - https://support.apple.com/guide/icloud/use-lost-mode-mmfc0f0165/icloud

Example Service Call for an automation or script:
```
        service: icloud3.lost_device_alert
        data:
          device_name: 'gary_iphone'
          number: '123-456-7890'
          message: 'This Phone has been lost. Please call this number to report it found.'
```
10.  Sensor Updates -
    - Last Zone sensors - Fixed several problems where they would not display or would display the wrong value.
    - Battery Level - Fixed a problem where an older iOS App battery level would overwrite a newer FamShr battery level. Also added the update time to the Battery.
    - Direction of Travel - The value will now display Towards or AwayFrom when tracking from the Home Zone. It  will display zone name when tracking from another zone. The waze travel time has been added to list of items that are checked to determine the travel direction.
    - Icons - The icons for the Zone, Last Zone and Direction of Travel sensors have been changed to better indicate if you are at or going towards or away from Home or another zone, or if the devie is in it's Stationary Zone.
    - Next Update time & Interval - 'TfZ' (Track from Zone) is displayed next to the Next Update if the time is for a non-Home tracked zone.

12. Enter Zone Delay - Changed 'PassThru' zone delay to 'Enter Zone' Delay in the Configuration Wizard and on some Event Log messages. Also fixed several issues triggering it.
13. Device Offline - Fixed some problems dealing with 'Location Old (#xx)' Event Log messages and setting the retry interval when a device went offline.
14. NearBy Devices - If one device is a Watch and the other is an iPhone, the devices are paired and within 15m of each other, the Watch's location will not be used for the iPhone. Apple used the location of the paired iPhone with the Watch prior to Watch v7 to conserve the battery so it does not make sense to use the location data.
15. Apple Watch - If the Watch, which is not using the iOS APP to trigger zone exits, is close to another device when the other device leaves a zone, a Zone Exit Trigger will be generated for the Watch. This causes the

13. Did a lot of code cleanup.

**Comment by thiago-s-medeiros** [comment]
Hi @gcobb321 

I'm trying to do a new login (with verification code) with this new update and the input for the verification code isn't showing, and i'm not been able to select "enter verification code" because is in the loading state of the page.

**Comment by gcobb321** [comment]
Go to the Configuration Wizard > Menu > Enter/Request Apple Verification code and enter it or request a new one. 

What it’s displayed when it is in the ‘ loading state of the pages’.

Have you ever used v3 beta before or is this the first time? Maybe restart HA
