### ISSUE TITLE
B16b: Not always updating

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#127]
I'm trying to get some icloud3 logs for you, but debug logging turns of every time HA restarts and I keep forgetting to re-enable it.

It appears to sometimes get "stuck" when going into or out of zones.

When my wife left home ~2:55 PM, the HA and icloud3 device_trackers updated twice. Then she arrived Town Library Zone, but the icloud3 device_tracker did not reflect this and instead shows an address near to the Town Library Zone. 

![SNAG-1774](https://github.com/gcobb321/icloud3_v3/assets/6526076/1a234d23-7015-48ce-9643-332eb35c2c98)

When I saw this earlier, the icloud3 location got stuck, but it didn't seem to be related necessarily to zones. But then seems to get unstuck when she passed through the Town Library zone.

![SNAG-1768](https://github.com/gcobb321/icloud3_v3/assets/6526076/90960b64-b69e-4895-921f-3d55edf851c7)

**Comment by gcobb321** [comment]
Entering and exiting zones is more controlled by the iOS app than iCloud3. iCloud3 only asks for data on timer intervals (next update, StatZone, enter zone delay). It checks the iOS app device tracker and last update triggers for location and zone changes. 

Check the iOS app Debug logs to see if it issued and enter/exit triggers. The Event Log > Actions > show Tracking monitors gives a detailed log of what is happening internally. I have been through zones and the iOS app has not responded to exiting or exiting. It might be running in the background or in some other show to respond states.

**Comment by Snuffy2** [comment]
The iOS App is detecting the zones correctly. The `HA Device Tracker` in the first image is the device tracker of the iOS App.

**Comment by Snuffy2** [comment]
And in the second picture, the iOS App on the first line is updating its address as she drives, but the iCloud3 location on the second line isn't changing until 11:34 AM.

**Comment by gcobb321** [comment]
The iOS app has a sensor that ends with _geocoded_location_. That sensor reports the address of the device (Clarkston Road, I87, etc). Is that the sensor you are displaying? 

iCloud3 does not have a sensor that reports the address, only the zone it is in or away. iCloud3 monitors the iOS app device_tracker entity which shows the zone the device is in. The one it is monitoring is shown in step 5 of the Event Log during start up. Mine is _device_tracker.gary_iphone_app_.

The zones that are used are the HA zones setup on the Settings > Areas& zones tab. These are listed in Stage 2 on the Event Log during start up. 

Go to Settings sidebar > Developer Tools > States to see the state values of the d_t and sensor entities.

**Comment by Snuffy2** [comment]
I have both the HA iOS App Device Tracker and the iCloud3_v3 device tracker setup as [places](https://github.com/custom-components/places) sensors which is doing the geolocation.

**Comment by gcobb321** [comment]
That is pretty cool. I had thought of looking into some type of gps/address resolution to be able to identify where a stationary  is. Now I know where to get the code from.

Thanks.

Places work on changes to gps locations. If the iOS App changes the location but does not change the iosapp d_t state value or does not a significant update, iC3 will not pick it up. I'll play around with it after fixing several other things and see if I can monitor the gps changes as well.

**Comment by Snuffy2** [comment]
Full disclosure, I maintain the places repo so if I can be of any help let me know.

icloud3 v2 worked great with places and would update at nearly the same time as the HA iOS device tracker. Most of the time icloud3 v3 updates similarly, but at times it just seems to get stuck as above. Not sure what's causing it though.

**Comment by gcobb321** [comment]
FYI - I have been out all day with my wife joining me mid morning. This is a screenshot of our activities. It looks like everything is updating like it should.

![image](https://github.com/gcobb321/icloud3_v3/assets/35449479/591bb27e-dcd6-46a6-b401-5caadea8e600)

**Comment by Snuffy2** [comment]
Agreed. More recently, everything seems to be updating ok again.

**Comment by gcobb321** [comment]
Snuffy2,
The Places Integration dumps a lot of entries into the HA log file. I haven’t looked at the code but is there a way to limit it to just the final result?

(gary_iosapp_place) Starting Update...
(gary_iosapp_place) Calling update for device_tracker.gary_iphone_app due to: Scan Interval (gary_iosapp_place) Distance from home [home]: 0.001 km] 
(gary_iosapp_place) Travel Direction: towards home
(gary_iosapp_place) Meters traveled since last update: 53.3] 
(gary_iosapp_place) Meets criteria, proceeding with OpenStreetMap query
(gary_iosapp_place) DeviceTracker Zone: home 
(gary_iosapp_place) Requesting data for OpenStreetMaps

**Comment by Snuffy2** [comment]
What is your overall HA Log Level set to or the log level for just `places` set to? Default level is `warning` I believe.

Those lines you show are `info` and/or `debug` level logging. If you have the log level set to `info` or `debug` those lines will show.

**Comment by Snuffy2** [comment]
Right. Those are info level logging statements. The default log level is warning so they don't show for most users at all. I have some info level logs for those that like that type of information without the full debug logging.

**Comment by gcobb321** [comment]
Gotcha. I’m wrapping up b17 and will put it up this weekend. Do you want to try an early copy?

**Comment by Snuffy2** [comment]
Sure. I'd be happy to.

**Comment by JtwoA** [comment]
I'll try it, sure.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by gcobb321** [comment]
A prerelease of it is attached.
Unzip into the icloud3 directory.

[icloud3_v3-beta-17.zip](https://github.com/gcobb321/icloud3_v3/files/11556156/icloud3_v3-beta-17.zip)

### Change Log:
Beta 17 - 5/24/2023
...................
1.  iCloud Reauthentication - Fixed a problem where the reauthentication notification kept repeating after the authentication code was accepted. This also fixed the problem where two Authentication Entry windoes were on the HA Devices & Settings screen that could not be closed.
2.  Configuration Wizard/iCloud Account Credentials screen:
    1. Changed it's name to Data Sources - iCloud Account & iOS App
    2. Split the 'iCloud Account' data source into 2-options - Family Sharing List and Find-my-Friends to prevent FmF error messages during start up.
3.  New Configuration Parameter - Added a Display GPS Coordinates (Format Parameters screen) - This option indicates if the GPS Coordinates/Accuracy or only the GPS Accuracy should be displayed in the Event Log
4.  Log Level - A Debug log level that automatically turns off at midnight was added (Format Parameter Screen).
    NOTE: A BROWSER REFRESH IS REQUIRED

5.  Event Log > Actions - The log_level is now saved to the configuration file when it is set to a new value (Start/Stop Debug or Rawdata Logging).  You no longer have to go to the Configuration Wizard to save it. The Start Debug Log is automatically turned off at midnight.
6.  Fixed several issues related to the v2-to-v3 migration and installating iCloud3 for the first time.
7.  Other internal changes dealing with tracking methods/data sources, non-availability of FmF as a data source, code cleanup, etc.
