### ISSUE TITLE
Empty log card

### ISSUE THREAD

**Issue by Toolhead** [gcobb321/icloud3_v3#128]
I've set up icloud3 v3 16b and want a event log card.
It shows up almost empty, while 2 iPhones are monitored.
See [here](https://rob-lilian.nl/images/temp/log.png)
What can I do to remedie this?

**Comment by gcobb321** [comment]
That is the v2 Event Log. Have you refreshed your browser?

**Comment by Toolhead** [comment]
That was it, thanks!
