### ISSUE TITLE
Tracker switching from stationary to away

### ISSUE THREAD

**Issue by Nuuki9** [gcobb321/icloud3_v3#131]
I'm seeing what seems to be some odd behaviour. My wife went out earlier today, and here's what I'm seeing from ther ic3 device tracker:

![image](https://github.com/gcobb321/icloud3_v3/assets/30313491/e6e64cbd-54cf-414f-848e-52dbb24befa0)

She did stop off to do a couple of things, but on numerous occasions ic3 has put her in a stationary zone, only to then revert back to _away_ a few seconds later. Looking my own tracker from yesterday I see similar behaviour. One of the times it did this for me was during a car journey during which I didn't stop off on the way - I would have stopped for lights etc, but nothing that should have triggered ic3 to believe I was stationary for any meaningful length of time.

Is it possible ic3 is being a bit too trigger happy in terms of when it puts a device into a stationary zone?

**Comment by gcobb321** [comment]
Check the _still time_ on the Configuration Wizard  > Page 2 > Special Zones screen. A short time value will do that. The default is 8. 

Check the Event Log. It shows when a device will move into a StatZone and if the time changes due to movement in the Results line.

**Comment by Nuuki9** [comment]
I checked and it was set to 8 minutes. Its too late to grab the event log covering that period, but I can keep an eye on it over the next coupld of days and if I see the same thing I'll export the logs and provide an update.

**Comment by Nuuki9** [comment]
We were away for the weekend so I thought I'd check out the tracking data when we got back to see if I was still seeing issues with the Stationary Zone triggering.

Looking at a 2.5 day period, my wife's phone went into a stationary zone 15 times - no issue there. However, in 10 of those cases, it then reverted back to Away within 15 seconds. For that to be legitimate, we'd be saying that in two thirds of cases, she was stationary *just long enough* to trigger the stationary zone (8 minues) and then immediately moved enough to break out of it. Clearly that's not the case.

Anyone else seeing anything like this?

**Comment by gcobb321** [comment]
Do you have any Log files that show any movement that would take her out of the zone?
What v3 beta version are you using?

**Comment by Nuuki9** [comment]
The logs from the weekend are gone, but I do have one example from yesterday:

<img width="160" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/30313491/10292681-00e4-44a0-8202-5c7db4207def">


These are the log entries from that time:

```
11:39:31a	   UPDATED FamShr Data > RequestedBy-kalis_iphone⣇⠋•⠉richards_iphone, 11:20:52a/±35m → 11:22:49a/±13m⣇⠋✓⠈kal
					is_iphone, 11:20:53a/±7m → 11:21:12a/±9m
11:39:31a	   iCloud Acct Auth (#22) > Token, Last-11:20:47a (19 min ago)
11:39:31a	   ADDED StationaryZone-ic3_statzone_1
11:39:35a	   UPDATED iOSApp > kalis_iphone, Exit Zone, ⣇⠋•⠉Loc-11:26:21a, Home-12.9 km, (LONG, LAT/±5m)
11:39:40a	   UPDATED iOSApp > kalis_iphone, Exit Zone, ⣇⠋•⠉Loc-11:36:22a, Home-12.9 km, (LONG, LAT/±5m)
11:39:50a	   UPDATED iOSApp > kalis_iphone, Exit Zone, ⣇⠋•⠉Loc-11:39:40a, Home-12.8 km, (LONG, LAT/±4m)
```

I'm running v3.0.0b16b

**Comment by gcobb321** [comment]
Kalis exited a zone at 11:26, 11:36 and 11:39. Can you tell from the previous Event Log entries if she was in a zone and which one? Was that Exit processed them or ignored? I’m trying to tell if the exit was for another zone that took p place before the StatZone was created which should have been ignored. 

Also, did the iosapp put her into the StatZone? Or did it still show her away?

If you can, send the log file to geekstergary@gmail.com and I might be able to figure it out.

**Comment by gcobb321** [comment]
Did you review the Event Log to see what was going on at that time it was going into and out of the StatZone? You might notice something immediately that would take me a while. Also, and errors in the HA logs?

**Comment by Nuuki9** [comment]
Looking at my phone, it went "stationary" 10 times over the course of the journey, rarely for more than 6 seconds. I took a look at 3 such events in the logs which occured in a cluster - from 12:23:35 to 12:36:46:

```
12:23:35p	   Updated > FamShr-12:16:04p/±5m → 12:16:09p/±5m (7 min ago), Moved-81 m
12:23:35p	   Located > FamShr-12:16:09p/±5m (iOSApp-11:59:54a)
12:23:35p	   Setting StatZone Location (StatZon) > StationarySince-12:15:35p (8 min ago), GPS-(51.31347, -0.35350)
12:23:40p	   iOSApp Monitor > Trigger-Exit Zone@11:59:54a (24 min ago), State-not_home@12:19:56p (4 min ago), LastTrig
					ger-FamShr@12:16:04, iOSAppData-11:59:54a, LastZoneExit-ic3_statzone_1@12:19:56p, WillUpdate-False-B
					
12:23:40p	   Updated > FamShr-12:16:09p/±5m → 12:23:39p/±5m (1 sec ago), Moved-4.17 km
12:23:40p	   Located > FamShr-12:23:39p/±5m (iOSApp-11:59:54a)
12:23:40p	   Trigger > Next Update Time Reached
12:23:40p	   Exited Stationary Zone (StatZon)
			┌─ iCloud update started > Next Update Time Reached
12:23:40p	│  Zone > Away > Care Home-14.7 km,Swimming-44.3 km,Home-47.8 km,Library-48.7 km,Forest School-49.2 km,Rose 
			│		Cottage-54.1 km,Music Class-62.3 km, GPS-(51.30728, -0.41245/±5m)
12:23:40p	│  Nearby Devices (&lt;20m) > ✓Kali/iPhone-2m/±5m
12:23:40p	│  Using Nearby Device Results > Kali, Distance-2 m
12:23:40p	├─ Results: From-Home > NextUpdate-1:06:55p, Interval-43 min, TravTime-1.2 hrs, Distance-45.3 mi, Direction-
			│		Towards, IntoStatZone-12:28:35p, Battery-80%
»Home		│  iOSAppState-Away, iCloud3Zone-Away, Interval-43 min, TravelTime-1.2 hrs, Distance-45.3 mi
			└─ iCloud update completed > Date source - FamShr
12:23:40p	   Device Monitor > famshr, Next Update Time Reached, AttrsZone-not_home, LocDataZone-not_home, Located-12:2
					3:39p (1 sec ago), iOSAppGPS-(51.31104, -0.37693/±5m), iOSAppState-not_home), GPS-(51.30728, -0.4124
12:23:45p	   iOSApp Monitor > Trigger-Sig Loc Change@11:59:54a (24 min ago), State-not_home@12:19:56p (4 min ago), Las
					tTrigger-FamShr@12:23:39, iOSAppData-11:59:54a, LastZoneExit-ic3_statzone_1@12:19:56p, WillUpdate-Fa
					
12:28:35p	   Updated > FamShr-12:23:39p/±5m → 12:23:44p/±5m (5 min ago), Moved-26 m
12:28:35p	   Located > FamShr-12:23:44p/±5m (iOSApp-11:59:54a)
12:28:35p	   Setting StatZone Location (StatZon) > StationarySince-12:20:35p (8 min ago), GPS-(51.30736, -0.41280)
12:28:35p	   Located > FamShr-12:23:44p/±5m (iOSApp-11:59:54a)
12:28:40p	   iOSApp Monitor > Trigger-Exit Zone@11:59:54a (29 min ago), State-not_home@12:24:57p (4 min ago), LastTrig
					ger-FamShr@12:23:39, iOSAppData-11:59:54a, LastZoneExit-ic3_statzone_1@12:24:57p, WillUpdate-False-B
					
12:28:40p	   Updated > FamShr-12:23:44p/±5m → 12:28:39p/±5m (1 sec ago), Moved-2.01 km
12:28:40p	   Located > FamShr-12:28:39p/±5m (iOSApp-11:59:54a)
12:28:40p	   Trigger > Next Update Time Reached
			┌─ iCloud update started > Next Update Time Reached
12:28:40p	│  Zone > Away > StatZon-2.01 km,Care Home-12.8 km,Swimming-42.6 km,Home-46.0 km,Library-47.0 km,Forest Scho
			│		ol-47.6 km,Rose Cottage-56.1 km,Music Class-60.6 km, GPS-(51.31655, -0.43761/±5m)
12:28:40p	│  Nearby Devices (&lt;20m) > ✓Kali/iPhone-2m/±5m
12:28:40p	│  WazeHistDB > Get All Records, Table-locations, Criteria- lat_long_key=`51.3166:-0.4376`, RecdCnt-0
12:28:41p	│  Waze Route Info > TravTime-1.1 hrs, Dist-63.7 km, WazeMoved-2.04 km, CalcMoved-2.04 km, Took-1.61 secs 
12:28:41p	├─ Results: From-Home > NextUpdate-1:09:05p, Interval-40 min, TravTime-1.1 hrs, Distance-39.6 mi, Direction-
			│		Towards, IntoStatZone-12:36:40p, Battery-80%
»Home		│  iOSAppState-Away, iCloud3Zone-Away, Interval-40 min, TravelTime-1.1 hrs, Distance-39.6 mi
			└─ iCloud update completed > Date source - FamShr
12:28:41p	   Device Monitor > famshr, Next Update Time Reached, AttrsZone-not_home, LocDataZone-not_home, Located-12:2
					8:39p (3 sec ago), iOSAppGPS-(51.30920, -0.41896/±5m), iOSAppState-not_home), GPS-(51.31655, -0.4376
12:28:45p	   iOSApp Monitor > Trigger-Sig Loc Change@11:59:54a (29 min ago), State-not_home@12:24:57p (4 min ago), Las
					tTrigger-FamShr@12:28:39, iOSAppData-11:59:54a, LastZoneExit-ic3_statzone_1@12:24:57p, WillUpdate-Fa
					
12:30:00p	   Nearby Devices (&lt;20m) > ✓Kali/iPhone-2m/±5m, Checked-12:28:40p
12:36:40p	   Updated > FamShr-12:28:39p/±5m → 12:28:44p/±5m (8 min ago), Moved-13 m
12:36:40p	   Located > FamShr-12:28:44p/±5m (iOSApp-11:59:54a)
12:36:40p	   Setting StatZone Location (StatZon) > StationarySince-12:28:40p (8 min ago), GPS-(51.31662, -0.43775)
12:36:40p	   Located > FamShr-12:28:44p/±5m (iOSApp-11:59:54a)
12:36:45p	   iOSApp Monitor > Trigger-Exit Zone@11:59:54a (37 min ago), State-not_home@12:34:58p (2 min ago), LastTrig
					ger-FamShr@12:28:39, iOSAppData-11:59:54a, LastZoneExit-ic3_statzone_1@12:34:58p, WillUpdate-False-B
					
12:36:45p	   Updated > FamShr-12:28:44p/±5m → 12:36:44p/±5m (1 sec ago), Moved-4.45 km
12:36:45p	   Located > FamShr-12:36:44p/±5m (iOSApp-11:59:54a)
12:36:45p	   Trigger > Next Update Time Reached
			┌─ iCloud update started > Next Update Time Reached
12:36:45p	│  Zone > Away > StatZon-4.45 km,Care Home-8.34 km,Swimming-38.4 km,Home-41.9 km,Library-43.0 km,Forest Scho
			│		ol-43.7 km,Music Class-56.6 km,Rose Cottage-60.6 km, GPS-(51.34323, -0.48550/±5m)
12:36:45p	│  Nearby Devices (&lt;20m) > »Kali/iPhone-4.5km/±5m
12:36:45p	│  WazeHistDB > Get All Records, Table-locations, Criteria- lat_long_key=`51.3432:-0.4855`, RecdCnt-0
12:36:46p	│  Waze Route Info > TravTime-1 hr, Dist-63.5 km, WazeMoved-4.91 km, CalcMoved-4.47 km, Took-1.32 secs 
12:36:46p	├─ Results: From-Home > NextUpdate-1:12:55p, Interval-36 min, TravTime-1 hr, Distance-39.5 mi, Direction-Tow
			│		ards, IntoStatZone-12:44:45p, Battery-80%
»Home		│  iOSAppState-Away, iCloud3Zone-Away, Interval-36 min, TravelTime-1 hr, Distance-39.5 mi
			└─ iCloud update completed > Date source - FamShr
12:36:46p	   Device Monitor > famshr, Next Update Time Reached, AttrsZone-not_home, LocDataZone-not_home, Located-12:3
					6:44p (3 sec ago), iOSAppGPS-(51.33105, -0.48091/±5m), iOSAppState-not_home), GPS-(51.34323, -0.4855
```

Something that struck be as being very odd is that these 3 phases of it being stationary actually overlap. In other words, prior to the 2nd occurance of it being dropped into the StatZone, it was stationary for 8 minutes (the configured period), and this 8 minute period overlaps with the prior phase of it being stationary, from which it dropped out. So that's definitely odd.

I plotted the GPS locations and they're on the road I was on, fairly close. I'm confident that we were not stationary for 3 separate 8 minute periods, though I don't have specifics. I'm not suggesting the GPS is wrong here, and without something like Google Maps location history (which I had turned off) I don't have anything to correlate with. I may turn on Location History for now as that would be a useful reference.

So a bit inconclusive - its clearly not correct that my phone was stationary just 5 seconds longer than the threshold on 7 times out of 10, and those overlapping periods seem like they shouldn't be possible, but not sure if the logs are providing any real clue as to the cause.

**Comment by gcobb321** [comment]
One of the movements into the StatZone is:
```
12:28:35p          Updated > FamShr-12:23:39p/±5m → 12:23:44p/±5m (5 min ago), Moved-26 m
12:28:35p          Located > FamShr-12:23:44p/±5m (iOSApp-11:59:54a)
12:28:35p          Setting StatZone Location (StatZon) > StationarySince-12:20:35p (8 min ago), 

12:28:40p	   Updated > FamShr-12:23:44p/±5m → 12:28:39p/±5m (1 sec ago), Moved-2.01 km
12:28:40p	   Located > FamShr-12:28:39p/±5m (iOSApp-11:59:54a)

```
At 12:38, The location data had been updated at 12:23 so that location was 5-minutes old. The StatZone timer started at 12:20, 3-minutes before the old data so really the timer should be based on the age of the data, not the current time or at least be reset to the data time of the data time is old. I’ll check it out and see what’s the best way to handle it. 

Thanks.

**Comment by gcobb321** [comment]
I've added a check to not create a statzone when the current data is old.

UnzIp this into the /icloud3 directory and restart HA

[icloud3_main.zip](https://github.com/gcobb321/icloud3_v3/files/11691971/icloud3_main.zip)

**Comment by Nuuki9** [comment]
OK I've got that running. We'll be travelling over the weekend so I'll report back on Monday on how it compares...

**Comment by Nuuki9** [comment]
That seems to have done the trick - I didn't have any triggers of these very brief and/or overlapping Stationary Zones.

**Comment by Nuuki9** [comment]
That seems to have done the trick - I didn't have any triggers of these very brief and/or overlapping Stationary Zones. Thanks again!

**Comment by gcobb321** [comment]
Great.
