### ISSUE TITLE
Since b16b, keep getting asked to re-authenticate with icloud

### ISSUE THREAD

**Issue by RealGandy** [gcobb321/icloud3_v3#132]
Since installing b16b (I think that;s when it started) I am constantly getting the persistent notification that cloud3 needs reconfiguration. The icloud3 tile is red and asks for 2fa authentication again. I run through the process and it accepts the new code but very quickly afterwards I get the reauth required again. This reauth required can also be triggered by forcing a locale all devices.

Event card shows successful completion thus:

![image](https://github.com/gcobb321/icloud3_v3/assets/305484/7173b0be-e391-49ee-85cc-90f0ee5e2294)

Still an issue on b16c

Nothing in the homeassistant.log

It appears that updates do still continue, albeit with [I think unrelated as this behaviour was seen previously] two devices that are FamShr only seem to stall for a significant time (hours) until I restart icloud3 from the eventcard menu.

**Comment by FireROR** [comment]
I have the exact same issue. Restart the iCloud3 and even HA couple times and it pops up again

**Comment by gcobb321** [comment]
Go to the _Configuration Wizard > Page 2 > Format_ and set _Log Level_ to RawData. That will show the response codes from Apple. Restart HA and after this happens a few times sends me the _icloud3_debug.log_ file. I’ll see if I can see what it’s going on. 

Email to geekstergary@gmail.com

**Comment by JtwoA** [comment]
Chiming in, I re-authed via the mobile app last night, again from HA desktop this morning and then immediately again before it accepted and let me do other things. Sending you logs privately.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by pitoganzado** [comment]
Same issue here... any way to fixed?

**Comment by gcobb321** [comment]
Working on it.

**Comment by gcobb321** [comment]
The beta 17 2fa that google might have blocked

[icloud3_v3-beta17-2fa-test.zip](https://github.com/gcobb321/icloud3_v3/files/11569922/icloud3_v3-beta17-2fa-test.zip)

**Comment by JtwoA** [comment]
Got it - installing now and then heading out for a bit.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by JtwoA** [comment]
Things already look happier. I'll keep you posted.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by RealGandy** [comment]
Upon upgrading to this beta and restarting I get the usual prompt to authenticate, but I enter the six digit code from Apple and get a 'Verification code not correct' error. Repeated this a few times with icloud3 and hass restarts etc.

![image](https://github.com/gcobb321/icloud3_v3/assets/305484/c6fe240b-5969-43c3-b362-23e35c9d4a22)

I'll send over the debug log privately

**Comment by gcobb321** [comment]
The code may have expired. Have you tried Requesting a new code?

**Comment by gcobb321** [comment]
John and others,
I think I have it fixed so give this one a shot. 

I found several issues. When I log into Apple, a 'Session' is created. When an authentication is done, a new Session is created and the 6-digit code is entered for the new one. The testing for the authentication being needed was still being done on the old Session with the old data. This was also leading to FamShr data always being old, the testing was done with the data in the old Session that was no longer being used instead of the newly authenticated one.

There is still a lot of debug code in it and code that needs to be cleaned out.

Here it is, unzip to the /icloud3 directory as usual.

[icloud3_v3-beta17-2fa-test.zip](https://github.com/gcobb321/icloud3_v3/files/11580153/icloud3_v3-beta17-2fa-test.zip)

**Comment by JtwoA** [comment]
On it, boss. Will let you know.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by gcobb321** [comment]
Here is a clean copy of b17 without any special debug messages. 
There is a change to the Event Log so yu will bet a browser refresh message.

[icloud3_v3-beta-17.zip](https://github.com/gcobb321/icloud3_v3/files/11583139/icloud3_v3-beta-17.zip)

**Comment by JtwoA** [comment]
Loaded up and running.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by RealGandy** [comment]
That seems to have fixed it for me on first load and first 'locate'... will give it the day and come back to close later if still good.

**Comment by JtwoA** [comment]
Installed.

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------

**Comment by gcobb321** [comment]
Thanks for all of your help. I just uploaded b17

**Comment by JtwoA** [comment]
Thanks for your persistence!

John Alan
[image]

01000011 01110101 01110010 01101001 01101111 01110011 01101001
01110100 01111001 00100000 01101001 01110011 00100000 01110100
01101000 01100101 00100000 01101101 01101111 01110011 01110100
00100000 01110110 01100001 01101100 01110101 01100001 01100010
01101100 01100101 00100000 01100110 01100101 01100001 01110100
01110101 01110010 01100101 00100000 01101111 01100110 00100000
01101001 01101110 01110100 01100101 01101100 01101100 01101001
01100111 01100101 01101110 01110100 00100000 01101100 01101001
01100110 01100101 00101110

------- Original Message -------
