### ISSUE TITLE
HA tried to start icloud3 from a configuration.yaml file

### ISSUE THREAD

**Issue by spry-salt** [gcobb321/icloud3_v3#135]
iCloud3 reports this message on startup:
"HA tried to start icloud3 from a configuration.yaml file"

I'm running the most current pre-release version and have combed through all my yaml files to try to find any reference to the older version of icloud3 but I can't. Am I missing something obvious or is there somewhere else I should be looking?

**Comment by gcobb321** [comment]
b17 has been released. There must be an evntry somewhere, maybe in an includes sub-directory
