### ISSUE TITLE
[Request] Notify on FMF/general method grab fail

### ISSUE THREAD

**Issue by KairuByte** [gcobb321/icloud3_v3#136]
I didn't notice the initial issues with FMF until a couple weeks after they started because I don't typically look at the map to ensure everyone is being tracked. It would be useful to push a notification when a method fails, even if it's just to the HA notification tab.

**Comment by gcobb321** [comment]
FmF can now be excluded from iCloud3 as a data source. It is set to an excluded status when iCloud3 is installed.

**Comment by KairuByte** [comment]
This was more of a “on source failure, notify in the notification section of HA” rather than “disable FMF.”

I get that the FMF issue was the most recent, but I’m looking for an “in your face” alert to a source grab issue. Like “integration cant log in” or “FMF is down” or “iCloud data malformed,” etc.
