### ISSUE TITLE
v3 beta 16c1 not adding the v3 integration

### ISSUE THREAD

**Issue by timaseth** [gcobb321/icloud3_v3#137]
Hi Gary,

So, I am/was on 2.4.7 on a HA docker install (latest HA version as on date).
Deleted the old iCloud3 folder and created a new one with the latest beta assets files in it (47 files).
Restarted.
While adding the integration, all I get is the old app and the following error.
<img width="475" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/60132339/43113941-2c64-470c-b282-98c0b02f9f1a">
<img width="529" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/60132339/ca6b814c-b51f-44ab-982e-b37f7de517fa">

**Comment by gcobb321** [comment]
I suspect you reinstalled the v2.4.7. The latest beta is b16c1. The 'Select Brand' screen should show 'iCloud3 v3', not 'iCloud3 Device Tracker'. See if the icloud3/const.py file has VERSION = '3.0.0b16c' at the top. If the file does not exist or it does not, get the zip file again and unzip it.

Also, if you are running in a docker container, you might have to rebuild the container.

**Comment by timaseth** [comment]
Thanks Gary!
So I decided to start from scratch and cleared all traces of the old install (files, yamls).
Installed the latest beta using the transfer of directory to /config/cus...
This time around, the v3 showed up in itegrations but clicking on it shows this error:
<img width="501" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/60132339/71e2e0d5-b536-46a0-97fc-abaa9d1ab5e8">

**Comment by gcobb321** [comment]
I googled 'home assistant invalid handler specified' and it appears to be a home assistant/docker issue. There are some solutions on the responses. Try googling that and see if any applies to your set up.
