### ISSUE TITLE
Use status of static device tracker to trigger exit/enter home zone

### ISSUE THREAD

**Issue by japyjaap** [gcobb321/icloud3_v3#138]
Hi Gary,

I really love your work on iCloud3. My wife and children don't have the iOS app installed and with V3 it is helpful that you can set the polling frequency separately in this case. However when my wife and children are at home the polling frequency can go down. I'm using a static device tracker (through the unified integration) that marks people at home when connected to the wifi. 

So in my use case it would be helpful if the polling frequency can be different when persons are detected in the Home zone. When leaving home (disconnecting from my network) this would trigger a change to the polling frequency (I guess this is what being done through the iOS app right now).

**Comment by gcobb321** [comment]
You can set the next location update using the iCloud3 `action` service call. When you exit a zone, do an immediate locate (`command: locate`) or do one in 5 secs (`command: locate 5 secs`). This should set your status to away. 

See iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3/#/chapters/3.1-other-topics?id=device-tracker-services) for info about the service calls.
