### ISSUE TITLE
Apple Verification Code

### ISSUE THREAD

**Issue by woopstar** [gcobb321/icloud3_v3#140]
I am running b16c currently.

Since a few days ago, my integration suddenly keeps asking for the verification code.

<img width="595" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/2997782/79248b57-255c-4f76-87e7-ff3143423c88">

I am able to request a new code fine and also send it where as the integration accepts it. But 2 minutes after it says it needs a verification code again and the "loop" continues.

**Comment by gcobb321** [comment]
I just uploaded a preliminary beta 17 to some others who had the same problem. Get it[ here](https://github.com/gcobb321/icloud3_v3/issues/132#issuecomment-1565711401)

**Comment by woopstar** [comment]
> Get it[ here](https://github.com/gcobb321/icloud3_v3/issues/132#issuecomment-1565711401)

How would I install a zip? ;D

**Comment by gcobb321** [comment]
I guess your not a computer guy and installed it using a HACS custom repository. I hope to set up a new release this afternoon. Try restarting HA for now.

**Comment by gcobb321** [comment]
b17 has been released
