### ISSUE TITLE
On HA Restart, icloud3 v3 sometimes doesn't detect any devices

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#143]
I'm working to identify a way to reliably reproduce this, but recently when restarting HA, it seems to be ~50/50 whether icloud3 v3 will properly load devices or not. If I manually restart icloud3 v3, it starts working again. I'm not 100% sure, but I don't recall seeing this prior to Beta 17.

What I've also noticed from this is that I don't have a good way to automatically determine if an icloud3 v3 device is working or not. The values of all of the entities just seem to stay the same. If this happens, could the Badge, device_tracker, and/or some other entity be set to Unknown/Unavailable/None?

Let me know if there are other logs or specifics you'd like to see.

[icloud3-event-log_2023.05.29-11.22.10 - Failed.log](https://github.com/gcobb321/icloud3_v3/files/11628252/icloud3-event-log_2023.05.29-11.22.10.-.Failed.log)
[icloud3-event-log_2023.05.29-11.31.13 - Success.log](https://github.com/gcobb321/icloud3_v3/files/11628254/icloud3-event-log_2023.05.29-11.31.13.-.Success.log)

![IMG_9369](https://github.com/gcobb321/icloud3_v3/assets/6526076/1e39bd67-5eb8-41b1-8e25-a826df896258)

**Comment by marceloaf** [comment]
I'm having the same issue. Specially related to my apple watch.

**Comment by gcobb321** [comment]
This has Happened to me to. When I look at the logs generated using log level `rawdata`, and looking at the data returned from Apple, the devices that are unverified/missing is because they are not returned from Apple during the initial authentication. iCloud3 does an automatic retry and asks for the data again 1 time. Sometimes it then gets it, sometimes not. An Event Log > Actions >Restart Usually takes care of the problem. 

Set the log level to `rawdata`, then dig thru the _icloud3-debug.log_ and you will see what I mean. 

In b17, the fmf data source can be turned off. Configuration Wizard > Data Sources screen. Uncheck FmF

**Comment by gcobb321** [comment]
I've made some changes to detect devices without location or other information that are not verified when iC3 starts. If there was a communications delay with a response from Apple, the device info might not be available when it is needed and you would get the No Devices Detected error message. You would also get a No Location Data error for an individual device if nothing was returned. This was more likely to happen with a Watch that was asleep. I've added more retries when this happens.

Also included is a `recorder_prefilter.py` module you may be interested in that can be used in `places` component sensors.py module where you are adding a sensor to the exclude list (e_exclude_e). if the comprehensive attributes parameter is enabled.. In 2023.6.0, the HA recorder.py was rewritten to be more efficient. The changes meant a program could no longer update the exclude entities table in the recorder and then have those entities excluded from the HA log data base after HA and the recorder had started. The `recorder_prefilter.py` module contains a filter that is injected into the HA recorder filter process. You can add sensors to be filtered when adding the prefilter, You can also add sensors to the list list at a later time. If a sensor to be excluded is in the prefilter list, it will be excluded, if not, contol is passed to the HA recorder and everything is done as if the prefilter is not there. A complete description is in the `recorder_prefilter.py` module. 

Unzip the zip file to the icloud3 directory. I'll publish this as a beta 18 in a couple of days if everything looks good.

Gary

[icloud3_v3-beta-18.zip](https://github.com/gcobb321/icloud3_v3/files/11750166/icloud3_v3-beta-18.zip)

**Comment by Snuffy2** [comment]
Loaded b18 and it ended up going into an endless loop. That also seemed to cause problems with a bunch of other integrations for unclear reasons. I've grabbed the icloud3 event log, icloud3 debug log and HA log. I'd rather not post all of the personal information in the logs and they take a while to deidentify. But I'd be happy to email them to you (or send them some other way). Send me an email to: 7v9w5q12@mail.snuffy2.com and I'll reply back with the logs.

For now I'm going to revert back to b17 on my Production Home Assistant.  Happy to load b18 in my development HA and try other things as needed.

Also, thanks for the info on how you are now excluding entities from the recorder!!! I haven't looked in detail yet, but I'm very appreciative for you sharing your knowledge.

**Comment by Snuffy2** [comment]
Interestingly, this was on my production HA where there were/are FamShr devices setup, at least on b17. I'll give 18a a try soon.

**Comment by gcobb321** [comment]
Fixed in beta 18
