### ISSUE TITLE
Update Polling Interval

### ISSUE THREAD

**Issue by 951ryan** [gcobb321/icloud3_v3#146]
Looking for some help writing a script to set the polling interval for a specific device manually.   

With iCloud3 v2 I was able to achieve this via a script like this...

alias: Set iCloud Update 30 Seconds (Bob)
sequence:
  - service: device_tracker.icloud3_set_interval
    data:
      device_name: bob_iphone_13
      interval: 30 sec
mode: single

But Im having problems finding the working command for iCloud3 v3 beta 17.   I was able to get a very sketchy workaround by doing the command: resume for a specific device and then triggering that script to run every __ minutes as a workaround but would love to learn the proper command to manually set the polling interval.

alias: iCloud3 v3 Test
sequence:
  - service: icloud3.action
    data: 
      device_name: bob_iphone_13
      command: resume
mode: single

**Comment by gcobb321** [comment]
See action service call [here](https://gcobb321.github.io/icloud3_v3/#/chapters/3.1-other-topics?id=icloud3action-service). Use the _locate_ option (ex. locate 1 min)
