### ISSUE TITLE
patform: icloud3 statement

### ISSUE THREAD

**Issue by chupacabra71** [gcobb321/icloud3_v3#15]
I'm seeing this in the logs, but for the life of me i cannot find anywhere in my config files a `platform: icloud3` statement and i have deleted the `config_ic3.yaml` file.  not a big issue, just a bit confusing.  

> This error originated from a custom integration.
> 
> Logger: icloud3
> Source: custom_components/icloud3/device_tracker.py:48
> Integration: iCloud3 Device Tracker (documentation, issues)
> First occurred: 11:21:44 AM (1 occurrences)
> Last logged: 11:21:44 AM
> 
> ICLOUD3 ALERT: The HA `configuration.yaml` file contains a `PLATFORM: ICLOUD3` statement. iCloud3 v3 is now an integration and does not use the `configuration.yaml` or `config_ic3.yam` files. 1. Remove `PLATFORM: ICLOUD3` statements from `configuration.yaml`. 2. Restart Home Assistant 3. Add iCloud3 on the `Devices & Settings > Integrations` screen 4. Configure iCloud3 on the Integrations screen 5. Restart iCloud3
>

**Comment by gcobb321** [comment]
There is a statement in the /config/configuration.yaml file or in an include statement in that file that has a -platform: icloud3 parameter. That is how iCloud3 v2 started. It must be somewhere or it would not have loaded before v3. The config_ic3.yaml file only contained device and general parameters, not the initial commands used by HA to start iCloud3 v2.

**Comment by chupacabra71** [comment]
yep, you were right, it was buried in an tree of includes.  thanks!
