### ISSUE TITLE
Feature request: Minimal logging settings option for Logbook

### ISSUE THREAD

**Issue by romlisrl** [gcobb321/icloud3_v3#150]
Hi,
I appreciate the work done, but I would like to suggest a settings option that would minimize logging to Home Assistant.
My Logbook is full of entries similar to as below provided:
device_name NextUpdate changed to 9:40:25p

And in case you have not one device setuped, you will see every minute all logs for all of them.
![image](https://github.com/gcobb321/icloud3_v3/assets/49437281/3dec173a-cbca-4379-aec7-6d5ec875e721)

**Comment by gcobb321** [comment]
iCloud3 excluded a lot of sensors from the recorder/log book until HA made a massive change to in in the 2023.6.0 update.. updating the excluded sensors is not a publish feature of HA except through the recorder configuration .yaml parameter and requires a hack to make it work by a program. It took some reengineering to figure out what they did but I have that working and it will be in the next beta.
