### ISSUE TITLE
FamilySharing not working permanently

### ISSUE THREAD

**Issue by Fuian3** [gcobb321/icloud3_v3#153]
Hi everyone,

I have the problem, that my wife is not permanently traceable through FamilySharing. Seems to be a problem with iCloud-Login. Does someone have a solution for me? Restarting iCloud3 resolves the problem for a day.

br
Florian
![IMG_0371](https://github.com/gcobb321/icloud3_v3/assets/116919502/1667ab9c-ceb1-4d83-9a40-3ca047e80ec4)

**Comment by gcobb321** [comment]
I have updated the iCloud3 docs and have added a section dealing with Tracking problems like yours. Go [here](https://gcobb321.github.io/icloud3_v3/#/chapters/4.2-device-tracking-problems?id=not-all-of-the-devices-are-being-tracked) if there still a problem.

**Comment by gcobb321** [comment]
Install b19.1 and create a new issue if you are still having a problem
