### ISSUE TITLE
Confused with versioning

### ISSUE THREAD

**Issue by GerdRuetten** [gcobb321/icloud3_v3#156]
Dear all,

i‘m confused with versioning (see screenshot)

<img width="1112" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/97361636/b151bc12-50b2-4870-a6b0-e9d1313d5586">

According to which scheme is the version number assigned?

What is the current (beta) version?

TIA and best regards!

Gerd

**Comment by gcobb321** [comment]
Beta 18.5 is the latest. 18a and 18b were not released but used for testing with specific users. 18c and 18d was released. I went to a decimal for releases when I got it working work HACS.
