### ISSUE TITLE
icloud3_v3 Migration Peculiar

### ISSUE THREAD

**Issue by obiwantoby** [gcobb321/icloud3_v3#158]
Hi there. I did a few migrations to iCloud3v3. It worked great for most. On one installation, having a weird issue.

The configuration migration pulls in an out of date, old iCloud password. I update it. I then get a prompt for 2 factor code. I put that in. I get a 'unknown error occurred'. I restart home assistant then the account with the old password is then recovered, same results. I tried removing the configuration.yaml parameters and the old ic3 yaml, and reinstalling the icloud3v3.

1. Can I somehow reset this to start over again?
2. Where would the information be cached so I can remove it?
3. Is there a known issue or something obvious I am missing when the 2 factor code is causing an 'unknown error'?

**Comment by gcobb321** [comment]
The iCloud3 parameters are in the  _config/core/.storage/icloud3/configuration_ file. I would go to the
 Configuration Wizard > Data Sources screen and uncheck  the iCloud data source, remove the username and password and save the configuration first. Then restart iCloud3. Then go back in and put the username and password back in, save and restart iCloud3 again. 
 
This is not a known problem. There should be an error message in the _icloud3-0.log_  file. Can you look for it and email the file to geekstergary@gmail.com so I can see what is going on.

**Comment by obiwantoby** [comment]
Thanks. I wiped the /.storage/icloud3/ folder and removed the entries from configuration.yaml. I am not sure if the FmF previous setup was causing the issue or not. The log simply said logged in was successful, which I found odd with how it was behaving.

Family share is up and working great, FmF, as known, not so much.
