### ISSUE TITLE
local/custom_cards/icloud3-event-log-card.js:1481:38 TypeError: can't convert undefined to object

### ISSUE THREAD

**Issue by UlrichThiess** [gcobb321/icloud3_v3#160]
I have installed the latest Version. Everything works fine, but the Event Log shows:
![grafik](https://github.com/gcobb321/icloud3_v3/assets/79257887/9b7fdb52-7b61-413b-9651-6fa630d87a70)

What do i missing?

**Comment by gcobb321** [comment]
You are seeing the v2 Event Log screen. Refresh your browser.
