### ISSUE TITLE
feature request: traveltime in hh:mm

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#163]
Instead of traveltime as a decimal it would be great to have the traveltime in hh:mm

As workaround I created a template sensor to format traveltime_min into hh:mm, but at ha start the traveltime from iCloud3 is not available for the template-sensor which results in state "unavailable". 

So it would be great to have iCloud traveltime in hh:mm in the original sensor.

Is this possible?

Thanx

**Comment by gcobb321** [comment]
Great idea. And you get a Bogo. I added a travel_time_hhmm and an arrival_time sensor, plus a bug fix.

Beta 19.1 will be uploaded tomorrow but here it is.

[icloud3_v3-beta-19.1.zip](https://github.com/gcobb321/icloud3_v3/files/11996291/icloud3_v3-beta-19.1.zip)

Unzip into the icloud3 directory. But download the update tomorrow also to keep HACS in sync.

**Comment by criticallimit** [comment]
WOW!!

Requested, few hours later delivered! That´s unbelievable! 

Thank you very much for your outstanding work!

**Comment by gcobb321** [comment]
Go to the config settings > Sensors to turn them on. I have all sensor definitions controlled through tables so it was fairly easy to add them. The only problem I had was caused by spelling one of them incorrectly in one of the tables. Thanks for the suggestion.

**Comment by criticallimit** [comment]
Beta 19.1 installed and sensors activated. Working perfect! No Fault in the logs, just working fine.

Thanx again
