### ISSUE TITLE
b19: IndexError: list index out of range on Startup

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#164]
Below is the error in the HA logs on startup. It happens on every HA reboot, but icloud3 does appear to be working despite this. I don't see anything significant before it in the HA logs.

```
2023-07-09 16:06:04.805 ERROR (SyncWorker_5) [icloud3] list index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 286, in stage_5_configure_tracked_devices
    start_ic3.setup_trackable_devices()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1877, in setup_trackable_devices
    PairedDevices[0].PairedDevice = PairedDevices[1]
                                    ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
[icloud3-0.log](https://github.com/gcobb321/icloud3_v3/files/11996103/icloud3-0.log)

**Comment by gcobb321** [comment]
I uploaded the fix around 8am this morning. Grab that release and you should be all set. I did not change the release number. it is still beta 19.

Another subject, when I upload the release and run it through the hasfest Action, I keep getting an error code 1 and it fails. Looking at the log, it appears that it is missing an 'id' field and I have no idea where to start looking for a fix. Do you have any knowledge of what is going on?

Here is the Actions results:
```
Validating application_credentials... done in 0.00s
Validating bluetooth... done in 0.00s
Validating codeowners... done in 0.00s
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 244, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 166, in main
    plugin.validate(integrations, config)
  File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 108, in validate
    _validate_integration(config, integration)
  File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 73, in _validate_integration
    _has_assignment(init, "CONFIG_SCHEMA")
  File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 23, in _has_assignment
    if target.id == name:
       ^^^^^^^^^
AttributeError: 'Attribute' object has no attribute 'id'
Validating config_schema...
Error: Process completed with exit code 1.
```

**Comment by Snuffy2** [comment]
Hmmm... I installed it via HACS on 7/9 @ 11:10am EDT

**Comment by gcobb321** [comment]
I just downloaded the release file (icloud3.zip) and the code there has the fix in it. I didn't create a new release, just deleted the bad icloud3,zip and uploaded the correct one. I wonder if HACS is getting the original upload instead of the new one. If so, I'll upload a new b19.1 release.

The fix is in support/start_ic3.py, lines 1876-1881 should be:
```
    for PairedDevices in Gb.PairedDevices_by_paired_with_id.values():
        try:
            PairedDevices[0].PairedDevice = PairedDevices[1]
            PairedDevices[1].PairedDevice = PairedDevices[0]
        except:
            pass
```

What color is the Config Settings fear on the Event Log, is it cyan or purple. the cyan was in the original release, purple was the uploaded one.

**Comment by Snuffy2** [comment]
I went into HACS, icluod3, selected Redownload and restarted HA. Still the same error as above.

Settings gear is cyan (I believe):
<img width="504" alt="2023-07-09_17-57-59" src="https://github.com/gcobb321/icloud3_v3/assets/6526076/71c5a89d-e098-417c-8d9a-6e31c5b9036b">

My support/start_ic3.py, lines 1876-1881:
```
    for PairedDevices in Gb.PairedDevices_by_paired_with_id.values():
        PairedDevices[0].PairedDevice = PairedDevices[1]
        PairedDevices[1].PairedDevice = PairedDevices[0]

    for devicename, Device in Gb.Devices_by_devicename.items():
        Device.display_info_msg(f"Set Trackable Devices > {devicename}")
```

I've seen other integrations with the same issue where they push out a quick fix and don't increment the release and for whatever reason HACS still delivers the old version. I guess it is doing some type of caching. Likely not the full zip, but maybe the URL to the zip? _(pure conjecture)_

**Comment by gcobb321** [comment]
Or it has grabbed some github release id and cached it, then it uses that instead of the new one. I think HACS goes through all it's items each night and updates that info. That is probably how it would know a new update is available. I'll push an update b19.1 tomorrow morning. It stores the HACS info in .storage/hacs_repositories. iC3 info is:

```
"394419578": {
      "repository_manifest": {
        "name": "iCloud3 v3 iDevice Tracker",
        "homeassistant": "2023.6.0b0",
        "render_readme": true
      },
      "full_name": "gcobb321/icloud3_v3",
      "authors": [
        "@gcobb321"
      ],
      "category": "integration",
      "description": "iCloud3 v3 is an advanced iDevice tracker that uses Apple iCloud account and HA Companion App data for presence detection and location based automations.",
      "domain": "icloud3",
      "etag_repository": "W/\"7b86458dbec76136ad4b8ea404d67e7f561c4225ca4e7f8eec3b47908eaaa5d5\"",
      "last_updated": "2023-07-08T22:14:32Z",
      "stargazers_count": 91,
      "topics": [
        "device-tracker",
        "ha-ios",
        "icloud",
        "icloud-account",
        "tracking",
        "waze",
        "zone",
        "zones"
      ],
      "installed_commit": "2b09e68",
      "installed": true,
      "last_commit": "5055478",
      "last_version": "v3.0.0b19.0",
      "manifest_name": "iCloud3 v3",
      "releases": true,
      "show_beta": true,
      "version_installed": "v3.0.0-beta-18c",
      "last_fetched": 1688923407.040015
    },
```
On GitHub, URL of the last commit with the description is :https://github.com/gcobb321/icloud3_v3/commit/b85e2a883813963aa022f0fa96c0fd549402b863, The `installed_commit` in the HACS json above is 2b863. So it is probably cached somewhere.

I've just added 2-new sensors: 
- `travel_time_hhmm` gives the travel_time to the zone as hh:mm and 
- `arrival_time` that shows the expected arrival time to the zone.
And cleaned up sensor creation for track_from_zones other than home.

**Comment by Snuffy2** [comment]
```
    "394419578": {
      "repository_manifest": {
        "name": "iCloud3 v3 iDevice Tracker",
        "homeassistant": "2023.6.0b0",
        "render_readme": true
      },
      "full_name": "gcobb321/icloud3_v3",
      "authors": [
        "@gcobb321"
      ],
      "category": "integration",
      "description": "iCloud3 v3 is an advanced iDevice tracker that uses Apple iCloud account and HA Companion App data for presence detection and location based automations.",
      "domain": "icloud3",
      "downloads": 3,
      "etag_repository": "W/\"f492a151814b585d533ad2bcf803e024c6656bd203128720638d53d1ce5fe2a1\"",
      "last_updated": "2023-07-08T22:14:32Z",
      "stargazers_count": 92,
      "topics": [
        "device-tracker",
        "ha-ios",
        "icloud",
        "icloud-account",
        "tracking",
        "waze",
        "zone",
        "zones"
      ],
      "installed_commit": "5055478",
      "installed": true,
      "last_commit": "5055478",
      "last_version": "v3.0.0b19.0",
      "manifest_name": "iCloud3 v3",
      "releases": true,
      "show_beta": true,
      "version_installed": "v3.0.0b19.0",
      "last_fetched": 1688953511.252105
    },
```

**Comment by gcobb321** [comment]
I wonder if it will change tomorrow with the id info for today. Beta 19.1 tomorrow to be sure. Here is the update.

[icloud3_v3-beta-19.1.zip](https://github.com/gcobb321/icloud3_v3/files/11996288/icloud3_v3-beta-19.1.zip)


Change Log:
1. Bug Fix - Fixed a problem that may be encountered if you have a watch paired to an iPhone and are tracking the iPhone but not the watch.
2. New Sensors:
    1. travel_time_hhmm - Displays the travel time to the zone in an hh:mm format.
    2. arrival_time - The expected arrival time to the zone (current time + travel time)
3. Simplified the sensors associated with track_from_zones other than Home.

**Comment by Snuffy2** [comment]
> Another subject, when I upload the release and run it through the hasfest Action, I keep getting an error code 1 and it fails. Looking at the log, it appears that it is missing an 'id' field and I have no idea where to start looking for a fix. Do you have any knowledge of what is going on?
> 
> Here is the Actions results:
> 
> ```
> Validating application_credentials... done in 0.00s
> Validating bluetooth... done in 0.00s
> Validating codeowners... done in 0.00s
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/src/homeassistant/script/hassfest/__main__.py", line 244, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/src/homeassistant/script/hassfest/__main__.py", line 166, in main
>     plugin.validate(integrations, config)
>   File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 108, in validate
>     _validate_integration(config, integration)
>   File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 73, in _validate_integration
>     _has_assignment(init, "CONFIG_SCHEMA")
>   File "/usr/src/homeassistant/script/hassfest/config_schema.py", line 23, in _has_assignment
>     if target.id == name:
>        ^^^^^^^^^
> AttributeError: 'Attribute' object has no attribute 'id'
> Validating config_schema...
> Error: Process completed with exit code 1.
> ```

I believe it is coming from this PR: https://github.com/home-assistant/core/pull/93587
It sounds like you need to import  PLATFORM_SCHEMA (or possibly CONFIG_SCHEMA) for each of your platforms and extend it to define your schema.

From `places`:
```
from homeassistant.components.sensor import PLATFORM_SCHEMA

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
    {
        vol.Required(CONF_DEVICETRACKER_ID): cv.string,
        vol.Optional(CONF_API_KEY): cv.string,
        vol.Optional(CONF_DISPLAY_OPTIONS, default=DEFAULT_DISPLAY_OPTIONS): cv.string,
        vol.Optional(CONF_HOME_ZONE, default=DEFAULT_HOME_ZONE): cv.string,
        vol.Optional(CONF_NAME): cv.string,
        vol.Optional(CONF_MAP_PROVIDER, default=DEFAULT_MAP_PROVIDER): cv.string,
        vol.Optional(CONF_MAP_ZOOM, default=DEFAULT_MAP_ZOOM): cv.positive_int,
        vol.Optional(CONF_LANGUAGE): cv.string,
        vol.Optional(CONF_EXTENDED_ATTR, default=DEFAULT_EXTENDED_ATTR): cv.boolean,
        vol.Optional(CONF_SHOW_TIME, default=DEFAULT_SHOW_TIME): cv.boolean,
    }
)
```

**Comment by Snuffy2** [comment]
Or looking at what they did in the linked PRs, you may just be able to add to \_\_init\_\_.py:
```
from homeassistant.helpers import config_validation as cv
CONFIG_SCHEMA = cv.empty_config_schema(DOMAIN)
```
Since v3 no longer supports YAML.

**Comment by gcobb321** [comment]
Thanks. I’ll give that a try tomorrow. What’s strange is it was passing everything when I made the changes to support HACS when I released beta 18 last month.

**Comment by gcobb321** [comment]
Adding `CONFIG_SCHEMA = cv.empty_config_schema(DOMAIN)` to __init__.py worked.

Thanks.
