### ISSUE TITLE
Reconfiguration is needed but verification code is not send

### ISSUE THREAD

**Issue by groenmarsmannetje** [gcobb321/icloud3_v3#167]
Since at least the last 3 beta versions I get a Reconfigure notification after restarting Home Assistant but I never get the verification code. Also when I use the option to request a new verification code I do not get it on my iPhone. The iCloud3 sensors seem to be able to track the devices anyway.

**Comment by gcobb321** [comment]
Let me make sure I understand.
- You get an HA notification that a code needs to be entered but do not get a notification on your phone. You click Notifications and it opens the window. You then click ‘check it out’ or what the text is and it opens Devices and Services and the Reauthentication notice is there in red. You click Reauth and the Enter /Request Code screen opens. You still do not have a code on your phone so you request one and still do not get one. 

But if instead, you go to the Configuration Settings and request one from the Enter/Request screen, you get a code and the authentication works. 

Ic3 looks at some at some items in the data returned form Apple to signal a Reauth is needed that then tells HA to display the Enter/Request screen. It does not know if a code was sent but it assumed it must have been.  When you request a code, the Apple cookies files are all deleted which tells Apple to send another code.

**Comment by groenmarsmannetje** [comment]
> * You get an HA notification that a code needs to be entered but do not get a notification on your phone. You click Notifications and it opens the window. You then click ‘check it out’ or what the text is and it opens Devices and Services and the Reauthentication notice is there in red. You click Reauth and the Enter /Request Code screen opens. You still do not have a code on your phone so you request one and still do not get one.

Correct 

> But if instead, you go to the Configuration Settings and request one from the Enter/Request screen, you get a code and the authentication works.

No I also do not get the code when I do this

**Comment by gcobb321** [comment]
Fixed it. It will be update in Beta 19.2 Thanks. I posted a preliminary b19.2 zip file on the icloud3_v3 repository file list if you need to download the fix.
