### ISSUE TITLE
Beta 19.2 - Pre-release

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#169]
@marceloaf @garyak @Snuffy2 @JtwoA @broyuken

Hey guys. I'm ready to try beta 19.2 with several changes. Two are real important to watch, the full Change List list is below.

The 2 items that I'd like you to watch carefully are:
- Item # 2 below deals again with how device_tracker state values are set
- Item # 3 deals with a couple of problems with the Stationary Zones that have been there since I redid it several beta ago.

Can you install it and make sure I didn't break anything, specifically the way the device_tracker state value is handled. Iff there is a problem, go into the Configuration Settings > Format Settings and change the Device Tracker State Value to the HA gps coordinates option.

Give it a day or two and let me know if it's OK or if I need to fix something. Then I'll release it

Thanks
Gary

[icloud3_v3-beta-19.2.zip](https://github.com/gcobb321/icloud3_v3/files/12139845/icloud3_v3-beta-19.2.zip)

### Change Log
beta 19.2 - 7/23/2023
...............................
1. Bug Fixes
    1. Fixed a problem displaying the iCloud3 Configure Settings screen on an iPad or iPhone from the iOS App.
    2. Fixed a problem requesting a new Apple Verification code from the Enter/Request Apple Verification code screen when it was selected from the HA Notifications > iCloud3 Reconfigure.
    3. Fixed a problem logging into the iCloud Account after getting an Invalid iCloud Account username/passwor error.

2. Device Tracker State Value Source parameter (New parameter) - The Device tracker state value is generated by HA based on the gps coordinates. When the device's location is updated, HA uses the lat/long to determine if that location is in one of it's zones. If it is in a zone, the state is set to 'home' if it is in the Home Zone or the zone's friendly name if it is in another zone. It is set to 'not_home' if it is not n a zone. This does not take the gps accuracy into consideration and gps wandering will take it out of the zone and set it to 'not_home'. iCloud3 overcomes this by creating it's own [devicename]_zone sensor (zone entity name) and [devicename]_zone_fname sensor (zone friendly name-the one HA uses and displays).

    This new parameter lets you select the state value to use - the iCloud3 zone name (actually the Zone Name Display name parameter value) or the HA zone based on the gps coordinates. This parameter is on the Format Settings screen and defaults to 'iCloud3'. Change it to use the HA option like it was before.

    Note: When iCloud3 is restarted and the device is in a Stationary Zone, the HA zone information is not updated on a timely basis so iCloud3 and the HA App on the devices still have the Stationary Zone information where HA may not. iCloud3 and the iOS App put the device in the Station Zone and HA sets it's state value to 'not_home'. This is not resolved until the next location is requested. To solve this, iCloud3 always sets the state value to the Stationary Zone friendly name when it is in a Stationary Zone.

3. Stationary Zone:
    1. Found that the Stationary Zone timer was being reset when an old location had been detected and the location update resulted in a good location. This delayed a device from moving into a Stationary Zone until it's still time interval was reached again 8-minutes from now. This would happen again if the location was old again the next time it was checked, further delaying a device from moving into a Stationary Zone. This has been fixed.
    2. Moving into a Stationary Zone will now happen much sooner after it's timer had expired. It now will be done as soon as it expires instead of the second or third update update after it had expired.
    3. Changed some of the text messages in the Event Log dealing with the Stationary Zone for consistency.
    4. Restart - When HA & iCloud3 restarts, the Stationary Zones do not exist yet. However, a device's Restore State data used during a restart will have Stationary Zone information (names, travel directioys, current status) in it's restore sensor values until the initial locate is done. The device's sensors would be set to a Station Zone incorrectly. This has been fixed.

4. Sensor tweaks:
    1. `_arrival_time` - Changed the icon to better show when the device was in the zone (house/map icon solid = arrived) or when you will arrive (house/map icon not solid = calculated arrival time).
    2. `_zone_distance` & `_home_distance` - Changed the icon to show if you are going towards Home, away from Home or at Home.
    3. `_battery` - Added the iOS App battery sensors entity names that are monitored to the sensor attributes.

5. Waze times and distances are now available when less than 2-minutes from home or a tracked-from zone.

---> A BROWSER REFRESH WILL BE REQUESTED <---

**Comment by broyuken** [comment]
I just updated, but I'm not seeing my wife who is away from home at the moment in a stationary zone even though she's set for 8 minutes.

**Comment by gcobb321** [comment]
@broyuken 
I've been using it since last Friday and have not had any problems. What does the Event Log show - Old location messages indicate the location is old and not useable like before. The fix was to NOT reset the timer but wait until the location was good. And then the statzone would be set. Before the timer was being reset so you had to get a good location to start the timer again, then wait until it expired, then check the location and if good, create the stat zone.

**Comment by broyuken** [comment]
I think it may be poor gps signal judging by the map and what I'm seeing in the logs.

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/f55377f7-b23d-43d1-8659-5afbb4cf3e12)
![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/106b434d-336a-46c9-a8f8-976e44b27ddc)
![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/3413394a-db31-4d06-bbed-215a3a6df2d4)
![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/df361dfd-db43-4a9d-ad29-ad4fc0d04567)

**Comment by broyuken** [comment]
It just crossed the time when the stat zone should have taken effect but now it pushed it out again. I don't quite see why that happened. It says moved 9m

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/6665f619-6d83-4a33-8d91-ab1de325044d)

**Comment by gcobb321** [comment]
It looks like b19.1. There should have been a Trigger Stationary Zone at 3:23:20. And if a location needed to be done, the Trigger at 3:23:25 would have added (Verify Stationary). Unless the Located msg at 3:23:30 was processed before it.

Scroll to the bottom of The EvLog  when iC3 started and verify the version, just to make sure.

**Comment by broyuken** [comment]
hrm, the version looks like 19.1. I just re-uploaded it to check and it still shows 19.1. Did you accidentally upload .1 into a zip named .2?

**Comment by gcobb321** [comment]
I just l downloaded the b19.2 zip file from Github that I had uploaded and it looks ok. 
I opened it, went to the 'support' directory and opened 'icloud_data_handler.py'.
Line 69 was `Device.icloud_update_reason += " (Verify Stationary)"`. Plus all the dates in the files that changed had a 7/23 date.
The version in `const.py` also showed v3.0.0b19.2`
so the zip file is OK.

**Comment by broyuken** [comment]
I didn't restart HA, I just restarted ic3. I did an ha restart and now it's loading 19.2. And now shes on her way home so she won't be in a stat zone.

**Comment by gcobb321** [comment]
Maybe tomorrow when she might go out again.  

When I’m testing from home, I edit the `config/.storage/core.config` file and change the location of the go one zone from -80.xxx to -81.xxx. Save and restart. But a real world experience is better. Especially since I’m on a high speed connection, not a slow cell tower inside a metal building. 

Thanks

**Comment by gcobb321** [comment]
@marceloaf @garyak @Snuffy2 @JtwoA @broyuken

Beta 20 to be updated tomorrow. This should be the final one.

I fixed a couple of bugs introduced in b19.2, plus the following:
6. Monitored Devices - The iOS App battery and location information was not displayed for monitored devices. This has been fixed.
7. Event Log - The iCloud3 and Event Log versions are displayed when you hover over Actions. Also made some other formatting changes. And some others related to first time installs.

---> A BROWSER REFRESH WILL BE REQUESTED <---

[icloud3_v3-beta-20.zip](https://github.com/gcobb321/icloud3_v3/files/12197808/icloud3_v3-beta-20.zip)

**Comment by Snuffy2** [comment]
It looks like you may have already taken down b20, but I had installed it prior to that and am seeing these errors on boot in the HA logs:

```
2023-07-29 12:49:57.479 ERROR (MainThread) [icloud3] 'zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'zone_display_as'
2023-07-29 12:49:57.713 ERROR (MainThread) [icloud3] 'last_zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'last_zone_display_as'
2023-07-29 12:49:57.869 ERROR (MainThread) [icloud3] 'zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'zone_display_as'
2023-07-29 12:49:58.039 ERROR (MainThread) [icloud3] 'last_zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'last_zone_display_as'
2023-07-29 12:49:58.256 ERROR (MainThread) [icloud3] 'zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'zone_display_as'
2023-07-29 12:49:58.477 ERROR (MainThread) [icloud3] 'last_zone_display_as'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/restore_state.py", line 192, in _reset_sensor_value
    if instr(sensors[sensor], statzone_value):
             ~~~~~~~^^^^^^^^
KeyError: 'last_zone_display_as'
```

**Comment by gcobb321** [comment]
@marceloaf @garyak @Snuffy2 @JtwoA @broyuken

**b20 was updated**

I fixed a problem where the old location counter was not getting reset to 0 when a good location was used.  Also fixed the restore state error that was resetting the stationary zone values back to away on a restart.

Here is the new b20.
[icloud3_v3-beta-20.zip](https://github.com/gcobb321/icloud3_v3/files/12207790/icloud3_v3-beta-20.zip)
