### ISSUE TITLE
Documentation Search not working

### ISSUE THREAD

**Issue by pauly7300** [gcobb321/icloud3_v3#170]
Gary, from what I can tell, it looks like you've shifted your documentation from the dedicated repo (https://github.com/gcobb321/icloud3_v3_docs) to this repo.  I noticed the search functionality is no longer working on the docs in this repo.  I assume it's something to do with docsify that you may need to change but I can't figure out where it might be.  Maybe just a path change somewhere assuming you just copied over everything from the other location.

https://gcobb321.github.io/icloud3_v3_docs/#/
<img width="452" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/11494052/febb1fa7-d4a5-4a3d-b7b1-ebdbeddea394">

https://gcobb321.github.io/icloud3_v3/#/
<img width="454" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/11494052/40a9e9b2-72db-4b6f-b150-b6d0d88e544c">

**Comment by gcobb321** [comment]
I removed the search. It was giving so many items that it became confusing and not really a benefit as the docs got bigger and bigger

**Comment by gcobb321** [comment]
Added index to documentation
