### ISSUE TITLE
new fault with beta 20 ;-)

### ISSUE THREAD

**Issue by criticallimit** [gcobb321/icloud3_v3#173]
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: icloud3
Source: custom_components/icloud3/helpers/entity_io.py:40 
Integration: iCloud3 v3: iDevice Tracker (documentation, issues) 
First occurred: 15:56:37 (40 occurrences) 
Last logged: 15:58:10

'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/helpers/entity_io.py", line 40, in get_state
    entity_state = entity_data.state
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by gcobb321** [comment]
Did the errors stop after iC3 started? There is a error logging message that does not need to be there.

**Comment by criticallimit** [comment]
Yepp. Error stopped and was not coming back after second restart of HA.

**Comment by criticallimit** [comment]
yes, seems to be. No more faults after several restarts now.

**Comment by criticallimit** [comment]
Checked again the logs:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: icloud3
Source: custom_components/icloud3/helpers/entity_io.py:40 
Integration: iCloud3 v3: iDevice Tracker (documentation, issues) 
First occurred: 11:25:47 (38 occurrences) 
Last logged: 11:27:15

'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/helpers/entity_io.py", line 40, in get_state
    entity_state = entity_data.state
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'
```

System was running over night and in the morning the fault was back after installing 2023.8.0b4

**Comment by gcobb321** [comment]
Same problem here with ha 2023.8.b04 & b05

Unzip this into the icloud3/helpers directory and restart ha

[entity_io.zip](https://github.com/gcobb321/icloud3_v3/files/12240661/entity_io.zip)

**Comment by broyuken** [comment]
I have the same fault, will upload this file tomorrow and see if it helps

This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/helpers/entity_io.py:40
Integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 9:53:50 AM (17114 occurrences)
Last logged: 9:46:55 PM

'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/helpers/entity_io.py", line 40, in get_state
    entity_state = entity_data.state
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by gcobb321** [comment]
HA guys made a breaking change in 2023.08. iCloud3 v3, Beta 20.1 fixes this.

**Comment by derekoharrow** [comment]
I'm still seeing this in v3.0.0b20.1.1.

**Comment by gcobb321** [comment]
Look at the Startup Stage 0 messages and verify b20.1 is running and not b20. 
Did you restart HA after installing?
What is the exact error message? It is still says line 40 restart HA again and check again.

The `entity_state = entity_data.state` statement in on:
line 40 - beta 19 and below
line 43 - beta 20
line 42 - beta 20.1

**Comment by derekoharrow** [comment]
> 

Interesting - it says it's starting v3.0b20, which is what's in const.py, but HACS says I'm on b20.1. Is HACS downloading an old version?

**Comment by marceloaf** [comment]
The same for me. HACS says is b20.1 but stage 0 reports b20


Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: derekoharrow ***@***.***>
Enviado: Friday, August 4, 2023 1:16:27 PM
Para: gcobb321/icloud3_v3 ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [gcobb321/icloud3_v3] new fault with beta 20 ;-) (Issue #173)


Interesting - it says it's starting v3.0b20, which is what's in const.py, but HACS says I'm on b20.1. Is HACS downloading an old version?

**Comment by derekoharrow** [comment]
Manually downloaded from the releases page instead of via HACS. Now running v3.0b20.1 and the errors have gone.

**Comment by gcobb321** [comment]
The original release of b20.1 has the b20 zip file (an OOPS moment on my part). I deleted the b20.1 and created the b20.1.1 release with the correct file. I have seen cases where HACS downloads the wrong file on a quick update. Try downloading again or get the zip file from the Release page

HACS is not even picking up the new release on my system.

**Comment by marceloaf** [comment]
The manual download worked! Tks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gcobb321** [comment]
If all works on my travels tonight, Release Candidate 1 (rc1) will be 
posted tomorrow.

Gary Cobb


------ Original Message ------
From "marceloaf" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Gary Cobb" ***@***.***>; "Comment" 
***@***.***>
Date 8/4/2023 1:35:34 PM
Subject Re: [gcobb321/icloud3_v3] new fault with beta 20 ;-) (Issue 
#173)
