### ISSUE TITLE
How to change intervals when out of zone 

### ISSUE THREAD

**Issue by Airey001** [gcobb321/icloud3_v3#174]
I found the way to change the in zone interval, is there no way to do this for out of zone.  I have found that when away i a seeing intervals that seem random to me like 3 minutes 15 minutes and. Even 30 - nothing consistent.  I uses zone to help track where my family is and alerts if we are somewhere we shouldnot be.

I am finding that the alerts aren’t firing cause the intervals are missing stops cause they can be too long.  

A good example is i alert if the phone shows up at a local fast food restaurant .  However alot of the time they or i can get though the drive though and be gone with no alert be cause the interval was so big it never recorded them there.

**Comment by gcobb321** [comment]
@Airey001
Are you using the iOS App? That it’s the app that generates the zone enter/exit triggers. Just relying on the phone itself to monitor the location on a fine scale will eat your battery. And even then, if you are in a location for a short period of time (the driver), the phone may not pick up the location and generate the trigger. 

But see the `action locate ###` service call to set the interval to the value you want.
