### ISSUE TITLE
Cannot access local variable 'duplicate_msg' where it is not associated with a value (RC1)

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#176]
Hi Gary, good afternoon. Noticed this error today. I upgraded earlier today to RC1.

This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/support/start_ic3.py:1797
Integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 16:15:36 (2 occurrences)
Last logged: 16:15:37

cannot access local variable 'duplicate_msg' where it is not associated with a value
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3_control.py", line 213, in stage_4_setup_data_sources
    start_ic3.setup_tracked_devices_for_iosapp()
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1797, in setup_tracked_devices_for_iosapp
    f"{CRLF_INDENT}{device_info_by_iosapp_devicename[iosapp_devicename]}{duplicate_msg}")
                                                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'duplicate_msg' where it is not associated with a value

**Comment by gcobb321** [comment]
Thanks. Already fixed. It from a routine that displays an error if you have duplicate iOS app devices. I thought I push an update today but want to get the HA service call support done first.

————————
Gary Cobb

**Comment by smarthomefamilyverrips** [comment]
> Thanks. Already fixed. It from a routine that displays an error if you have duplicate iOS app devices. I thought I push an update today but want to get the HA service call support done first. ———————— Gary Cobb
> […](#)
> On Aug 7, 2023 at 3:22 PM -0400, marceloaf ***@***.***>, wrote: Hi Gary, good afternoon. Noticed this error today. I upgraded earlier today to RC1. This error originated from a custom integration. Logger: icloud3 Source: custom_components/icloud3/support/start_ic3.py:1797 Integration: iCloud3 v3: iDevice Tracker (documentation, issues) First occurred: 16:15:36 (2 occurrences) Last logged: 16:15:37 cannot access local variable 'duplicate_msg' where it is not associated with a value Traceback (most recent call last): File "/config/custom_components/icloud3/support/start_ic3_control.py", line 213, in stage_4_setup_data_sources start_ic3.setup_tracked_devices_for_iosapp() File "/config/custom_components/icloud3/support/start_ic3.py", line 1797, in setup_tracked_devices_for_iosapp f"{CRLF_INDENT}{device_info_by_iosapp_devicename[iosapp_devicename]}{duplicate_msg}") ^^^^^^^^^^^^^ UnboundLocalError: cannot access local variable 'duplicate_msg' where it is not associated with a value — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

@gcobb321 I have the same issue.... I assume it not have any impact on the functionality of the integration?

**Comment by gcobb321** [comment]
This error occurs during startup up when it is displaying a message about the iosapp devices. It has no impact on anything. I will be checking one thing dealing with short interval location updates over the next few hours and probably post an update after I check it out. The update will include support for service calls using the Developer Tools > Services.
