### ISSUE TITLE
iCloud3 v3, Release Candidate 2 (8/8/2023)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#177]
@biggeeus @confusedsecuritydudes @chupacabra71 @chr04213 @criticallimit @daneboom @denac @derekoharrow @diothar @DerDon1302 @Exit2Studios @freshairr @gekberlin @garyak @freekode @FredWst @filikun @hvddrift @hellotomtom @ihf1 @JtwoA @HA_n00b @J-Fartz @joselito1 @japyjaap @kalkocz @kamkilt @kingy444 @lukkigi @marceloaf @MarkGardiner @marting @mobiledude @myMartek @morrisonpeter @Nuuki9 @pauly7300 @poudenes @polskikrol @rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3 @stevekuchta @townsmcp @tm24fan8 @t077584 @u20p17 @umrath 

### iCloud3 v3, Release Candidate 2 was just uploaded

Go to the Releases page [here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0-rc2)

**Comment by broyuken** [comment]
I’m having some issues with this release and old locations. My wife’s phone enters a zone, but ic3 delays it probably to make sure she’s not driving through it, and then it goes to old location. She used to have no issues when she got there, but now I am seeing a lot more old location errors in the logs and ic3 seems to be a lot less reliable to see where someone is than it used to be. Can this old location logic be tweaked to help fix some of these errors?

![image](https://github.com/gcobb321/icloud3_v3/assets/1593391/ebb8da31-b0d5-423c-b842-236b4b2d551e)

**Comment by broyuken** [comment]
I just enabled the gps accuracy sensor to see if her accuracy drops when she’s moving around.

**Comment by gcobb321** [comment]
In your screenshot:
- at 8:07:10, the location was 2.3 hours old ( `#12` ) so it had been old for a while. It got a new location but that was 4-mins ago and still old
- from 8:07:15 to 8:11:50, a location request was made and famshr kept returning the same old location
- at 8:11:50 ios requested an update and said the location was 8:08:33. The 8:08:33 location was from the iosapp. But the counter was not reset and the data was probably good.

It appears the loc data was really old and kept trying to get a new location but famshr kept giving the old one back. (Action > Show Tracking Monitors shows what is going on with the location updates.)

I've added another check to reset the old loc counter for the iosapp and famshr data when it is going to be used. This is a lot earlier in the tracking process and the old loc counter is used in a lot of places. The Threshold will also be displayed in the messages on the screen shot so you know what is being used to see if it is old.

This is rc3 which I am putting up tomorrow and probably to the base HACS>iCloud3(v2.4.7) as a prerelease Sat. if all goes well.

Unzip into the icloud3 directory.
[icloud3_v3-rc3.zip](https://github.com/gcobb321/icloud3_v3/files/12371621/icloud3_v3-rc3.zip)

**Comment by broyuken** [comment]
I'll try this new version, not sure why the location from 2 hours prior was still showing up. she was at home then and GPS has always been pretty accurate. Did Apple change something where if the location doesn't move it doesn't update the timestamp in icloud or something along those lines perhaps?

**Comment by gcobb321** [comment]
An updated rc3 that fixes a few things.
1, An error message when starting up about the area_id.
2. The Started from a platform: icloud3 statement when that does not exist.
3. Some things with the Event Log when posting the current running version.

[icloud3_v3-rc3.zip](https://github.com/gcobb321/icloud3_v3/files/12381527/icloud3_v3-rc3.zip)

**Comment by broyuken** [comment]
downloading now, quick questions unless this should go into a new topic. Is there a way to have wyze distances for 2 separate locations at the same time? I want to be able to track the travel time to say my home, my work and vacation house. I know you can set the vacation house as the new "home" for tracking when you get a certain distance away, but can you have multiples at once?

**Comment by riedlem** [comment]
Downloading this version and will check if it helps. I’m having the same problems with my wife’s FamShr reporting the old location. She’ll be located at home, and then suddenly I’ll see that her location is back to Away when she hasn’t moved anywhere. 

I also see an error in the Event Log for her phone that the iOSApp Location Requested > LastLocated 5:17:41p (18.5 hrs ago) > Failed to send message

**Comment by gcobb321** [comment]
@riedlem 
1. Select EvLog > Actions > Show Tracking Monitors to display the location times for the devices when a request is made for one of them. It shows who wanted the data, the location time of the data and if it changed. 
2. A Home _> Away -> back to Home usually indicates GPS wandering. Check the GPS accuracy of the data when that happens. 
3. The iosapp may be offline, asleep or not connected. You may have to force close it and then open it again. that will gnerate a Launch trigger.

**Comment by criticallimit** [comment]
RC3 is working since yesterday without any problem.

**Comment by gcobb321** [comment]
Will be releasing later this morning. Thanks for letting me know
