### ISSUE TITLE
@marceloaf  Migration v2.4.7 to v3 startup problems

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#18]
@marceloaf  Go ahead and send them. The items i fixed probably would not have anything to do with your issues.

Also lets open an new issue on your startup problems. I'm trying to keep this issue related to new releases, change logs and people using the beta release, not problems. Thanks

_Originally posted by @gcobb321 in https://github.com/gcobb321/icloud3_v3/issues/2#issuecomment-1366915403_

**Comment by gcobb321** [comment]
I have created this issue for you. I have the answers to the questions. Email the /config.icloud3-event-log_[datetime].log and /config/icloud3-debug.log files to [geekstergary@gmail.com](mailto:geekstergary@gmail.com). I can not get them or they do now show up on GitHub.

**Comment by gcobb321** [comment]
Have you tried b7 yet and had any success getting everything started correctly? If it still doesn’t work, I have added a parameter to the configuration file that delays the initial connection to the iCloud account until Stage 4 of the startup routine.

**Comment by JtwoA** [comment]
I didn’t realize B7 was a full beta version.  Is it something we should be using?


--
John Alan

01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110110 01100001 01101100 01110101 01100001 01100010 01101100 01100101 00100000 01100110 01100101 01100001 01110100 01110101 01110010 01100101 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01101100 01101100 01101001 01100111 01100101 01101110 01110100 00100000 01101100 01101001 01100110 01100101 00101110

**Comment by gcobb321** [comment]
The special b7 version was to test solving a problem logging into the icloud account that marceloaf was having that no one else had run into. I've added some other things to b7 and will be releasing it tomorrow.

**Comment by JtwoA** [comment]
That’s what I thought so I’d held off.  Looking forward to the full B7 release, thanks!On Jan 7, 2023, at 18:30, Gary Cobb ***@***.***> wrote:﻿
The special b7 version was to test solving a problem logging into the icloud account that marceloaf was having that no one else had run into. I've added some other things to b7 and will be releasing it tomorrow.

**Comment by gcobb321** [comment]
Everything fixed in beta 7 [here](https://github.com/gcobb321/icloud3_v3/issues/2). Hopefully. Let me know if you have any more issues.
