### ISSUE TITLE
iCloud3 v3, Release Candidate 3 Uploaded (8/19/2023)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#182]
@biggeeus @confusedsecuritydudes @chupacabra71 @chr04213 @criticallimit @daneboom @denac @derekoharrow @diothar @DerDon1302 @Exit2Studios @freshairr @gekberlin @garyak @freekode @FredWst @filikun @hvddrift @hellotomtom @ihf1 @JtwoA @HA_n00b @J-Fartz @joselito1 @japyjaap @kalkocz @kamkilt @kingy444 @lukkigi @marceloaf @MarkGardiner @marting @mobiledude @myMartek @morrisonpeter @Nuuki9 @pauly7300 @poudenes @polskikrol @rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3 @stevekuchta @townsmcp @tm24fan8 @t077584 @u20p17 @umrath 

### iCloud3 v3 ,~Release Candidate 3~ Prerelease 1,1 was just uploaded
I think this will probably be the final Release Candidate in the iCloud3_v3 repository. The next step will be creating a pre-release in the main iCloud3 repository that will get picked up by HACS. Both the iCloud3 and iCloud3_v3 repositories will be maintained for a while. Any issues identified and fixed will continue to be released in iCloud3_v3 before being promoted to iCloud3.

Gary

Go to the Releases page [here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0-pr1)

**Comment by edwinzelf** [comment]
Just upgraded. All still seems to work fine, except for configuration.
I get:
![image](https://github.com/gcobb321/icloud3_v3/assets/23138037/dc378a53-06df-4f65-8a7c-1207f927bc00)
Tried reloading the integration and also HA.
Am i missing something?

**Comment by townsmcp** [comment]
Same error for me to when going to configure IC3

**Comment by gcobb321** [comment]
Hmmm. Are there any errors in the home-assisstant.log or icloud3-0.log files? Email them to geekstergary@gmail.com and I'll look at them.

**Comment by townsmcp** [comment]
I enabled debugging and in the lo I get this after a reload:
![IMG_1557](https://github.com/gcobb321/icloud3_v3/assets/14061617/6e618c60-c8d4-4cae-a5e4-3d02fcf82a7b)

**Comment by gcobb321** [comment]
Does the 'Restart HA' option work OK?

All the reload is doing is issuing an HA 'reload_config_entry' service call with the iCloud3 id. It was an addition when trying to solve another problem that I fixed another way but decided to leave it in. HA thinks it is already loaded and giving an error message. I might just remove it if it doesn't work correctly.

**Comment by gcobb321** [comment]
Does this reload iCloud3:

1. Go to **HA Developer Tools > Services**
2. Select the **'Home Assistant Core Integration: Reload config entry**' service.
3. Select **Device**, then select '**iCloud3 (Personal Device)**'. Do not select _'iCloud3 iDevice Tracker_' or '_iCloud3 v3 iDevice Tracker_'. They belong to HACS
4. Select **Call Service**

Go to the iCloud3 page where you have the devices listed. It will show Unavailable for the items but they will fill in after iCloud3 has started. You may have to refresh the screen or go to another screen and then go back for the Frontend to do a refresh.

That is an alternate way of doing the reload. If that works for you, I'll do an update to the Configurator Settings and let you try that before doing an update.

**Comment by townsmcp** [comment]
Restarting HA then shows entries in the IC3 event log.

On the dev tools, I don’t have the option you mention:
![IMG_1558](https://github.com/gcobb321/icloud3_v3/assets/14061617/eef9bf3c-d589-4a5e-9208-d57258628320)

**Comment by gcobb321** [comment]
My screen
![image](https://github.com/gcobb321/icloud3_v3/assets/35449479/77e22ffd-8f1f-4b11-bc6b-5c31fbb442f0)

They both show No Area which makes me think the area is not set when iC3 started or you are not seeing the iCloud3 v3 device item.
Go to the **Devices & Services > Integrations > iCloud3 v3**
On the left, select **## devices** and the iCloud3 devices are displayed. What is in the Area column.

My devices:
![image](https://github.com/gcobb321/icloud3_v3/assets/35449479/04bd296f-db9b-4a90-bce6-bb1badc236fd)

**Comment by gcobb321** [comment]
The `config_flow.zip` file above has the alternate code to reload. Unzip it into the icloud3 directory, restart HA and try the Actions > Reload iCloud3 to see if it works that way.

**Comment by JtwoA** [comment]
> 

This worked for me.

**Comment by edwinzelf** [comment]
Did the trick for me.

I also tried re-installing RC3, after removing all config parts. Same issue. Replacing bothe patched files made everything working again. (y)

**Comment by broyuken** [comment]
Still having issues with zone enters from the iOS app not taking. 

![IMG_2793](https://github.com/gcobb321/icloud3_v3/assets/1593391/474e4f7e-1e8e-4748-90d9-e80e807a5cd1)

**Comment by gcobb321** [comment]
@broyuken 
I suspect the location data was from 2:44 based on the 17-min ago at 3:03 and confirmed on the 3:48 item. That would mean the test for the end of the 1-min zone delay was using the old location data at 3:03. 

Export the Event Log which shows the tracking monitors. Send the explore and the icloud3-0.log to geekstergary@gmail.com 

You can show the monitors to see the location updates using Event Log > Actions > Show Tracking Monitors. 


Do you have Log Level Debug? If not, turn it on in case this happens again. Do it from the Configurate Settings > Format Parameters so it won’t  go back to log level info at midnight.

**Comment by HaraldGithub** [comment]
I've tested the new feature. Restart HA with iCloud and iCloud alone is working, but
"RETURN > Return to the previous screen" dosen't work for me.
<img width="603" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/90566183/c8d47b28-bf27-4cb7-83e7-f6b348468d6e">
I got this error message:
<img width="603" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/90566183/0ba3c80c-c0c8-4cf2-960f-d89193af81d2">
So at the moment it's for me impossible to change other iCloud options.

**Comment by gcobb321** [comment]
@HaraldGithub  I’m aware of the problem. The Reload works after applying unzipping `patch.rc3.3-xxx`. I’ll check out the return but that should have been also fixed. That is a screen that is not used much. Click the X at the top right to close I it and then start over.

**Comment by HaraldGithub** [comment]
Thx, after installing patch*.zip every thing works fine again! :-)

**Comment by HaraldGithub** [comment]
Problem solved! Thx!

 

Von: Gary Cobb ***@***.***>
Antworten an: gcobb321/icloud3_v3 ***@***.***>
Datum: Sonntag, 20. August 2023 um 14:18
An: gcobb321/icloud3_v3 ***@***.***>
Cc: HaraldGithub ***@***.***>, Mention ***@***.***>
Betreff: Re: [gcobb321/icloud3_v3] iCloud3 v3, Release Candidate 3 Uploaded (8/19/2023) (Issue #182)

 

@HaraldGithub I’m aware of the problem. The Reload works after applying unzipping patch.rc3.3-xxx. I’ll check out the return but that should have been also fixed. That is a screen that is not used much. Click the X at the top right to close I it and then start over.

**Comment by broyuken** [comment]
I just had a chance to jump in and grab that file to upload, but I see it's taken down. Let me know when you have a new version up for me to take a look at and help test!

**Comment by gcobb321** [comment]
I've run around a bit and have uploaded in Release rc3a or pr1. [here](https://github.com/gcobb321/icloud3_v3/releases)

**Comment by gcobb321** [comment]
I have fixed a few issues and posted a new patch (patch.pr1.3-08.23+event-log.zip) on the GitHub releases page (here)[https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0-pr1.1]

Download and unzip into the icloud3 directory. A browser refresh will be requested.

Note: patch.pr1.3-08.23-xxx includes the previous patch.pr1.2-08.21-xxx)

Change Log:
1. Battery - Fixed a problem where the battery level/status was not being updated immediately in the Event Log when it went from 'charging' to 'not charging' or 'not charging' to 'charging'.
2. GPS - The 'Show GPS Coordinates' parameter is now applied when the event is displayed in the Event Log instead of when it is added to the Event Log. You can disable this parameter so they are not normally displayed. Later, if you need to review where a device has been, reenable the parameter and the location coordinates for previous events will be displayed.
3. Event Log - Fixed a problem where the event time was not displayed if the 'Zone Display-as' parameter was set to display the zone entity_id.
4. Event Log - Fixed a problem with the Event Log Card not detecting a version update.

**Comment by HaraldGithub** [comment]
Hi Gary,

 

thank you for this informations.

 

I’ve some problems with the patch.

I’ve installed this version: Prerelease Version - v3.0-pr1a (8/20/2023)

After that, I’ve installed this patch: patch_pr1.3-08.23+event-log.zip

and restart HA.

I’ve got message of invalid configuration of iCloud3.

 

Have I to copy all files from the patch or only the both text-files?

 

To repair the above mentioned problem, I’ve reload iCloud3 in HACS and restart HA again.

At the moment iCloud runs without any patch.

 

Best regards

 

Harald

 

 

Von: Gary Cobb ***@***.***>
Antworten an: gcobb321/icloud3_v3 ***@***.***>
Datum: Mittwoch, 23. August 2023 um 18:46
An: gcobb321/icloud3_v3 ***@***.***>
Cc: HaraldGithub ***@***.***>, Mention ***@***.***>
Betreff: Re: [gcobb321/icloud3_v3] iCloud3 v3, Release Candidate 3 Uploaded (8/19/2023) (Issue #182)

 

I have fixed a few issues and posted a new patch (patch.pr1.3-08.23+event-log.zip) on the GitHub releases page (here)[https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0-pr1.1]

Download and unzip into the icloud3 directory. A browser refresh will be requested.

Note: patch.pr1.3-08.23-xxx includes the previous patch.pr1.2-08.21-xxx)

Change Log:
Battery - Fixed a problem where the battery level/status was not being updated immediately in the Event Log when it went from 'charging' to 'not charging' or 'not charging' to 'charging'.
GPS - The 'Show GPS Coordinates' parameter is now applied when the event is displayed in the Event Log instead of when it is added to the Event Log. You can disable this parameter so they are not normally displayed. Later, if you need to review where a device has been, reenable the parameter and the location coordinates for previous events will be displayed.
Event Log - Fixed a problem where the event time was not displayed if the 'Zone Display-as' parameter was set to display the zone entity_id.
Event Log - Fixed a problem with the Event Log Card not detecting a version update.

**Comment by gcobb321** [comment]
You should unzip the patch zip file into the icloud3 directory.
