### ISSUE TITLE
StatZon1 - How to remove?

### ISSUE THREAD

**Issue by jurekjure** [gcobb321/icloud3_v3#185]
Hey, I just started using HA and iCloud3 (v3).

I turned the creation of stationary zones off, but before I did this iCloud3 already created StatZon1.
I cannot figure out where I can remove it completely. I for example figured out how to rename it (through Developer Tools/States), but I can not figure out how to delete it.
There is nothing related to zones in my configuration.yaml (opened with Studio Code Server). Also this configuration.yaml seems pretty small - only 23 lines. Is this OK or do I see only a part of this .yaml?

Thank you!

**Comment by rayzorben** [comment]
@gcobb321 I like this feature, it would be cool instead of just naming it StatZon1 or whatever value put in there by the user, if it could geolocate a City/State or a general area so that tiles that show the zone make sense.

**Comment by gcobb321** [comment]
When the device goes into a StatZone, the gps coordinates are in the device tracker entity. The iOS app has a geocode Location sensor with the place description. Also check out the ‘Places’ custom component on HACS (by snuffy2) that also has the place name for a device.
