### ISSUE TITLE
StatZone Movement Total

### ISSUE THREAD

**Issue by scotty1395** [gcobb321/icloud3_v3#190]
I'm finding it quite difficult getting devices to register as stationary.
Every update during the stationary timer adds distance moved to the StatZone Movement Total. If I'm walking 35m backwards and forwards with each update, at the end of the stationary timer I'm not 140m from the point when the stationary timer started, I'm 35m or less.

Should IC3 be comparing the coordinates at the start and end of the stationary timer and the distance between them, rather than accumulating distance moved with each update during the stationary timer?

Alternatively, is there a way to modify the DistMoveLimit to a greater distance than 125m? I can't find a setting for it.

**Comment by scotty1395** [comment]
Hi Gary. I've emailed you an export of the event log.

**Comment by gcobb321** [comment]
I have found the problem. The distance moved from the last location is being added to a total distance moved each time the interval time expires. When close to home and with a 15-secs interval expire time, the total moves gets greater than the still time very fast. This code changes how this is done to keeping the gps lat/long when the StatZone timer is set and always checking the distance from that point instead on using the distance moved. 

Edit the _icloud3/device.py_ file.

Line 177, add the _self.statzone_latitude_ and _self.statzone_longitude_ statements below so the code block is:

```
        # StatZone fields
        self.statzone_latitude       = 0.0
        self.statzone_longitude    = 0.0
        self.statzone_timer           = 0
        self.statzone_dist_moved_km  = 0
        self.statzone_setup_secs     = 0     # Time the statzone was set up
```

```
@property
    def statzone_reset_timer(self):
        '''
        Set the Stationary Zone timer expiration time
        '''
        self.statzone_dist_moved_km = 0
        self.statzone_timer     = Gb.this_update_secs + Gb.statzone_still_time_secs
        self.statzone_latitude  = self.loc_data_latitude
        self.statzone_longitude = self.loc_data_longitude
```
