### ISSUE TITLE
Getting Error with no iOS app installed on iphone.

### ISSUE THREAD

**Issue by firestrife23** [gcobb321/icloud3_v3#193]
This certain individual do not want to install Home Assistant app on iPhone, I selected None for IOS APP DEVICE_TRACKER ENTITY, however it threw me an error. See below

[![SCR-20230902-rmyj.png](https://i.postimg.cc/2yhTw81S/SCR-20230902-rmyj.png)](https://postimg.cc/fSWxWs7G)

**Comment by gcobb321** [comment]
Did this happen one time or every time you start HA and iCloud3?
Did iCloud3 start after the error and is your phone being tracked?
Putting None in the iosapp parameter just updates the configuration file. 
Does this message go away if you restart HA?

**Comment by firestrife23** [comment]
1. Yes
2. 3 iPhones being tracked just fine, except for one without iOS app
3. Yep
4. It didn't go away
5. Yes during the migration, I even tried nuking the iCloud3 data with fresh setup

**Comment by gcobb321** [comment]
Edit the 2 files below and add the following code:


`Gb.hass = hass`


icloud3/device_tracker.py — line 65
Icloud3/sensor.py —- line 75

restart HA

**Comment by gcobb321** [comment]
Great. That change will be in the next prerelease (pr1.4) later this month when I get home from a trip.
