### ISSUE TITLE
Regarding how to replace Waze with Amap in China.

### ISSUE THREAD

**Issue by jhchenchong** [gcobb321/icloud3_v3#196]
Waze is not available in my region, so I replaced the distance calculation method with Amap. Now, the issue I'm facing is that Amap requires two additional parameters besides location information: api_key and mode, which are the platform authorization key and traffic mode, respectively. I want to configure api_key and mode separately for each device_tracker. Is it possible to do this in config_flow?

Looking forward to your reply. Thanks!

**Comment by gcobb321** [comment]
That is not supported

**Comment by jhchenchong** [comment]
Thanks for your reply.
