### ISSUE TITLE
Km and Miles incorrect, and Batterystate

### ISSUE THREAD

**Issue by maiki97** [gcobb321/icloud3_v3#199]
Hey Garry, why is my ad suddenly not working? I got km displayed during setup and now only miles. In addition, the battery level does not fit, it seems to me as if he only updates at very high intervals... how can I change that? 
Under settings would actually km set

**Comment by gcobb321** [comment]
Are you getting any errors in the HA logs related to iCloud3?
Go into the Configure Settings > Page 2 > Format Parameters screen and verify the settings. 
Go into the Configure Settings > Update Devices screen for the devices and verify the famshr device is selected for the phone ups are tracking. The phones model number is displayed to make sure you have selected the correct one. 

Restart HA and review the Event Log To make sure there are no error or warning messages.

**Comment by maiki97** [comment]
Good morning,
I have added a picture in the attachment. But unfortunately I have no idea what familyshar is and how to change it. I can also select only "none" or Iphone but then I get red error messages
![image](https://github.com/gcobb321/icloud3_v3/assets/59704782/db079515-b593-4602-914f-f2ce3ce58bf9)

**Comment by gcobb321** [comment]
They Family Share list shows the members/devices in your iCloud account. When iCloud3, it logs into your iCloud account to get the devices. That message means it didn’t get any devices or the ‘iPhone Bo irgendoam’ it’s not in the list. 

Go to the  Configure Settings > Data Sources - iCloud and iosapp’ screen and verify your iCloud account I’d and password and make sure you can log into your account. 

Items are displayed in the Event Log about the iCloud account when iCloud3 starts. See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/1.4-evlog-during-startup?id=stage-4-setup-icloud-amp-ios-app-tracking-methods) for the messages
