### ISSUE TITLE
HACS: Only v3.0-pr1.3

### ISSUE THREAD

**Issue by GerdRuetten** [gcobb321/icloud3_v3#203]
Dear @gcobb321 

I'm to stupid to update from pr1.3 to pr1.4

In the selectbox in HACS I see only this as highest version

![image](https://github.com/gcobb321/icloud3_v3/assets/97361636/e1983afa-8c68-49e3-adac-2af9b00b6261)

What do I wrong?

TIA

Best regards

Gerd

**Comment by gcobb321** [comment]
If you see 3-dots in the upper right corner, Click it, select Update Information. That should display the pr1.4 version. Then install it. Sometimes it takes HACS some time to refresh the new versions

**Comment by ahamro** [comment]
I tried yesterday evening and today and the pr1.4 version does not show up yet. Maybe something is wrong...

**Comment by JtwoA** [comment]
It doesn't show for me, yet, either - HACS hasn't updated yet.  That's on HACS, not @gcobb321 .  Show some patience, please.

**Comment by ahamro** [comment]
@JtwoA and @gcobb321: I'm not in a hurry, I just thought there might be something wrong. Or is it normal for HACS to take over 24 hours to update?

**Comment by JtwoA** [comment]
> @JtwoA and @gcobb321: I'm not in a hurry, I just thought there might be something wrong. Or is it normal for HACS to take over 24 hours to update?

I can't answer this for two reasons:  I've never deployed anything thru HACS and I don't watch that closely.

**Comment by GerdRuetten** [comment]
OK, just in time HACS present the v3.0-pr1.4 and i could update!

Closed!
