### ISSUE TITLE
iCloud3_Device object has no attribute 'interval_secs' Prerelease 1.4

### ISSUE THREAD

**Issue by everdrift** [gcobb321/icloud3_v3#205]
After updating to Prerelease 1.4 the followig error pops up:

Logger: icloud3
Source: custom_components/icloud3/support/determine_interval.py:680
Integration: iCloud3 v3 (documentation, issues)
First occurred: 15:32:00 (54 occurrences)
Last logged: 15:36:20

'iCloud3_Device' object has no attribute 'interval_secs'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/determine_interval.py", line 680, in determine_interval_after_error
    threshold_msg = ''  if interval_secs == Device.interval_secs \
                                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'iCloud3_Device' object has no attribute 'interval_secs'

**Comment by gcobb321** [comment]
Fixed. Will be in pr1.5
