### ISSUE TITLE
Cannot edit devices if more than 5.

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#21]
In my family group we have 7 devices, some FamShr, some FMF, etc.

In the configurator, selecting icloud3 devices calls up the list of devices to edit, but you can only see the first 5 - you cannot access or edit any after that.

I've had to manually edit the configuration file to make changes to latter devices.

**Comment by JtwoA** [comment]
There’s a menu entry to move to the next page of devices.On Jan 1, 2023, at 16:02, derekoharrow ***@***.***> wrote:﻿
In my family group we have 7 devices, some FamShr, some FMF, etc.
In the configurator, selecting icloud3 devices calls up the list of devices to edit, but you can only see the first 5 - you cannot access or edit any after that.
I've had to manually edit the configuration file to make changes to latter devices.

**Comment by gcobb321** [comment]
When there are 5 or less devices, you are presented with option buttons to *update, add, delete, reinitialize fields, and return*. When there are more than 5 devices *next* is added. HA changes the option buttons to a dropdown list when there are more than 6 items in the list. I added the *reinitialize* selection but never tested it for more than 5 devices. 

At the moment, select the next action from the dropdown list and select *next*. I'll look at it to see how to force a option list so it displays correctly. The *next* option switches betweeh devices 1-5 and 6-10.

**Comment by derekoharrow** [comment]
Doh! Thanks

**Comment by gcobb321** [comment]
I just uploaded a preliminary beta 7 which will fix your issue of more than 5 devices. The menu now displays correctly.
