### ISSUE TITLE
Unkown Error Occured while adding 1st device to iCloud V3

### ISSUE THREAD

**Issue by UginePudowski** [gcobb321/icloud3_v3#210]
Hello, 

To start with an FYI, i am very new and green to HA so if i make a blunder with terminology please bare with me. Also i am struggling to find log files in file editor.

I have been trying many ways to set up device tracking, i tried iCloud V3 then removed it had it working then wanted to try something else and removed it. Now i have redownloaded it i am struggling to add the device. I am using pre-release version 1.4.

Any support you can give will be greatly appreciated.

Thanks

Callum

**Comment by gcobb321** [comment]
HACS has not been downloading pr1.4 correctly and you are probably running pr1.3. Check the first line of the _Event Log_ when iCloud3 starts to see what you are running. 

See [here](https://github.com/gcobb321/icloud3_v3/issues/207#issuecomment-1737012322) for more info and what to do.
