### ISSUE TITLE
Tracking has been paused.

### ISSUE THREAD

**Issue by JtwoA** [gcobb321/icloud3_v3#212]
I've been seeing this a lot of late, @gcobb321.  

What exactly does this mean?  A couple of times this prevented my home from seeing my departure and never locked it down.

![339C55D7-1979-4500-8121-85C8610E2DA9_1_201_a](https://github.com/gcobb321/icloud3_v3/assets/12992040/37ab76d1-7c40-4073-b62f-a02707ea8320)

**Comment by gcobb321** [comment]
It means the location data received from iCloud or the iOS app is old and can not be trusted. iCloud3 keeps asking for an updated location and is not getting one. I see this when I go to a doctors office and my phone loses the gps signal, when I’m on a plane in airplane mode or in a poor cell area for a long time. The _Event Log_ will show how old the location data is after each request.

**Comment by JtwoA** [comment]
I'm seeing this at home. It's never done this before. I work from home, my office location hasn't changed. Has this always been included?

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
