### ISSUE TITLE
On iphone se 2020 No Location Data

### ISSUE THREAD

**Issue by antoweb** [gcobb321/icloud3_v3#213]
Hello,
after installing icloud3 v3 on HA and authentication successfull all sensor are corrected valued.

From this morning the addon cannot update the sensors and in log i see: "No Location Data"

Any suggestion?

**Comment by gcobb321** [comment]
Try _Event Log_ Request Location famshr and see if the location updates. 
Make sure there it’s a good internet connection. 
 Restart iCloud3 and review the _Event Log_ startup Stage 4 &5 to make sure there are no duplicate devices and the device model numbers are correct. Also make sure the initial locate is returning good data. 
Have you updated your phones?  If so, you are probably requesting location of the old one, not the new one. _Configure Settings > Update Devices_ screen and review the FamShr device selection.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
