### ISSUE TITLE
Can't re-deploy iCloud3 v3

### ISSUE THREAD

**Issue by Nuuki9** [gcobb321/icloud3_v3#216]
Been using iCloud3 v3 for a good few months. Over the weekend I re-deployed my docker environment, and I'm now having issues.

To resolve this, I removed the custom integration in HACs and rebooted. I then re-added it (the new rc7), but the Integrations list doesn't seem to have the correct one - its showing the "_iCloud Device Tracker_", rather than "_iCloud3 v3_".

In the logs I do see the following error:

```
2023-10-14 13:15:21.808 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration icloud3: No setup or config entry setup function defined.
```

I don't have any reference to iCloud in my configuration.yaml, and I don't have any icloud config files in my root config folder.

Am I missing something obvious?

**Comment by Nuuki9** [comment]
Here's the custom integation showing up in my list:

<img width="277" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/30313491/d2cec054-b624-46cd-acd8-6d56fd008c12">

Here's what I get in the Integrations list:

<img width="287" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/30313491/c366e8aa-93c7-4ff2-ae97-d3de7aacdc96">

**Comment by gcobb321** [comment]
Did you select the iC2 v3, Dev Version, install via HACS and restart HA. Then go to Integrations and  Select _iCloud3 Device Tracker_

**Comment by gcobb321** [comment]
iCloud3 is in the `/custom_components/icloud3` directory. Your note above refreenced the `icloud` directory.

**Comment by Nuuki9** [comment]
My bad - I was referring to it generically. The integration is installed in `/config/custom_components/icloud3`.

**Comment by gcobb321** [comment]
I would delete all the files in the icloud3 directory to make sure you do not have a mix of v2 and v3 files. 
Then restart HA. 
Then restart it again (yes restart it again). 
Then readd the v3 files via HACS or unzipping the release zip files into the icloud3 directory.
Then readd it as an integration
Then restart HA

**Comment by Nuuki9** [comment]
That seems to have done the trick. Thanks!
