### ISSUE TITLE
Updating password does not update the configuration file

### ISSUE THREAD

**Issue by N3rdix** [gcobb321/icloud3_v3#217]
I recently changed my Apple ID password and entered it in the config flow to update icloud3 as well. 
![image](https://github.com/gcobb321/icloud3_v3/assets/70015952/033de7c0-21a3-4fbe-a001-2e2b422094d5)

After confirming the 6-digit code icloud3 starts working again for a certain time, then I get error messages in the log which indicate that is still uses the old password:
`Username/Password error logging into the iCloud Account`

**I observed that the encrypted password in the file .storage/icloud3/configuration is still the old password and does not get updated!**

```
"data": {
        "tracking": {
            "username": "abc@def.gh",
            "password": "««XYZ»»",
```

When I enter the config flow again after I saved the new password it shows again the old password.

I assume deleting/creating the integration would resolve the issue but I want to avoid that as this feels like a bug.

**Comment by gcobb321** [comment]
It probably a bug and I’ll check it out. Deleting and readding the Integration does not change the configuration file. 

Try this first to see if it’s just not saving the new password after you change it. 
Go to the _Configure Settings > iCloud Account & iOS App Data Sources_ screen.
Enter the password and select **Save**
Change the iOS App check box and select **Save **. 
Then change it back to what you had and **Save** again. 
Exit _Configure Settings > _ then go back in and see if the password is now correct. 

If that did not work, Edit the configuration file to reset the password to an empty field, save the change and restart iCloud3. 

```
data": {
        "tracking": {
            "username": "abc@def.gh",
            "password": "",

```
Go back into the _Configure Settings > ICloud and iOS App_  screen and enter it and save it again.

**Comment by N3rdix** [comment]
That worked partially, when performing step 1-5 it displayed the correct password as long as I stayed in the config flow. When I start the config flow again by clicking on configure" it again display the old password. Oddly the password was stored in the configuration correctly but the config flow was still showing the old password.

Editing the configuration file to the unencrypted password and restarting HA at least keeps config flow and config file in sync (both show the correct password), but it's not encrypted after a HA restart.

**Comment by gcobb321** [comment]
I just tried a number of changes to mine and could not get it to fail like you saw. 
1. Putting it in plain text encrypted after an HA restart. 
2. Changing the encoded pw caused it to fail on a  restart about 30-minutes later when the secure token expired. Correcting it in the _Configure Settings > iCloud Account & iOS App Data Sources_ screen logged into Apple, request a code and updated the configuration file. Everything was ok after a restart. 
3. Resetting it in the file and then entering also worked. 

The configuration file has an `"encode_password": true,` statement after the password parameter. It defaults to true. Is your true or false?

**Comment by gcobb321** [comment]
I just uploaded v3.0.rc7.1 to check the password on startup and a few other things. See the announcement [here](https://github.com/gcobb321/icloud3_v3/issues/218) for more information
