### ISSUE TITLE
v3.0.rc7  iOSApp Location Requested >   Failed to send message

### ISSUE THREAD

**Issue by jhchenchong** [gcobb321/icloud3_v3#220]
<img width="502" alt="截屏2023-10-19 09 45 59" src="https://github.com/gcobb321/icloud3_v3/assets/19201316/378e5498-ba9a-43a9-a50c-7570060b9006">

**Comment by gcobb321** [comment]
That means HA notify service could not send the message requesting the location. Maybe it was offline, in a poor cell area or in standby mode. It finally did at 6:25.
