### ISSUE TITLE
iCloud3 v3.0.rc8 - location information degrading

### ISSUE THREAD

**Issue by umrath** [gcobb321/icloud3_v3#226]
For a couple of days I see the phenomenon that the location information is degrading (not sure about other data) and my phone is located in a position that I haven't been at for quite some time. It looks like this is some fallback or the like.
This is correctable by reloading the integration but will degrade again after some time (patter unclear).
Interestingly, it is always the same location and according to Home Assistant the data is recent (couple of minutes old only).

Correction:
After reloading the integration (and the subsequent correction of the location), the wrong location popped back up just after minutes.

It could be related to the parallel use of the mobile app.

**Comment by gcobb321** [comment]
Did you get a new phone? It could still be tracking the old one instead of your new one if you didn’t go back into the _Configure Settings > Update Devices_ screen and review the famshr phone that is assigned.

**Comment by umrath** [comment]
No new phone.

I did reconfigure it now. (hopefully right)
Let's see if that changes anything.

**Comment by sdwhwk** [comment]
I just installed this today and it’s not updating location either. Last time it said it updated was 2 hours ago and while it showed me at home, I’ve been across town. Reloading the integration refreshed it, but it only works for a while before it gets gummed up again. Refreshed it 4 times already in 5 hours.

**Comment by gcobb321** [comment]
Does the _Event Log_ show any errors, old location retries, poor gps, etc. The interval will increase increase as the old location error counter increases. 

Turn on log level Debug on _Event Log > Actions > xx_  and restart iCloud3 on _Event Log > Actions > Restart iCloud3_   When things stop working, email the iCloud-0.log file to geekstergary@gmail.com.  I’ll take a look at it and see if I see anything.

**Comment by sdwhwk** [comment]
I think I figured it out. Went back in main device setup for the devices and the zone intervals were set to default 120min (so 2 hours). Must have missed that because the last device I set up had 15min (which is what I wanted.) changed it to 15 and it updated more frequently. So it was an oversight issue.

**Comment by gcobb321** [comment]
Glad you figured it out. I’ll let you close this issue if everything go as expected.

**Comment by umrath** [comment]
This issue was opened by me. So, I guess it's my job to close it then.

In fact, the solution was a little different for me. As you suggested, I reconfigured the device which caused the problem - and that helped.
I still think that this process should be in some way happening automatically, because it's hard to figure this out on your own without the help we have gotten here.

**Comment by gcobb321** [comment]
Good suggestion but I’m not sure how to automate it. Perhaps setting the default to a smaller value. Are you using the iOS app on that device?

**Comment by umrath** [comment]
Not sure, if the value change would help any. The wrong location was persistent for 2 weeks or so.

Yes, I do use the iOS app on the device. It's also configured that way in the integration.

**Comment by gcobb321** [comment]
When you leave a zone, the iOS app should be issuing an exit Zone trigger that iCloud3 picks up. Do you see any of those triggers in the _Event Log_ ? iCloud3 picks it up, takes you out of the zone and changes the time from the 2-hours inzone time to a travel time/ distance based one.
