### ISSUE TITLE
Unknown Error occurs when trying to move to Next Page items in Configuration

### ISSUE THREAD

**Issue by ctrobbins** [gcobb321/icloud3_v3#228]
When in the Configuration screens and in the "iCloud3 Devices" section, I have more than 5 devices to update. When I select the "Next Page Items" and hit Submit I receive an "Unknown error occurred". I'm using v3.rc6.

As a workaround I'm able to reorder the devices using "Change Device Order" so that the devices I wish to update show up within the first 5 items where I can then select it for updating that device's configuration.

**Comment by gcobb321** [comment]
That has been fixed. Update to rc8. I’m trying to get as many people as possible to go to rc8 for a final check before rolling it out in mid-November and would appreciate it if you would install it even though you found a work around.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
