### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by 22Black22** [gcobb321/icloud3_v3#229]
This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/support/pyicloud_ic3.py:1437
Integration: iCloud3 v3: iDevice Tracker (documentation, issues)
First occurred: 6:36:26 PM (58 occurrences)
Last logged: 6:45:01 PM

unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 1437, in update_device_location_data
    rawdata_battery_level = round(_RawData.device_data.get(ICLOUD_BATTERY_LEVEL, 0) * 100)
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
