### ISSUE TITLE
Correction for the Installation Guide

### ISSUE THREAD

**Issue by yvansandoz** [gcobb321/icloud3_v3#230]
In the "Installing and Configuring iCloud3" guide, under Step 5.4, paragraph 3, the text should be:

3. Enter the following:
- /local/icloud3/icloud3-event-log-card.js in the URL field
- Check JavaScript Module

The actual text does not specify the ".js" at the end of the URL.

**Comment by N3rdix** [comment]
Submitted. This basically can be done by every user, not much more work than creating an issue. But thanks for putting the effort into the report

**Comment by gcobb321** [comment]
Merged. Thanks
