### ISSUE TITLE
iCloud3 changes FAMILY SHARING LIST DEVICE back to older devices

### ISSUE THREAD

**Issue by MrIcemanLE** [gcobb321/icloud3_v3#233]
I noticed that icloud3 changes the device listed under the option `FAMILY SHARING LIST DEVICE` back to older devices that are still in this List. (e.g. from the current iphone 13.1 back to the iphone 8)
I have to change it back to the correct device almost every day.

Question 1) Can this issue be fixed?

Question 2) How to get rid of the older devices in this List? Maybe you can add an ignore list?

**Comment by JtwoA** [comment]
> I noticed that icloud3 changes the device listed under the option `FAMILY SHARING LIST DEVICE` back to older devices that are still in this List. (e.g. from the current iphone 13.1 back to the iphone 8) I have to change it back to the correct device almost every day.
> 
> Question 1) Can this issue be fixed?
> 
> Question 2) How to get rid of the older devices in this List? Maybe you can add an ignore list?

Wouldn't removing the old device from the icloud account rectify this, @gcobb321 ?  If the iPhone 8 is no longer in use then why is it still attached to the account?

**Comment by MrIcemanLE** [comment]
I'll try to capture the event when the integration changes the device. This might take a few hours/days.

The curious thing is, that the older devices are off. So they can't report a newer location to apple. 

>  I’m thinking about keeping the one that was configured and giving a duplicate message in the Event Log

That sounds great ...

**Comment by gcobb321** [comment]
The devices are off but if they are still in your iCloud account, they would still have a location time that may be days or weeks ago.

**Comment by MrIcemanLE** [comment]
> If there are several devices in your Family Sharing list with the same name, iCloud3 tries to pick the newest one and use it

My comment was due to your comment of the latest location. And I think I already removed the device from my wife's account. But I'll double check this.

**Comment by MrIcemanLE** [comment]
BTW: Found the reason why devices are listed even though they are not listed in Apple Account. The list of devices in the "Find My" application is not synchronized with the account. So after removing the device, it still lives in the Find My app. Since I deleted it from my wife's app. The problem is gone. But maybe you can still take a look at the issue in case someone else has the same problem.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
