### ISSUE TITLE
Apple ID Sign In Requests go to all iPhones in family?

### ISSUE THREAD

**Issue by ahamro** [gcobb321/icloud3_v3#236]
When there is an Apple ID Sign In Request on my iPhone and iPad, which I presume has originated from my iCloud3 integration, my wife's iPhone and iPad get the request too.

Is that 'normal' procedure and can I prevent it?

Please excuse me if this is a well known question: I couldn't find it in Github.

**Comment by ahamro** [comment]
But I don't mean e-mails, but the requests. They go the all our iPhones and iPads.

**Comment by ahamro** [comment]
Your description exactly fits my experiences until yesterday. Since then I'm getting these requests several times per hour, so it's starting to annoy a bit.

**Comment by JtwoA** [comment]
> When there is an Apple ID Sign In Request on my iPhone and iPad, which I presume has originated from my iCloud3 integration, my wife's iPhone and iPad get the request too.
> 
> Is that 'normal' procedure and can I prevent it?
> 
> Please excuse me if this is a well known question: I couldn't find it in Github.

You are asking about Apple functionality, not iCloud3 functionality.  It would seem from how you described the issue that you've configured all of your devices to be Trusted Devices and, subsequently, they will all receive the notification.

https://support.apple.com/en-us/HT205064

If you keep getting it repeatedly then Apple is not receiving the code properly.  It could be something as simple as someone with one of the Trusted Devices is responding before you do in a way that Apple doesn't like so Apple sends the code request again.

In any case, that's an Apple and you thing - not an iCloud3 thing.

**Comment by ahamro** [comment]
> It would seem from how you described the issue that you've configured all of your devices to be Trusted Devices and, subsequently, they will all receive the notification.

I think you've nailed the cause of receiving requests on my wife's iPhone. Thanks!

**Comment by pauly7300** [comment]
I believe this problem may be misdiagnosed regarding why your wife's phone is getting the Apple ID Sign in request prompt.  Those prompts are specific to one and only one AppleID.  In the case of icloud3, those prompts will show up on ios devices that are signed into icloud using the same AppleID you've specified in the icloud3 config screen such as in the screenshot below.  
If your wifes devices are getting the requests, it would suggest her devices are signed into the same AppleID that your devices are.  Can you confirm that she has her own independant icloud account setup with a different email address and that each of her devices are logged in to that separate account?  Also can you confirm that you've set up the family sharing from your account?  An AppleID can either be the originator of a family or a member of a family but not both.  

![image](https://github.com/gcobb321/icloud3_v3/assets/11494052/cb6c1503-4621-489e-b193-bccda54e790f)

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
