### ISSUE TITLE
Longer or fixed update interval for some devices

### ISSUE THREAD

**Issue by philrich** [gcobb321/icloud3_v3#238]
Hi,

I have some devices, where i don't want a short update interval. I just want to know the location every ~30min (to save battery as good as possible). This is what the original home assistant icloud extension did, but unfortunately its broken since some time. These devices don't (and never will) have the home assistant app installed.

Now, if I understood correctly, when a device exits a zone, the update interval is set to 15sec if it is in a 2.5km radius. As these devices are in this radius most of the time and the owners are walking most of the time the battery of the device drains too fast.

Is it possible to tune parameters for this use case? Does monitor mode help in this case? Is it possible to set a manual tracking method and update the location via an automation?

**Comment by gcobb321** [comment]
That should not be too difficult to implement. I’ll make the changes and send you an early rc9 to try to make sure it works for you.

**Comment by gcobb321** [comment]
I've added a 'Fixed Interval" to the Update Devices screen that should do this. Let me know if you have any issues with it.

Below is the latest rc9 update. Unzip icloud3_v3-rc9.zip into the icloud3 directory and restart HA.

There are a lot of updates, bug fixes and new features. Review ChangeLog.txt for a complete list. They are at the top under the rc9 heading.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13641390/icloud3_v3-rc9.zip)

**Comment by philrich** [comment]
Wow, that was quick! Thanks Gary, I already installed rc9, will report back soon.

**Comment by philrich** [comment]
It works! In the log of the affected device the interval is always set to the value I have set for this device (30min). I still see down-spikes in the Interval history card in homeassistant. Maybe it has something to do with old locations? On a side note: the Interval entity changes the unit-of-measurement according to the current interval (hrs, min, sec). This makes it difficult to interpret the history chart.
Here is a screenshot of the interval history:
![image](https://github.com/gcobb321/icloud3_v3/assets/17569738/6077819e-7e54-4483-b57c-2638954f607e)
The last down-spike in the history graph is at 00:47:05. This is the log at this point in time:
![image](https://github.com/gcobb321/icloud3_v3/assets/17569738/795cd0bf-30f4-4413-b0f2-8615b8aca37e)

This release fixed another nasty bug which drove me crazy: when the battery of the device was empty the device did not come back in icloud3 when the device was charged and came online again. It needed multiple homeassistant restarts to come back. Thank you for this fix!

**Comment by gcobb321** [comment]
Yes, the c change in the interval time to a short o one is due to poor/old data being returned from Apple. The interval history is going to reflect that. The interval history graph may be interesting but that is the way it is.

**Comment by gcobb321** [comment]
Here is the latest version of rc9 before I release it next week for you to try.

The final changes won't affect you but I wanted to make sure I didn't break anything.
One critical change is to the method of determining the time an iOS App trigger takes place and how time zones are handled. Check the Event Log to see if a Trigger or zone change time does not seem to match the event time.

Unzip rc9 and restart as always.

[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13693706/icloud3_v3-rc9.zip)

**Comment by philrich** [comment]
I installed your new rc9 - did not notice anything unusual.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
