### ISSUE TITLE
Feature request: Sensor for minimum distance to Zone (/Home) of all tracked devices

### ISSUE THREAD

**Issue by klingbing** [gcobb321/icloud3_v3#239]
Hi Gary,

I have some use cases where I could use a sensor that gives me the **minimum distance** to Home **of all tracked** icloud3 devices.

I tried doing this Q&D with a [Min/Max HA Helper](https://www.home-assistant.io/integrations/min_max/) using the in my case two sensor.device_icl3_home_distance sensors and type min. 
This appears to result in a "Units of measurement do not match for entity sensor.distance_all_to_home" error message in the HA log while `unit_of_measurement: km` is set for both icl3 home distance sensors. I was able to "fix" this (Q&D) by adding a `customize_glob:` to my configuration yaml with `unit_of_measurement: "km"` for the two icl3 sensors and the sensor.distance_all_to_home the Min/Max Helper creates, but there has to be a simpler way of doing this.

**Comment by gcobb321** [comment]
Can you explain what you are trying to do. I'm not sure what the minimum distance from a zone (Home) might be used for. Maybe I can then suggest something.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
