### ISSUE TITLE
All entities Unavailable

### ISSUE THREAD

**Issue by Whizzykid** [gcobb321/icloud3_v3#240]
Hi, I just installed this as a first time user and all seems to have been created, but I cannot get any of the entities to update.

Is there something I missed in the set up? Or have I found a bug?

<img width="648" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/118218986/85ccc00b-38b6-4fab-8d35-b9e67546adf3">

**Comment by gcobb321** [comment]
1. Did you go through the v2.4 to v3 migration steps in the in the iCloud3 docs? Or just add iCloud3 as an integration?
2. When you add it, it migrates the devices and set them to an Inactive status and they are not tracked. See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/0.1-migrating-v2.4-to-v3.0?id=step-32-review-the-icloud3-device-tracker-entities-screen) for more info. Note the highlighted message in red. 
3. Does the _Event Log_ display? Any messages? And device info?

**Comment by Whizzykid** [comment]
> 1. Did you go through the v2.4 to v3 migration steps in the in the iCloud3 docs? Or just add iCloud3 as an integration?
> 2. When you add it, it migrates the devices and set them to an Inactive status and they are not tracked. See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/0.1-migrating-v2.4-to-v3.0?id=step-32-review-the-icloud3-device-tracker-entities-screen) for more info. Note the highlighted message in red.
> 3. Does the _Event Log_ display? Any messages? And device info?

Thanks for the response,

1- I went directly to v3

2- The device is set to active
<img width="548" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/118218986/7c287e7f-c623-46da-8e8e-5514660be1e3">

a quick look through the log and I can see this:
<img width="656" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/118218986/2f1c8d47-fee1-47bc-9b70-04bfe319ad97">

Any ideas from that?

**Comment by gcobb321** [comment]
You are not tracking with iCloud. The FamShr on the Update Devices is None so you are only with the iOS App. I suspect the Mobile App Integration might not be set up, is disabled or the sensors it uses is disabled. Then that got a lot of errors so there was no location data source.

 I will be releasing rc9 in a few days that checks that. I have attached rc9 below. Install and lets see what that detects.  Stage 3 & 4 of the startup show how the iOS App is configured and if there is anything that is disabled.

Unzip icloud3_v3-rc9 into the icloud3 directory and restart HA.
[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13696669/icloud3_v3-rc9.zip)

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
