### ISSUE TITLE
No Devices have been set up, nothing will be located or tracked

### ISSUE THREAD

**Issue by tluethi71** [gcobb321/icloud3_v3#241]
Hello
Great integratoin. I am trying to install iCloud3 v3 (not migrating). I was successfully to connect my Apple ID with iCloud3 and I entered also successfully the 6 digit code. But if I go one step further I am not able to choose any devices. 
I have HA Companion OS installed...
What did I wrong?
Br 

<img width="577" alt="Bildschirmfoto 2023-12-17 um 21 05 35" src="https://github.com/gcobb321/icloud3_v3/assets/118109408/f6ed4736-2fa6-491a-95db-757c7fd2ab03">
<img width="585" alt="Bildschirmfoto 2023-12-17 um 21 04 48" src="https://github.com/gcobb321/icloud3_v3/assets/118109408/a400443c-dccd-463d-b079-197c6c451603">

**Comment by gcobb321** [comment]
You have to add a device to iCloud3. Add Device is highlighted, Click Weiter and that takes you to the next screen. Then select the iCloud device to be associated with it

**Comment by tluethi71** [comment]
oh no!! stupid me.. quite embarrassing;) sorry for that. all went well. thanks for the quick reply..

**Comment by gcobb321** [comment]
Glad it went well. I’ll close this for you but feel free to reopen if you run into anything. Rc9 will be posted in a few days so watch for that.
