### ISSUE TITLE
Seems the services icloud3.find_iphone_alert and icloud3.lost_device_alert are no longer working

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#242]
Hi Gary! Hope this finds you well...

These 2 services seem are no longer working...

Seems the services icloud3.find_iphone_alert and icloud3.lost_device_alert are no longer working.

Am I missing something?

service: icloud3.find_iphone_alert
data:
  device_name: 1234132kjhkjh12hj43k123j4hk13h14

Thanks, in advance.
Marcelo

**Comment by gcobb321** [comment]
I'm not having any problems with either service call. The Lost device sends the message with phone number and disables the iCloud access until you enter the iCloud password in the Settings App. The Find my iPhone sends the sound notification.

Check the device you are sending it too. Maybe it's one you no longer have or you have the sound on the device off (it will still vibrate and display a message).

**Comment by gcobb321** [comment]
I realized that i am running rc9, which I hope to release tomorrow.
Here is a copy of it. Unzip into the icloud3 directory and restart HA.
[icloud3_v3-rc9.zip](https://github.com/gcobb321/icloud3_v3/files/13719717/icloud3_v3-rc9.zip)

**Comment by lovelyjubley** [comment]
Not sure if I have a similar issue.
Running v3 rc9.
If I use the iCloud event log to call the service action to "send find my iPhone alert" it works fine, but using the service call does not.

**Comment by gcobb321** [comment]
@lovelyjubley 
I just ran through the Event Log > Send Find My Phone alert to this device, the Service Call on the Developer tools and through an Automation on the Devices & settings > Automations. All worked fine and sent the alert to the phone.

On the Service Call and the automation, i selected Gary (gary_iphone) to select the device. The device setting is hidden behind a dropdown list on the Automation. Could you have not selected the correct device?
