### ISSUE TITLE
Find iPhone alert tone for family member

### ISSUE THREAD

**Issue by vlumikero** [gcobb321/icloud3_v3#244]
Hi,

I can’t get the service to produce an alert on my wife’s iPhone, but it works on my own iPhone. I can get it to work in the stock iCloud integration but would like to migrate to iCloud v3. 

Anyone else manage to get this scenario working? Any tips?

**Comment by gcobb321** [comment]
Is your wife’s phone being tracked by iCloud3? It need to be. 
Are you selecting the iCloud3 device tracker entity to send the alert to? Or the device_tracker entity for iCloud integration. 
The alert can be sent several ways.  Are you r requesting it through:
- The _Event Log > Actions_
- _Configure Settings > Actions_ screen_
- HA > Developer Tools > Service Call
- An automation and script

**Comment by vlumikero** [comment]
Thanks for taking a look @gcobb321.

Her device is tracked in iCloud v3, and I can see relevant stats being updated in the integration’s entities. I’m using the Developer Tools/Services UI to send the ping, and it works with my own phone. I’ve used “iCloud 3” as an appendix in naming the entity to be sure I’m using the right one. 

![IMG_1517](https://github.com/gcobb321/icloud3_v3/assets/13744614/d2915ae7-ce5a-4ecf-a4c1-97a57f5bcb8f)

**Comment by gcobb321** [comment]
The service call from Developer tools calls the ic3 service handler with the HA device ID it gets from the device registry. iCloud3 translates that to the iCloud device ID and sends the alert request to Apple. 

The request can also be done from the _Event Log > Actions_ screen for the selected device. 

Both will display messages in the _Event Log_. Do it from the Developer tools > Services like you have been doing. When that fails, do it again from _Event Log > Actions >_  . Then review the _Event Log_ screwed to see what messages are displayed for each one and see if there are any differences in the messages or errors in the HA log. Post a screenshot of the messages.

**Comment by vlumikero** [comment]
Thanks! I hadn’t used the Event log card before, that was very helpful. I’ve now reconfigured the entry for my wife’s phone. 

When I use the icloud3.find_iphone_alert service now, my wife’s phone shows an alert from the iOS HA app instead of the native Fmf alert (which is more persistent). My own phone has the latter behavior. Have I missed something in the configuration?

**Comment by gcobb321** [comment]
@vlumikero 
As I recall, the alert will be sent via the iOS app when there was a problem setting up the FamShr device to be used f for location and other data. 
1. Check the _Event Lg_ Stage 3&4 for any error messages. 
2. Review the device that was selected for your wife on the _Configure Settings > Update Devices_ screen. M make sure it is her current phone and not an old one. 
3. make sure there are famshr locations that are being used in the _Event Log_

**Comment by vlumikero** [comment]
There was a missing permission in the iOS location settings that prevented the phone from being listed in the Fam share devices list. It works now. 

Thanks a bunch for your support and the plugin @gcobb321! A couple of coffees on their way.

**Comment by gcobb321** [comment]
Glad it's now working and thanks for the coffee
