### ISSUE TITLE
Battery charging glitch after latest update

### ISSUE THREAD

**Issue by bkr1969** [gcobb321/icloud3_v3#245]
First of all...thank you so much for this integration.  It works amazingly well!  I noticed today that my phone's battery % was spot on until I plugged it in. It went immediately to 100% and the status never went to charging.  Minor in the grand scheme, but thought I'd mention.

**Comment by gcobb321** [comment]
Look in the _Event Log_ at the time you plugged it in. Is the data from famshr or the iosapp? 
The HA history should show the iosapp battery level sensor for that time. Did it change to 100% then?

**Comment by bkr1969** [comment]
Not sure where to find that.  The only thing related that I see in the logs is:
```
Recursive use of cursors not allowed.
15:04:56 – (ERROR) iCloud3 v3: iDevice Tracker (custom integration)
```

**Comment by gcobb321** [comment]
That error would be from the Waze History. Send _icloud3-0.log_ to geekstergary@gmail.com and I’ll look into it.

**Comment by gcobb321** [comment]
I have the HA history in my configuration.yaml. With it, you can display the history of sensor updates. See HA docs about adding or using it. You can filter and select battery entities to see how they changed

**Comment by JtwoA** [comment]
@gcobb321 I'm seeing an issue with my battery sensor.  It is not reporting the change to charging as it did previously.  This history graph is from midnight thru noon today.  It was very def docked for charging ~0030 ET this morning.

<img width="1319" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/12992040/b24b9948-aae8-4ad5-838e-356083108d70">

This drives NIGHT mode in my house, that's how I discovered it.

**Comment by gcobb321** [comment]
The charging status comes from the famshr when the phone is located and seeing the icon displayed on the iosapp battery level sensor. iCloud3 looks at the iosapp sensor every 5-secs and the famshr on a locate. See what the iosapp reported in the history. Maybe nothing if the phone was asleep or the iosapp was unloaded.

**Comment by JtwoA** [comment]
> The charging status comes from the famshr when the phone is located and seeing the icon displayed on the iosapp battery level sensor. iCloud3 looks at the iosapp sensor every 5-secs and the famshr on a locate. See what the iosapp reported in the history. Maybe nothing if the phone was asleep or the iosapp was unloaded.

Oddly... last night I opened the app to watch what happened and... everything worked just fine.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
