### ISSUE TITLE
Location updates under 5 mins get Apple ID Locked

### ISSUE THREAD

**Issue by notownblues** [gcobb321/icloud3_v3#246]
Hi,

First of all thank you so much for this integration. It really is a game changer to track iOS devices especially Apple Watches with Cellular, which I use as my main tracker.

I've been having some issues with Update Frequencies however. I noticed that if I set an update interval of less than 5 minutes (i.e. 2 minutes), it will get my Apple ID locked after a few hours and stop the integration from updating.

To resolve it, I need to login into my iCloud account each time and unlock my Apple ID then restart the integration and it starts tracking again. This happened on a daily basis so I increased the location frequency update to 5 minutes and it seems to be the sweet spot to not get the Apple ID locked.

Today when I got home it took 5 mins to update the location so it can be problematic with the alarm system.

Do you know if there any way to increase the location updates without getting the Apple ID locked?

Thanks

**Comment by JtwoA** [comment]
Watching this as I'm curious how @notownblues is using his watch to do this.  My attempts were all met with either horrid watch battery life or delays as I waited up to five minutes to enter my house.

**Comment by notownblues** [comment]
![IMG_1706](https://github.com@JtwoA obb321/icloud3_v3/assets/29582306/1fc2101c-569d-4df8-a7ac-c199ebd147de)

@JtwoA I didn't experience any battery drain using the integration but I've got the Apple Watch Ultra 2 so the battery lasts longer. Else than the 5 minute interval issue it's working really well for me for Apple Watch.

**Comment by gcobb321** [comment]
@JtwoA 
The basic problem is there is not a way to trigger a zone enter or exit from just the watch to start a location update to enter Home or exit Home. The 5-minute interval triggers a FamShr update to determine the location.

I do not have a Watch. My wife does and keeps threatening to get one for me but I'm happy with an iPhone in my pocket. I believe the HA Watch Complication supports actionable notifications (I don't know anything about them other than a brief read). Could you create an automation that is triggered by a zone change to away/not_home. Then if you touch it, it triggers an iC3 service call that does an immediate location update. Just a thought for you Watch guys to figure out. If it works, send me the details and I'll add it to the iC3 docs.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
