### ISSUE TITLE
iPhone suddenly moving to AWAY even though I'm home all day

### ISSUE THREAD

**Issue by JtwoA** [gcobb321/icloud3_v3#248]
<img width="495" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/12992040/d8a03cdd-e706-4d81-a214-ae8b0b03af1b">

My iPhone has suddenly (this weekend) been drifting and triggering my home into AWAY mode.  Only opening the iOS App brings it back - and it's never been acting like that until this weekend.

Is there a setting somewhere that I've possibly bumped?

**Comment by gcobb321** [comment]
All I can suggest is review the Configure settings for each device and make sure there are no error messages. Might also be sun spots, poor gps, signal, poor cell signal. Try HA Settings > Companion App > Locate > Update Location for the phone to send a location update trigger to iC3.

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
