### ISSUE TITLE
battery status:  charging, not charging, etc

### ISSUE THREAD

**Issue by JtwoA** [gcobb321/icloud3_v3#25]
I use battery charging status as an automation trigger and notice in B6 and B7 that the status seems to only show as one of these three:

`Not Charging`
`notcharging`
`---`

**Comment by JtwoA** [comment]
Here’s what I’m seeing:

**Comment by JtwoA** [comment]
If I look at this in MSR (my rules engine) this clarifies what I’m seeing a bit more:

**Comment by JtwoA** [comment]
Now it’s showing as such:

**Comment by gcobb321** [comment]
I’m not familiar with MSR. Plus, I can not see any of your images on GitHub. How about sending them to geekstergary@gmail.com so I can see what you are dealing with.

**Comment by JtwoA** [comment]
MSR (Multi System Reactor) is a rules-engine.  It plays very well with Home Assistant and I use it for all of my rules management.

Here are the screenshots of what I’m currently seeing in Home ASsistant:



This is from within the Entity screen in MSR:


Here’s a more complete image from Home Assistant:

**Comment by gcobb321** [comment]
I fixed a lot of things regarding the battery in beta 8.
