### ISSUE TITLE
Waze History not working?

### ISSUE THREAD

**Issue by rientsbr** [gcobb321/icloud3_v3#250]
The sensor: is not been updated, is this a know issue?
[sensor.icloud3_wazehist_track]

**Comment by gcobb321** [comment]
It was a problem. The _sensor.icloud3_wazehist_track_ was being excluded from the HA history file.

Download and unzip the _icloud3-v3_rc10.zip_ file into the _config/custom_components/icloud3_ directory and restart HA.

I've also verified the _card_mod_ add-on that is available on HACS and described in the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/7.2-other-topics?id=display-the-waze-history-locations-on-a-map-card).

[icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13843376/icloud3_v3-rc10.zip)

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
