### ISSUE TITLE
iCloud3 not waiting for Mobile App Intergration

### ISSUE THREAD

**Issue by scotty1395** [gcobb321/icloud3_v3#251]
In recent HA versions the Mobile App Intergration seems to be loading slower/later causing iCloud3 to complain it isn’t loaded. Every time HA is restarted I need to manually restart iCloud3 for it to load correctly.

**Comment by gcobb321** [comment]
The Mobile App Integration will now be checked when the iOS App devices are being set up and, if it had not finished installing, again after HA had finished setting itself up.

Unzip this into the iCloud3 directory and restart HA. I ran it through various operations but using debug code. Let me know if this solves the issue you are having

[icloud3_v3-rc10.zip](https://github.com/gcobb321/icloud3_v3/files/13850940/icloud3_v3-rc10.zip)
.

**Comment by scotty1395** [comment]
Looks to have fixed it. 
Thanks Gary

**Comment by gcobb321** [comment]
Super. I’ll put it up as a new release

**Comment by Seger85** [comment]
> Super. Ich werde es als neue Veröffentlichung veröffentlichen

Did I miss the version, or are you still fine-tuning it?

Best regards from
53° 4‘ 45.48 N 8° 48‘ 6.12 E

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
