### ISSUE TITLE
Release Candidate 9 - v3.0.rc9 - issue with sensor.xxxx_icloudv3_zone_name

### ISSUE THREAD

**Issue by andyblac** [gcobb321/icloud3_v3#252]
the sensor is removing spaces from Zone name, see below

<img width="261" alt="Screenshot 2024-01-07 at 12 30 19" src="https://github.com/gcobb321/icloud3_v3/assets/77936/bbf7b352-782c-4c50-9231-c304feabac4a">

<img width="569" alt="Screenshot 2024-01-07 at 12 26 34" src="https://github.com/gcobb321/icloud3_v3/assets/77936/081a5bb4-0225-4f34-b035-25d92a09350d">

**Comment by gcobb321** [comment]
It’s always done that. The iCloud3 docs for the _Configuration Screens and Parameters >  Sensor_ screen [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/7.1-config-parms) describes the zone sensors as:

**Zone Name Sensors** - Zone name sensors provide different formats for displaying the zone name when the device is in a zone. The formatting rules are:
_zone_name - A reformatted zone entity name without spaces and apostrophes (the_shores → TheShores)
_zone_fname - The zone's friendly name
_zone - The HA zone entity

**Comment by andyblac** [comment]
Even the main state of the entity ?, surely it contain a space ?

**Comment by gcobb321** [comment]
The zone can be displayed in several formats. The format is selected on the _Configure Settings > Update Parameters Menu > Format Settings_ screen. One of them is the HA friendly name (preferred). What have you selected?

**Comment by andyblac** [comment]
I'm 99% sure it used to contain a space.

<img width="660" alt="Screenshot 2024-01-07 at 13 47 29" src="https://github.com/gcobb321/icloud3_v3/assets/77936/0f0b101a-b1d4-4c44-b320-1427feb78e73">

**Comment by gcobb321** [comment]
Go to HA Device and Services > Areas and Zones > Zones and change the name of the zone to what you want it to be. Then select HA Zone Friendly Name in the iCloud3 parameters. Nothing has been done to the way the zone name is formatted in a long long time.

**Comment by andyblac** [comment]
it is how I want it to be, 
<img width="261" alt="Screenshot 2024-01-07 at 12 30 19" src="https://github.com/gcobb321/icloud3_v3/assets/77936/c3688166-5d7d-4f98-b302-9e5f5dcbbd7a">

**Comment by gcobb321** [comment]
There are several Zone sensors that iCloud3 can create — zone_name and zone_fname are two of them. They are selected on the _Configure Settings > Sensors_ screen. The zone_name removes spaces, _’s and a few other things that is described on the description  line. It is reformatted to make it easier to use in automations without a lot of reformatting, quote Mark checking, etc. it has been this way since v2. The zone_fname sensor does not do any reformatting. Maybe that it’s what you are thinking of. 

Create the zone_fname sensor and us that and see if it meets your needs

**Comment by andyblac** [comment]
how do I do that ?

**Comment by andyblac** [comment]
ok, yes, it now displayed correctly, thanks, although I'm pretty sure it used to work correctly in early beta's, just not been to a zone with a space for a while

**Comment by andyblac** [comment]
ok, now have another issue it not working correctly, got `Home` it not showing as home is the other sensor does.

<img width="369" alt="Screenshot 2024-01-07 at 14 36 02" src="https://github.com/gcobb321/icloud3_v3/assets/77936/f319780b-443a-46bd-aec8-2f0fd35d2ee5">

**Comment by JtwoA** [comment]
> ok, yes, it now displayed correctly, thanks, although I'm pretty sure it used to work correctly in early beta's, just not been to a zone with a space for a while

The inference in your response is that it's not working correctly - that is not the case.  In is working as intended/designed.  As noted, it has been this way since v2.  I've played with this setting in deciding which to use in my automations and can verify it has been there and has not changed since v2.

**Comment by gcobb321** [comment]
There were some Zone naming  issues early on but that was related to the value that should display in a device tracker entity field.

**Comment by andyblac** [comment]
so why does it show correctly in the description on setting stage (with a space) in friendly name ????, IMO removing the space for the main state is just wrong.
<img width="660" alt="Screenshot 2024-01-07 at 13 47 29" src="https://github.com/gcobb321/icloud3_v3/assets/77936/ab6f3906-b4db-4b10-ae71-93d5a388e491">

See above `Lloyds Bank` has a space in it.

**Comment by andyblac** [comment]
also using fname will I loose `Away` as it seems `Home` does not work ???, what happens if in not in a zone with  name.

**Comment by gcobb321** [comment]
Home and Away will be ok. If you are not in a zone, both zone_name and _fname are Away

**Comment by andyblac** [comment]
> Home and Away will be ok. If you are not in a zone, both zone_name and _fname are Away

hmm, `Home` not working, it just show the zone name, not `Home`, my Zone name is not `Home`, as have 2 homes

**Comment by JtwoA** [comment]
> > Home and Away will be ok. If you are not in a zone, both zone_name and _fname are Away
> 
> hmm, `Home` not working, it just show the zone name, not `Home`, my Zone name is not `Home`, as have 2 homes

@gcobb321 correct me if I'm wrong - you can have only one HOME zone.  User may have two houses but only one can be delineated as "home", yes?

**Comment by andyblac** [comment]
> > > Home and Away will be ok. If you are not in a zone, both zone_name and _fname are Away
> > 
> > 
> > hmm, `Home` not working, it just show the zone name, not `Home`, my Zone name is not `Home`, as have 2 homes
> 
> @gcobb321 correct me if I'm wrong - you can have only one HOME zone. User may have two houses but only one can be delineated as "home", yes?

correct, my main home is my home, but both zones name are the street name.

**Comment by gcobb321** [comment]
Yes, the Home zone is where HA Server lives. It's name (friendly name) can be changed on the Zone settings screen. I think it will only change the friendly name (have never tried it), not the `zone.home`  entity name. Otherwise, another house is just another zone.

**Comment by andyblac** [comment]
`zone_name`
<img width="255" alt="Screenshot 2024-01-07 at 15 41 03" src="https://github.com/gcobb321/icloud3_v3/assets/77936/37d65bfc-d31b-4446-a555-ff43691fa533">


`zone_fname`
<img width="240" alt="Screenshot 2024-01-07 at 15 41 54" src="https://github.com/gcobb321/icloud3_v3/assets/77936/0ec520bd-7c64-4a24-8c04-be973e0397ab">

**Comment by gcobb321** [comment]
Thanks for the info. The HA zone names and data come from _config/.storage/zone_ and _config/.storage/core.config_ files and is provided by HA when iC3 starts.
