### ISSUE TITLE
HA restart breaks iCloud authorisation

### ISSUE THREAD

**Issue by jaymunro** [gcobb321/icloud3_v3#253]
Almost every (but not all) restart of HA results in having to reauthorise the iCloud account connection. Even after one day of requesting an Apple ID verification code, entering it, it being accepted and services working normally.

This has been happening for several weeks now.

The log shows:
```
Stage 4 > Setup iCloud & iOSApp Data Source

ALERT > Some devices could not be verified. iCloud Location Services will be reinitialized
• Unverified Devices > jay_iphone_icloud3, jay_watch_icloud3, masami_iphone_icloud3,
aska_iphone_icloud3, zoe_iphone_icloud3

iOS App Devices > 3 of 5 iCloud3 Devices Configured 
HJM iPhone (iphone) → jay_iphone_icloud3 (iPhone13,3)
Masami's iPhone 7 (masami_s_iphone_7) → masami_iphone_icloud3 (iPhone9,1)
Zoe's iPhone (zoes_iphone) → zoe_iphone_icloud3 (iPhone14,7)
• Masami's iPhone 6S (masami_s_iphone_6s) → Not Monitored,
Masami's iPhone 6S (iPhone8, 1)
• Kitchen iPad (kitchen_ipad) → Not Monitored,
Kitchen iPad (iPad4,1)
• HJM MacBook Air (hjm_macbook_air) → Not Monitored,
HJM MacBook Air (MacBookAir10,1)
• HJM iPad (hjm_ipad) → Not Monitored,
HJM iPad (iPad13,1)

Find-My-Friends Devices > Not used as a data source

ICLOUD FAMILY SHARING DEVICES ERROR >
• No devices were returned from iCloud Account Family
Sharing List, Retry #11

iCloud Account Used > jo.@mu......

iCloud Location Services interface > Verified (stage4)

iCLOUD ALERT > Family Sharing Data Source is not available.
The web url providing location data returned a Service Not Available error (stage4)

iCloud Location Svcs Interface > Started during initialization
• Completed: Setup
• Inprocess: Authenticate
• Needed: FamShr, FmF 

iCloud Account Used > jo.@mu.....

iCloud Location Services interface > Verified (stage4) 

iCloud3 Error > An error occurred logging into the iCloud Account. Error-cannot access local variable 'response where it is not associated with a value 

iCloud Location Services interface > Verified (init) 

iCloud3 Error > An error occurred logging into the iCloud Account. Error-cannot access local variable 'response where it is not associated with a value

iCloud Location Svcs Interface > Started during initialization
• Completed: Setup
• Inprocess: Authenticate
• Needed: FamShr, FmF 

iCloud Account Used > jo…@mu…
```

**Comment by gcobb321** [comment]
1. It looks like you are having communication issues with Apple. Any other HA errors? Network? Internet?
2. Check _Configure Settings > iCloud Account and iOS App_ screen and make sure username/ password are ok and China it’s not enabled. 
3. Reset the iCloud account and get a new code _Configure Settings > Enter/Request Verification Code_ screen 
4. Are you running a regular HA setup or in a container? Proxies? Virtual environmental? If so, that is probably the problem.

**Comment by jaymunro** [comment]
I think I may have narrowed this down to a DNS setting referencing a local container dns server that wasn't ready in time for iCloud3. Adding a secondary server such as 8.8.8.8 seems to have resolved the matter. TBH the secondary should have already been there and I'm not sure why I didn't add it following a system recovery from backups.

That said, if the dns was the cause perhaps iCloud3 could be more resilient to network issues at startup and try again at periodic intervals without breaking the authorisation??
