### ISSUE TITLE
Not getting event log card to work

### ISSUE THREAD

**Issue by Dekadinious** [gcobb321/icloud3_v3#262]
![image](https://github.com/gcobb321/icloud3_v3/assets/37292177/5ed38da5-abeb-4288-80dd-f661bdaa5947)

I am on rc9 and trying to add the event log card to debug why nothing seems to be updating from my wife's iPhone. I only get the error above.

I see that it is here:

![image](https://github.com/gcobb321/icloud3_v3/assets/37292177/fa04a6ed-c1bb-4f7b-a389-d28068f78917)

Here is the configuration in resources:

![image](https://github.com/gcobb321/icloud3_v3/assets/37292177/93e51b06-e554-4281-ac10-039e74902b24)

I have restarted the integration and restarted Home Assistant.

I use a Raspberry Pi and I am on HomeAssistant OS with everything updated to the newest versions.

**Comment by gcobb321** [comment]
On my RPi, the directory is _config/www/…_ where yours is _homeassistant/www/…_. There is a fix in rc10.1 that solves that issue. It was uploaded yesterday and it’s now available on HACS.

**Comment by Dekadinious** [comment]
Hmm, I am trying to do redownload form HACS:

![image](https://github.com/gcobb321/icloud3_v3/assets/37292177/7b18746f-6e42-4592-896c-e41459f0b41b)

But I am not seeing the new version.

**Comment by gcobb321** [comment]
Sometimes going to the 3-dots in HACS after selecting iCloud3 and then doing Reload Info will do a refresh. Sometimes waiting a day will show the latest. Sometimes you go to the Release page, download the zip file, unzip it to the icloud3 directory and restart HA.

**Comment by Dekadinious** [comment]
I have no idea what happened, but now it suddenly just works. I have not been able to update yet.

Anyways, do you have any documentation on the algorithms used for tracking updates? On my Android, I can set high accuracy mode when I am closer than 4 km from my house and connected to Bluetooth in the car, and this works perfectly for battery life and opening the garage door at the exact same spot when I arrive home.

I am struggling getting the garage door to open with my wife iPhone because I see no way to tell if she's driving or not, other than "activity" which seems to be not very accurate. And the location just does not update often enough. I have activated the automatic update option based on how close to home she is. How often will that update at what distance?

**Comment by marceloaf** [comment]
Hi, sorry to intrude in the conversation... 

Here is my 2 cents: Maybe you can use the iOS focvs mode to update your wife’s driving status on HA and try to use it as a trigger to your automation.

Here is what I have set:

1 – Configure iOS to automatically update the driving status (This has been very accurate)
![Driving mode automatically](https://github.com/gcobb321/icloud3_v3/assets/11551691/4bfc4969-e328-4abc-9cc5-fb7db2546878)


2 – Based on the driving status I created an automation that executes a shortcut to update via webhook an input_boolean in HA
![automation to adjust HA boolean](https://github.com/gcobb321/icloud3_v3/assets/11551691/e91d9903-ec68-4347-9ce6-449405c43bed)
![shortcut](https://github.com/gcobb321/icloud3_v3/assets/11551691/eee13a48-7e1e-444a-be84-35508ed88269)


3 - With the driving status correct I use it as a trigger or condition in an automation

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
