### ISSUE TITLE
Need some HELP please!!!

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [gcobb321/icloud3_v3#263]
Hello @gcobb321 I hope you can help explain me the following issue.... I am using both the HA companion app and your integrations device trackers for a person entity, but now I noticed that when the person leaves home all the time after the person left the state would change to away triggered by the HA app device tracker after about a minute but then few minutes later change for a short period (few seconds) to home and the to away again, the time that it changes back to away is same as time that the device tracker from Icloud v3 changes from home to away (what happens several minutes after the companion app tracker changed to away, what I not understand as I selected the HA tracker in the config to be used next to Icloud credentials?). 

Now I started playing with the intervals between updates for as well in zone and outside zone, when I change the outside zone interval to 1 minute instead of the default 0 minutes and the inside zone interval to 2 minutes it stops the behavior described above and I not get the short period at home registrations anymore on the person entity.

ONLY ..... I still noticed a big difference of several minutes between when the HA App device tracker switch to away compared to the Icloudv3 tracker... the icloudv3 tracker switches to away minutes later.... it looks like lowering the update interval when in a zone to 2 minutes also brings the difference back to about 2 minutes, not know if this is a coincidence or related.

Am I doing something wrong that is  causing the icloudv3 tracker to switch to away minutes later as the HA companion app tracker???????

**Comment by smarthomefamilyverrips** [comment]
![Screenshot_20240204_153342_Home Assistant](https://github.com/gcobb321/icloud3_v3/assets/97987488/3a7fa62c-d858-4705-9977-9793f72749bb)
![Screenshot_20240204_153313_Home Assistant](https://github.com/gcobb321/icloud3_v3/assets/97987488/98c8acd4-dd42-42a8-a15c-b2853394dbbf)

Some screenshots showing the difference

**Comment by gcobb321** [comment]
By setting the inzone time very low (less than 5-min), you are going to get a lot of reusing the same location as the last time because iCloud3 says the location is still good and within the still not old threshold. That would take you back to Home an after the Mobile App was processed taking you to away. I keep mine at 30 or 60 minutes. 

The out of a zone fixed interval should be set to 0 so iCloud3 will determine the interval. It was added for some devices without the Mobile App. Setting it to a very short interval with the Mobile App installed will also reuse a l previous location because iCloud3 thinks it is not old. Set it to 0. 

Because of your experience, I am going to change the inzone interval so it has to be above 5 ( maybe 10) and the same for the Away fixed interval.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 I did test for several hours with different in zone and out zone intervals. Now I get it working to not give me false home readings anymore and to update from home to away also within maximum 1 minute after the HA app tracker changed from home to away.

I now use for the In zone interval the default 5 minutes and for the out zone interval 1 minute instead of the default 0 minutes

This solved it for me to have icloudv3 suitable for my use case. So personal I hope you will keep the adjustment possibilities for in and out zone intervals as they are

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 I did now install the eventlog card and did see that it says it not uses the HA device tracker if I understand correctly? Any idea why this is?

![Screenshot_20240205_062418_Home Assistant](https://github.com/gcobb321/icloud3_v3/assets/97987488/cc9a09c6-daf8-4d46-bec7-c17a71d59bd6)

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 I now changed the intervals to how you suggested 

In zone 15 minutes 
Out zone 0 minutes 

I will give it a try this way to see if the away-home-away issue and slow change of icloudv3 tracker from home to away are solved this way, will keep you posted

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 changing back the update interval settings to your suggestion did bring back the issue as you can see on the below screenshots, i also did add a copy of the event log, so I hope you can explain and give a solution how to solve this. till then i will set the out zone interval again to 1 minute as that was the only way to make icloudv3 tracker valuable for my use cases (else gate will open as see person entity as home way after my wife left home, or proximity sensor distance get stuck for minutes on distances way closer or further away from home as actually are)

I hope you can help me out to solve this!

![1707301723254](https://github.com/gcobb321/icloud3_v3/assets/97987488/238165c2-8c98-4c87-9644-bb66522461be)

![1707301723643](https://github.com/gcobb321/icloud3_v3/assets/97987488/49eb6376-1b7a-4809-bdf9-6bf9c6ea5b1c)

![1707301720432](https://github.com/gcobb321/icloud3_v3/assets/97987488/876828b0-9a7a-4221-b8c9-2a5cafba5377)

[icloud3-event-log_2024.02.07-12.15.53.log](https://github.com/gcobb321/icloud3_v3/files/14193364/icloud3-event-log_2024.02.07-12.15.53.log)

**Comment by gcobb321** [comment]
I took a Quick Look at the Log file and saw the error message saying the Mobile App integration has not been set up. This means iCloud3 would not be able to monitor the HA iosapp sensors for zone changes for enter/exit triggers, location updates, etc. 

Let’s set up the Mobile App integration on _HA Devices & settings > Integrations_ and see if that helps. Restart HA after you do that to restart iCloud3. Also, set the Log Level to Debug Auto Reset on _Configure Settings > Page 2 > Format Parameters_ screen and email the _icloud3-0.log_ file to geekstergary@gmail.com, It has more info than the _Event Log_ export file.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 the mobile app is set up already (see second screenshot of my previous message what shows the device tracker entity created by the mobile app integration and see screenshots below), this message only occured one time because home assistant restarted because of powergrid failure, if you look at later entries it shows all started as should after a HA restart.

to me it looks like when i set outside zone distance to 0 minutes so the distance to home decides update interval it takes to long to update causing the person entity to fall back to wrong old location.

As said before if i use a 1 minute outside zone interval all works perfect and position and distance of my proximity sensor  updates are done frequently and also not have false person entity registrations of being on a old previous location

![1707317747893](https://github.com/gcobb321/icloud3_v3/assets/97987488/5a77a25f-d316-4868-bbcc-4a6fffe02cbb)

![1707317748023](https://github.com/gcobb321/icloud3_v3/assets/97987488/a01c5546-ea17-4481-a243-c20b5f7c5c07)

**Comment by smarthomefamilyverrips** [comment]
Closed because continued in #267
