### ISSUE TITLE
Need some advice to avoid being considered in a StatZone for x minutes

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#264]
Hello Gary, good morning!! Hope you're doing well.

Need some advice to avoid the below scenario....

- I went for a walk with my dogs earlier today and icloud3_v3 started monitoring my positions as usual. 
- At some time I met a neighbor and kept talking for some minutes. Fewer than 5 minutes for sure. 
- From this time on iCloud3_v3 only detected me again when I arrived at home more than 20 minutes later. I guess because it considered me at a statzone and reset the update time.
- Question: How do I adjust the time to consider sensors at a StatZone?

<img width="959" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/11551691/49b09c6b-631a-4d7e-b794-215afa023125">

<img width="959" alt="image" src="https://github.com/gcobb321/icloud3_v3/assets/11551691/d951111a-0ec6-414c-ae02-25ced9241da5">

**Comment by gcobb321** [comment]
It probably did go into a StatZone. When close to home, the interval could be as low as every 15-seconds so going into a StatZone will stop a constant update. Which it is suppose to do. The _Event Log_ will show what was going on. The Mobile App might have been too close to home to issue an exit interval hour the StatZone or its size and the Home zone size put them close to each other. Taking gps accuracy into consideration, it probably went from the StatZone directly to Home. 

You can reduce the StatZone interval on the _Configure Settings > Special Zones_ screen.
