### ISSUE TITLE
iCloud3 v3.0.rc10.2 (2/6/2024) has been uploaded

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#265]
**Description** - This release fixes the last few bugs in rc10-rc10.1 dealing with zone exit issues. It also changes a few messages on the Event Log during start up and changes the minimum zone interval times to 5-minutes to prevent conflicts with old location timings.

_**This is the final-final Release Candidate. I know, I've said that last time. But two things were identified and fixed. If nothing comes up, the base HA iCloud3 HACS version will be taken out of beta and go live next week if everything looks good.**_

### Update using HACS
When I create a new release, it is not picked up by HACS immediately. It might take HACS up to 48-hours to pick up the new release information and add it to the Devices & Services screen.

Check to see if the new version of iCloud3 is displayed as an available update on the Devices & Services screen. If it is not displayed there, do the following:
1. Open HACS from it's sidebar icon. Select Integrations, then type iCloud3 in the search field and press Enter.
2. Two items are displayed - iCloud3 Device Tracker and iCloud3 v3, Development Version.
3. Select iCloud3 v3, Development Version, click the 3-dots in the upper-right corner to open the menu. 
4. Select Update Information, Then select Download or Redownload. HACS will download and install the new version.
5. Restart HA like you normally do.
6. 
### Change Log
1. Outside of Zone with no Exit Trigger message - Changed the way the Exit Trigger was being logged so this wouldn't be issued when the trigger was actually issued.
2. Passive Zones and the Mobile App - The Mobile App does not issue an Enter Zone Trigger for passive zones (which is correct), but it will issue an Exit Trigger for them (which it should not do). This was creating problems by issuing an Exit Zone Trigger when leaving the real zone and then issuing another Exit Trigger when leaving a zone it had never entered (Passive or otherwise). This Mobile App error is now identified and changed into a Verify Location trigger.
3. Nearby devices - Nearby device info will not be used if the device being updated is in a non-Stationary zone.
4. Configure Settings - inZone Interval, Fixed Interval, Max Interval, etc. - Changed the minimum value to 5-minutes to prevent conflicts with old location threshold and reusing a location when it should be requested again.
5. Other code cleanup.
7. More iCloud3 Documentation updates.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 will this solve my issues in #263 because when i used your suggested update interval settings the issue just came back, only way for me to resolve the issue is a 1 minute outside zone interval and 5 minutes in zone interval. But if this update restricts me to put this settings it most likely will bring my issue back again. UNLESS this recent update have other changes that will resolve the issue i have?

**Comment by smarthomefamilyverrips** [comment]
Error after update see #266
