### ISSUE TITLE
After Update It Is Unable to Enter Special Zones Config Menu

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [gcobb321/icloud3_v3#267]
@gcobb321 After the update I am unable to enter the special zones section within the configuration menu

![1707326980166](https://github.com/gcobb321/icloud3_v3/assets/97987488/a418c887-2697-4591-8622-923b66f91011)

**Comment by smarthomefamilyverrips** [comment]
other problem after update it not is using mobile app tracker details when restarting HA, to make it work I need to use the "restart icloud3"action in the drop down menu of the event log card

![1707329718302](https://github.com/gcobb321/icloud3_v3/assets/97987488/69c7420f-f7a4-4e8c-875c-f9cac1e46d68)

**Comment by gcobb321** [comment]
I just got home and am looking at the Configure Settings > Special Zones now. 

That Error should have no effect since  the Galaxy Watch is not tracked by ic3. I will add a check in the setup to not display the red_x error if the mobile app device is not assigned to an icloud3 device.

Question:
1. Does the Mobile App zone display on the Event log or does that show NotUsed?
2. What are the devices/entities you are using for Person?
3. Are you using the proximity sensor integration?
4. Can you send me the icloud3-0.log file to geekstergary@gmail.com. I want to take a look at some of your tracking results and see how the Zone value changes.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 

1. it shows not used (see screenshot)
2. I use the icloudv3 tracker and HA mobile app tracker for GPS based trackers and ASUSwrt and Ping tracker for stationary trackers
3. Yes I use the proximity sensor integration and use icloudv3 tracker and HA mobile app tracker as entities for the proximity sensor
4. sure i will send now from smarthome.family.verrips@gmail.com

![1707330435646](https://github.com/gcobb321/icloud3_v3/assets/97987488/7a0d7dc1-f01d-4726-874d-ecdf0b069973)

**Comment by gcobb321** [comment]
I fixed the Special Zones error on the Config Settings. Looking at this now. I believe this is why the HA Mobile App is not being used and you are getting the Home-Away-Home person issue

**Comment by smarthomefamilyverrips** [comment]
> I fixed the Special Zones error on the Config Settings. Looking at this now. I believe this is why the HA Mobile App is not being used and you are getting the Home-Away-Home person issue

OK great to hear you found some fixes!

So if you release the fix for special zones and I do the update that also should fix my other issues if I understand correctly?

**Comment by gcobb321** [comment]
I hope so.
In Stage 4 right below Mobile App Devices > 1 of 1 ..., there is a line Checking Mobile App Integration > Loaded, Devices >" iPhone Lory", Samsung Fold Marco, Galaxy Watch Marco

Then in Mobile App Devices > 1 of 1 ..., it shows "iPhone Lory HA New"

The "iPhone Lory" comes from the HA Device Registry (from the HA iosapp devices) and the "iPhone Lory HA New" comes from what HA has loaded as part of the Mobile App Integration devices. iC3 checks to see if the "iPhone Lory", which is in the iC3 config is in the Mobile App devices and it is not, the name is different. That is why it is not monitoring the HA iosapp. 

Do you remember if you originally added it and then renamed it at some time.

**Comment by smarthomefamilyverrips** [comment]
> I hope so. In Stage 4 right below Mobile App Devices > 1 of 1 ..., there is a line Checking Mobile App Integration > Loaded, Devices >" iPhone Lory", Samsung Fold Marco, Galaxy Watch Marco
> 
> Then in Mobile App Devices > 1 of 1 ..., it shows "iPhone Lory HA New"
> 
> The "iPhone Lory" comes from the HA Device Registry (from the HA iosapp devices) and the "iPhone Lory HA New" comes from what HA has loaded as part of the Mobile App Integration devices. iC3 checks to see if the "iPhone Lory", which is in the iC3 config is in the Mobile App devices and it is not, the name is different. That is why it is not monitoring the HA iosapp.
> 
> Do you remember if you originally added it and then renamed it at some time

Yes I did change the entity name to be Iphone Lory HA New instead of Iphone Lory, so the device name in the mobile app integration is still Iphone Lory, but the displayed name for the device tracker entity is renamed (see below screenshot)

![Screenshot_20240207_234637_Home Assistant](https://github.com/gcobb321/icloud3_v3/assets/97987488/2f38746a-e4b6-43d4-800b-09bf3bb03f3a)

**Comment by smarthomefamilyverrips** [comment]
> Here is rc10.3 1.It fixes the Special zones screen error. 2. It loads both of the names (iPhone Lory & iPhone Lory HA New) into the valid tables.
> 
> Unzip it into the icloud3 directory and restart HA.
> 
> [icloud3_v3-rc10.3.zip](https://github.com/gcobb321/icloud3_v3/files/14202023/icloud3_v3-rc10.3.zip)

OK I am trying now

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 this did solve the special config menu issue but it still show mobile app "not used" in event log after restart of HA, AND same as before after manual using the restart icloud action from the drop down menu makes the mobile app change from not used to the zone i am in

[icloud3-event-log_2024.02.08-00.13.10.log](https://github.com/gcobb321/icloud3_v3/files/14202246/icloud3-event-log_2024.02.08-00.13.10.log)



![2024-02-08_00-12-19](https://github.com/gcobb321/icloud3_v3/assets/97987488/766aba19-5430-4c21-a072-1d42115cff09)

![2024-02-08_00-12-42](https://github.com/gcobb321/icloud3_v3/assets/97987488/e0ca8a90-330a-41b5-b750-d9e68fa4b53d)

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 This is how event log looks like after manual restart of Icloudv3 integration by using the restart icloud action from drop down menu. As you can see after restart of integration it is using the MobileApp

![2024-02-08_00-22-38](https://github.com/gcobb321/icloud3_v3/assets/97987488/c6188a31-bf7d-4887-93dc-4ccd5514b343)

![2024-02-08_00-21-50](https://github.com/gcobb321/icloud3_v3/assets/97987488/2db7f7e6-5bf5-4eb9-87e6-db238dd78715)

**Comment by gcobb321** [comment]
I added some other logging that includes the mobile app data to the  icloud3-0.log file.  Can you attach that file or email it to ***@***.***   That might show why it it’s needs a restart.

Gary Cobb, aka geekstergary
________________________________

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 did just mail it to your gmail

**Comment by smarthomefamilyverrips** [comment]
Sounds good to me! Thanks so far and enjoy your diner!

**Comment by smarthomefamilyverrips** [comment]
Hello @gcobb321 

Did you add something to your code in the update you made me try that influence the state/location of the HA MobileApp tracker because now my MobileApp tracker when coming home goes to home/away/home within few seconds. Before I did do the update you did share of iCloudv3 I never had this behavior on the MobileApp device tracker

![Screenshot_20240208_150656_Home Assistant](https://github.com/gcobb321/icloud3_v3/assets/97987488/34a45c6a-c466-4a60-90e5-faff5719bb36)

**Comment by gcobb321** [comment]
The HA mobile app and the icloud famshr location are both being monitored by iC3 and the latest valid one (based on location time and gps accuracy) is used. What you are probably seeing is the mobapp is updated by the HA iosapp, then ic3 updates it with either the same location or the famshr location, then the mobapp is being used again. 

remove the ha mobile app from the person entity since it is being monitored by ic3.

Also, now that the ic3 is using the mobile app, the screenshots of the ic3 event log are going to show what ic3 was doing at the time instead of just the results of a combination of several entities when the person was updated.

**Comment by smarthomefamilyverrips** [comment]
> The HA mobile app and the icloud famshr location are both being monitored by iC3 and the latest valid one (based on location time and gps accuracy) is used. What you are probably seeing is the mobapp is updated by the HA iosapp, then ic3 updates it with either the same location or the famshr location, then the mobapp is being used again.
> 
> remove the ha mobile app from the person entity since it is being monitored by ic3.
> 
> Also, now that the ic3 is using the mobile app, the screenshots of the ic3 event log are going to show what ic3 was doing at the time instead of just the results of a combination of several entities when the person was updated.

@gcobb321 

1. I will also try to remove the MobileApp tracker from the person entity.

2. As stated above I think that the rc.10.3 update did solve the home/away/home and away/home/away issue, to be 100% sure need to test it for some days of course but I believe the update did solve it.

3. The only issue left now is that the iCloudv3 integration not use the MobileApp after a restart of HA, in the Eventlog it shows "not used" only after i do a manual restart of the integration usting the "icloud restart" from drop down menu at event log card it starts to use the MobileApp and it shows the zone I am in instead of "not used"

You think you can find a solution for point 3 also?

**Comment by gcobb321** [comment]
Working on that and several other items. Will send you a new update when ready

**Comment by smarthomefamilyverrips** [comment]
Thank You!

**Comment by gcobb321** [comment]
I looked at the log file you sent in detail late yesterday and found a "Verify Location (Exit Unknown Zone)" trigger that was causing a lot of updates every 20-secs or so. It was processing an Exit Trigger that had already been processed. I have fixed that and will make sure the change does not cause any issues when I run some errands in a little while. I'll send you and update when it is ready later this afternoon.

**Comment by smarthomefamilyverrips** [comment]
> I looked at the log file you sent in detail late yesterday and found a "Verify Location (Exit Unknown Zone)" trigger that was causing a lot of updates every 20-secs or so. It was processing an Exit Trigger that had already been processed. I have fixed that and will make sure the change does not cause any issues when I run some errands in a little while. I'll send you and update when it is ready later this afternoon.
> 
> It also fixes a few other bugs dealing with the iCloud and Mobile App device verification and setup. I found that if there was a problem verifying the FamShr device but it was also using the Mobile App, it would not be tracked at all when it should still be tracked with the Mobile App. I also changed some messaging for Mobile App devices that had been disabled when they were not being used by iCloud3 to just print a mesage instead of a big red X.

Great! I will await the updated version when you are ready!

**Comment by gcobb321** [comment]
Here is a new rc10.3 with the above changes. And a few other things.

Unzip it into the icloud3 directory and restart HA.
[icloud3_v3-rc10.3.zip](https://github.com/gcobb321/icloud3_v3/files/14226969/icloud3_v3-rc10.3.zip)

**Comment by smarthomefamilyverrips** [comment]
> Here is a new rc10.3 with the above changes. And a few other things.
> 
> Unzip it into the icloud3 directory and restart HA. [icloud3_v3-rc10.3.zip](https://github.com/gcobb321/icloud3_v3/files/14226969/icloud3_v3-rc10.3.zip)

@gcobb321 I did install the update and now the integration also use the MobileApp after restart of HA, so that seems solved also. Later when we go out I will check if all tracking functions also still work as expected.

I will keep you posted, Thanks!

**Comment by gcobb321** [comment]
FYI - I uploaded rc10.3 several hours ago. You can get it immediately by going to the GitHub releases page and downloading the icloud3.zip file or waiting for HACS to do the update tonight. You may also be able to refresh HACS by going to it, selecting the 3-dots in the upper right corner and refreshing the information.

And thanks for the coffee. I appreciate it.

**Comment by smarthomefamilyverrips** [comment]
> FYI - I uploaded rc10.3 several hours ago. You can get it immediately by going to the GitHub releases page and downloading the icloud3.zip file or waiting for HACS to do the update tonight. You may also be able to refresh HACS by going to it, selecting the 3-dots in the upper right corner and refreshing the information.
> 
> And thanks for the coffee. I appreciate it.

@gcobb321 I just did updated through HACS, is it the same version as you shared with me already 2 days ago or you still made some changes? 

And you are welcome for the coffee, am happy you go through the effort to help me solve my issues 😊

**Comment by gcobb321** [comment]
It has other changes that I finished this morning that made the log files easier to see what was going on  (exported _Event Log_ and icloud3-0.log).

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
