### ISSUE TITLE
Icons after 2024.2.0

### ISSUE THREAD

**Issue by bkr1969** [gcobb321/icloud3_v3#269]
A lot of the integration icons were not coming up after the last core update.  Everything seems fine now except this one. i.e. for my battery state, I used to get a battery icon that was colored and changed based on the percentage.  Now it's just a mdi:battery-unknown icon, no color or percentage changes.

**Comment by smarthomefamilyverrips** [comment]
https://developers.home-assistant.io/blog/2024/01/30/ha-state-icon-properties-changes/

**Comment by gcobb321** [comment]
My battery icons are still showing the changes in color and level as the battery level goes down. Does the mobile app battery level also fail for you when you add it to a Lovelace card? The icon that is displayed is an attribute of the battery entity that can be seen on the HA Developer Tools >States screen.

**Comment by smarthomefamilyverrips** [comment]
@bkr1969 Maybe is as simple as clearing your cache?

**Comment by bkr1969** [comment]
My fault.  Seems it's not this integration with the problem.  The icons are all fine when viewing them normally.  The problem is that I only use them in battery-state cards, which seems to be causing the problem.
