### ISSUE TITLE
Battery sensors for FmF devices

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#27]
When setting up an FmF device, it creates the sensor entities for Battery and BatteryStatus, even though this info isn't available for FmF devices.

I tried disabling these entities, but they seem to be re-enabled later.

Can we either have the ability to disable them and keep them disabled, or not create them in the first place if it's an FmF device?

Thanks

**Comment by gcobb321** [comment]
That is probably going to be difficult to do and would require a lot more checking to determine if and when to create (and delete) the battery sensor. Expecially when adding the FmF entry to the device or deleteing the FamShr or iOS App parameter.

A much easier solution might be to just disable the sensor on the Devices & Settings > Entities screen for that sensor. And you can hide or show disabled sensors. I'm in the middle of chasing down some other issues so can not try it myself right now.

**Comment by derekoharrow** [comment]
I've tried disabling the battery entities for the 2 FmF devices, but they are re-enabled on HA restart.
