### ISSUE TITLE
Disable phone calls

### ISSUE THREAD

**Issue by CH1PSET1** [gcobb321/icloud3_v3#271]
Good afternoon. Tell me, when I’m at home, the integration calls to the phone approximately every 2 hours, but when I leave the house, it happens every minute, because of this the phone quickly dies. Is it possible to set some settings to make calls to the phone less frequent or turn it off altogether?

**Comment by JtwoA** [comment]
I presume by "calls" you don't mean actual phone calls but pings.  Working from that presumption, do you have the HA app on your phone?

**Comment by CH1PSET1** [comment]
> I presume by "calls" you don't mean actual phone calls but pings. Working from that presumption, do you have the HA app on your phone?

That's right. Pings. HA is also present.

**Comment by gcobb321** [comment]
What version are you running? I did find a problem with rc10.2 when you get an Exit Trigger and you were not in a zone. It was relocation every 20-30 secs. This has been fixed in rc10.3 that I uploaded several hours ago.

You can get it immediately by going to the GitHub releases page and downloading the icloud3.zip file or waiting for HACS to do the update tonight. You may also be able to refresh HACS by going to it, selecting the 3-dots in the upper right corner and refreshing the information.

**Comment by CH1PSET1** [comment]
> What version are you running? I did find a problem with rc10.2 when you get an Exit Trigger and you were not in a zone. It was relocation every 20-30 secs. This has been fixed in rc10.3 that I uploaded several hours ago.
> 
> You can get it immediately by going to the GitHub releases page and downloading the icloud3.zip file or waiting for HACS to do the update tonight. You may also be able to refresh HACS by going to it, selecting the 3-dots in the upper right corner and refreshing the information.

Yes, I will definitely update today, but nevertheless, I would like to know how I can set the settings in the integration configuration so that icloud3 accesses my device as rarely as possible, no matter if I’m at home or not.

**Comment by gcobb321** [comment]
You can set the inZone and Fixed Interval parameters on the _Configure Settings > Update Devices_ screen to its max value (480-minutes) to limit the iCloud location requests that are done. The Mobile App, if you use it, will still issue its update triggers on a r regular basis. You may have to set the Max Alive and several other interval values on the _Configure Settings > Update Parameters Menu > Other Tracking Parameters_ screen.
