### ISSUE TITLE
Question: What exactly is the iCloud Family Sharing device setting

### ISSUE THREAD

**Issue by Menz01** [gcobb321/icloud3_v3#277]
What exactly is the iCloud Family Sharing device setting? if i setup 3 different devices should they all have the same family sharing device setting or should they all have their own individual family sharing device (itself)?  i just am trying to understand what this setting actually does.

Thanks

**Comment by gcobb321** [comment]
See iCloud3 User Guide [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.1-icloud-account)

**Comment by gcobb321** [comment]
Closing this issue with the release of v3.0
