### ISSUE TITLE
iCloud3 v3.0 Release Version Uploaded (2/26/2024)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#278]
### iCloud3 v3.0 is now available for general use.

**This is the final version. There are no more release candidates.**

Thanks for all the help while I worked through getting the new version of iCloud3 up and running.

It was a rewrite of iCloud3 v2 to bring it up to date, add a lot of new features, support the latest version of Home Assistant, become an Integration with on-line configuration and provide a path for adding new features..

For those that are interested, iCloud3 contains 33,002 lines of code, which is a lot of code. For comparison, the HA iCloud Integration is 1445 lines. It took over 2-years to write and was in beta/release candidate state for another 1-year.  

It was a fun project but I am glad to wrap it up. Hopefully, you will find it useful.

Thanks again for the help.

Gary

**Comment by gcobb321** [comment]
@biggeeus @confusedsecuritydudes @chupacabra71 @chr04213 @criticallimit @daneboom @denac @derekoharrow @diothar @DerDon1302

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks

**Comment by gcobb321** [comment]
@ihf1 @JtwoA @J-Fartz @joselito1 @japyjaap @kalkocz @kamkilt @kingy444 @lukkigi @wgumaa

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@marceloaf @MarkGardiner @marting @mobiledude @myMartek @morrisonpeter @Nuuki9 @pauly7300 @poudenes @polskikrol

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3 @stevekuchta @townsmcp @tm24fan8 @t077584

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@u20p17 @umrath @ADHawk @alams154 @bastero @Ben82cgn @billraff @BruceH5200

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@Camille2906 @ChileHA @crankycowboy @DerekO @dirsve @dneubauer09 @eastern_blok @eBoon @engeles20 @ersilb

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@FinestDice17 @Hans_van_der_Drift @igadgetman @jchh @jeja @jlambert121 @Kasek @kohlep0a @lhf1

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by gcobb321** [comment]
@MartinG @michaelthompson1991 @NCO3 @p1ne @relout @shmookles @smart-ctrl @spry-salt @STATERA @ts2340

See this announcement about [iCloud3 v3 is released for General Availability](https://github.com/gcobb321/icloud3_v3/issues/278)

Thanks,
Gary

**Comment by michaelthompson1991** [comment]
So if it's the final version do we need to uninstall and install anything now?

**Comment by gcobb321** [comment]
No. Wait for HACS or download the zip file, unzip it into the icloud3 directory and restart HA. It’s no different than installing one of the release candidate versions.

**Comment by michaelthompson1991** [comment]
No problem, thanks! I'll wait for HACS 👍🏻

**Comment by Nuuki9** [comment]
Just showed up for me in HACS. Am I right to assume I can repo the development repo once the upgrade is done?

**Comment by gcobb321** [comment]
@
Sure. Everything there is current

**Comment by NCO3** [comment]
Thank you very much, @gcobb321 that’s  awesome stuff and I really appreciate your effort.
👍🏻

**Comment by andyblac** [comment]
> Just showed up for me in HACS. Am I right to assume I can repo the development repo once the upgrade is done?
> 

hmm, not showing me, still only showing rc10.4 ??

<img width="573" alt="Screenshot 2024-02-27 at 16 48 08" src="https://github.com/gcobb321/icloud3_v3/assets/77936/3f979a56-307b-4220-99eb-53b00df0f8cb">

**Comment by FredWst** [comment]
Hi,

I got same issue with HACS official repos. it only show release candidate 4.

I added custom github see below  gcobb321/icloud3_v3 to get last version. (just like doc)

![image](https://github.com/gcobb321/icloud3_v3/assets/41281764/386a2233-fb4f-44b7-880c-50500c843df3)

![image](https://github.com/gcobb321/icloud3_v3/assets/41281764/63f0eddf-0063-476d-9a0c-90101c6024b6)

Fred

**Comment by gcobb321** [comment]
I have not released it to the official HACS yet as a prerelease. I wanted to make sure there was nothing that came up at the last m minute. Once everything looks real good and has been downloaded a bunch of times, I’ll update the base HACS as the current release.

**Comment by RealGandy** [comment]
Congrats on getting this out the door - the work you've put into this over the past couple of years is phenomenal. 

Massive massive thank you.
