### ISSUE TITLE
Errors updating devices

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#28]
In the Integration menu, I'm going into ICLOUD3 DEVICES to edit my devices. When I do I get this in the HASS log:

```
2023-01-13 17:29:38.714 ERROR (MainThread) [icloud3] list index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/config_flow.py", line 2329, in _build_opt_picture_filename_list
    if file.rsplit('.', 1)[1] in image_extensions:
IndexError: list index out of range
```

When on the device screen, I'm seeing the message:

`Check the FamShr, FmF, iOS App or Picture parameter value (Not found or Invalid). Reset to `None``

However, everything is setup as it's supposed to be - iOS App, FmF and FamShr are all set correctly. Changing them and saving again doesn't seem to make any difference.

**Comment by gcobb321** [comment]
Do you have any image files (png,j pg) in the /www directory or it's sub-directories (www/icloud3, www/custom_components, etc)? I can not remember running this with no image files.

Thanks

**Comment by derekoharrow** [comment]
I have a www/images folder with some JPGs in.
I don't have a www/icloud3 or www/custom_components folder

**Comment by gcobb321** [comment]
Try beta 8. I made a few changes that I think may fix the problem. I'll close this for now but reopen it if you still have an issue.
