### ISSUE TITLE
Need Help to Add More Zones, Work, Paren'ts House, etc.

### ISSUE THREAD

**Issue by royf007** [gcobb321/icloud3_v3#280]
First of, let me say, this is fantastic integration with really amazing documentation.  I'm struggling how to figure out how to add more zones, i.e. work, parent's house, etc with friendly names.

Where can I create more zones...so if I'm currently at work, can I define a zone with my current location?

**Comment by JtwoA** [comment]
You would do this in Home Assistant > Settings > Areas & Zones

![image](https://github.com/gcobb321/icloud3_v3/assets/12992040/f4301f68-b51c-476b-bcd5-bd82851b963d)

**Comment by gcobb321** [comment]
John, that is the thing to do. Zone changes will be picked up automatically by iCloud3 when they are made. That is what a zone is for. I have a bunch of them set up.

**Comment by royf007** [comment]
Thank you! It works. I’m new to Home Assistant

**Comment by royf007** [comment]
Thank you! It works. I’m new to Home Assistant.
