### ISSUE TITLE
 "Find My" app from Apple to be activated in iCloud for family members?

### ISSUE THREAD

**Issue by fight3** [gcobb321/icloud3_v3#285]
Hi, is it absolutely necessary for the "Find My" app from Apple to be activated in iCloud for family members?

**Comment by gcobb321** [comment]
A device must be sharing its location info to be tracked. Below are the settings that need to be enabled. See the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/8.3-tracking-issues) for more info. 

Settings App > Privacy & Security

Locations Services is Enabled
Share My Location >
- Find My iPhone is Enabled
- Share My Location is Enabled
Family > This shows the Family members this device can see in the FindMy app. Make sure all the people you are tracking with iCloud3 are listed. This does not list each device for the Family member, just the person.
