### ISSUE TITLE
iCloud3 v3.0.2 (3.30.2024) has been released

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#292]
Go to the Releases page [here](https://github.com/gcobb321/icloud3_v3/releases) if you want it right now. Download the zip file, unzip it into the icloud3 directory, restart HA and enjoy.
--or--
Get it from HACS

### Important Links:
- iCloud3 v3 Documentation is [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/0.1-introduction)
- The *Installing iCloud3* chapter describes migrating from iCloud3 v2 and installing iCloud3 for the first time

### Change Log
1. ICLOUD SERVER ERROR MESSAGE (Fixed) - When the iCloud servers did not respond with location information, the 'no response from iCloud servers' error was displayed correctly. This was followed by another unrelated error which should have not been displayed.
2. ALERTS, STARTUP ERRORS, WARNING MESSAGES (New) - Unusual errors or warning events for iPhones, iPads, and Watches are displayed in a green bar on the first line of the Event Log when the event occurs. The message will continue displaying until the event is corrected. This includes (1) startup errors, (2) no data received from iCloud Location Servers, (3) when a device is offline, (4) when a device's location is over 5-hours old and (5) when tracking is paused. The messages from AirPods and iPods are only displayed when their Event Log screen is displayed. See the *Event Log* chapter in iCloud3 documentation for more information.
3. OTHER - Minor code corrections and cleanup.

**Comment by d13g0m0nt3s** [comment]
Hi, i do not know if only me but the update never finish is stuck installing. i reboot HA but same problem

**Comment by marceloaf** [comment]
It’s the same to me. I went to GitHub and downloaded the .zip instead

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: d13g0m0nt3s ***@***.***>
Enviado: Saturday, March 30, 2024 3:58:30 PM
Para: gcobb321/icloud3_v3 ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [gcobb321/icloud3_v3] iCloud3 v3.0.2 (3.30.2024) has been released (Issue #292)


Hi, i do not know if only me but the update never finish is stuck installing. i reboot HA but same problem

**Comment by wolfgangdenthaner** [comment]
Failing Update through HACS too

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 232, in hacs_repository_download
    await repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No manifest.json file found 'custom_components/None/manifest.json'

**Comment by gcobb321** [comment]
I guess I deleted the icloud3_v3/custom_components/icloud3 directory instead of updating it with the new stuff. It is out there now. Can someone try to download it using HACS again to see if it works this time.

**Comment by marceloaf** [comment]
At least for me it still didn’t work, even after a restart.

Although the version shown is 3.0.2, it is greyed out and you can’t see the other versions.



Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Gary Cobb ***@***.***>
Enviado: Saturday, March 30, 2024 6:28:42 PM
Para: gcobb321/icloud3_v3 ***@***.***>
Cc: marceloaf ***@***.***>; Comment ***@***.***>
Assunto: Re: [gcobb321/icloud3_v3] iCloud3 v3.0.2 (3.30.2024) has been released (Issue #292)


I guess I deleted the icloud3_v3/custom_components/icloud3 directory instead of updating it with the new stuff. It is out there now. Can someone try to download it using HACS again to see if it works this time.

**Comment by gcobb321** [comment]
All set now. The first Rerelease on GitHub wasn't saved. I created it again, just ran it through HACS and all went OK. It shows up as Release v3.0.2a
