### ISSUE TITLE
Old Apple iCloud passwords seem to be cached 

### ISSUE THREAD

**Issue by NR3Y** [gcobb321/icloud3_v3#295]
I recently changed my Apple iCloud password after I thought it was compromised.

I updated configuration.yaml with the new password and I thought that was it, until I upgraded HA Core and HA was restarted. After some time, I was wondering why some of my location-based automation were not executing, until I checked the iCloud3 log and found out it was reporting a log-on error because it was using my old password. I then had to go through the process of re configuring iCloud3 to use the new password - something I would have expected it to pick up from configuration.yaml on the restart.

Given that my automation silently failed, I would request that if iCloud3 can detect such an error condition, that it somehow set a boolean flag that can trigger a new automation to notify the user of a problem, rather than simply throwing an error message in the log and hoping it gets read sometime.

Thanks.

**Comment by gcobb321** [comment]
I assume you are running v2 if you are using the configuration.yaml file. iCloud3 v3 has been available as a prerelease for a while and all development is being done for v3. You might want to take a look at the docs for v3 [here](https://gcobb321.github.io/icloud3_v3_docs/#/).

There are some alerts in the attribute settings for the device_tracker entity, along with many other new features. v3.0.3 is soon to be released and will be released as the latest version, not a prerelease version. One of the alerts is a 'Startup Error' that indicates there was a problem/issue/error encountered when iCloud3 was starting. 

Watch for that version

**Comment by NR3Y** [comment]
I'm running 3.0.2. So, does that mean I can remove the entries in configuration.yaml? (That would be great, as there would be less clutter in there.)

Good news on 'start up error'. If I can trigger automation (to notify my phone and display a popup warning on my home dashboard) when it fails, that would be great.

Thanks

**Comment by gcobb321** [comment]
Dump everything in the configuration.yaml related to iCloud3. v3 is an integration and configured from the Devices & settings > iCloud3 > Configure. Or use the shortcut gear icon  on the Event Log. The password is changed on the _Configure Settings > iCloud Account and Mobile App_ screen.

I'm doing some changes to that screen to better handle switching iCloud Accounts to a new username/password. Once that is done, I'll release v3.0.3.

**Comment by NR3Y** [comment]
Perfect, thanks. I'll wait for V3.0.3
