### ISSUE TITLE
MobileAPP location overrides FamShr

### ISSUE THREAD

**Issue by nosar77** [gcobb321/icloud3_v3#301]
Ive consistently had issues with the iphone 14 pro max my wife has and the built in mobile app device tracker, often times it would never update the location enough and often it wouldn't update for 12 hours plus. Now , with Icloud 3 im having a similar issues, it seems the FamShr icloud location is always up to date but the mobileapp overrides the location very so often with the mobile app location which is never correct even though i set up the always use GPS precise location in the background etc. 

Is there a way to make icloud3 only get locations from the FamShr as it is always accurate. Is there some setting that I missed during setup on her phone that would make it work incorrectly? Its very annoying to never have accurate location data. Is there a way to force the mobileapp tracking to be faster and more accurate on iphone? I have no issues  tracking with the mobile app on my Galaxy S23.

**Comment by gcobb321** [comment]
My wife and i have iPhone 14 Pros 9not the Max) and have had not had the location issues you are having. However, the Companion App on the device controls the type of events that are triggered. You might want to turn all of them off (except one Enter/Exit) and see if that helps. This is done on the iPhone > HA App > Settings > Companion App > Location tab.

**Comment by nosar77** [comment]
I'll check the settings on her phone. It's not even just the triggers it seems ever so often icloud3 updates her location with the mobile app and then teleports her to our home zone even when she's not there and then the next update shows her away from the house and it keeps going back and forth. Would a log help? Diagnose

**Comment by gcobb321** [comment]
iCloud3 is using the location data it gets from the mobile app if the state value or trigger is newer than the FamShr location data. It does not know if it is wrong or bad data but just uses what it gets. 

You could turn on log_level debug (Event Log > Actions) and send me the iCloud3-0.log file. Also do an Event Log > Actions > Export Event Log and send me that too. 

Let me know what time all of this occurs so I know where to look.
I assume you are on v3.0.4 which I just released. If not, install that version and go from there.
