### ISSUE TITLE
I don't get my watch integrated because I can't find it anywhere

### ISSUE THREAD

**Issue by Friedi1970** [gcobb321/icloud3_v3#303]
Hi and thanks for this great integration which works great for my iPhones (where I installed the IOS app of HA). Anyway, I don't get my watch integrated because I can't find it anywhere since the FAMILY SHARING LIST DEVICE is empty.

Is there a way to add devices like watch, ipods and all those devices where no HA app is installed?

Another weird problem I have is that I always get the following error:
Error, The Mobile App Integration is not installed. The Mobile App will not be used as a data source; location data and zone enter/exit triggers will not be monitored

The mobile app is installed - of course -, so what does this error message mean?

> @Friedi1970 Go to Configure Settings > Enter/Request Verification Code screen and request a new c code. Enter it and then restart iCloud3 with Event Log > Actions > Restart iCloud3 and see if anything is returned from iCloud.

I requested as you described. The problem is I don’t get any code …

**Comment by gcobb321** [comment]
The Event Log is described in the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/1.2-event-log)

**Comment by Friedi1970** [comment]
OK, got it but the rest of the problem still exists. Not verification code and no devices without installed mobile HA app.

**Comment by Friedi1970** [comment]
Seems, it is solved by I don‘t know who ;) Anyway, it works now.
