### ISSUE TITLE
Icloud3 arrival time

### ISSUE THREAD

**Issue by rkpollack** [gcobb321/icloud3_v3#307]
Sensor for arrival time is 3 hours later. See below. I haven’t figured out how to fix this?

![IMG_2238](https://github.com/gcobb321/icloud3_v3/assets/24683079/f595c34a-3b57-4cc9-941c-bb54d8110105)

**Comment by gcobb321** [comment]
What is also strange is the Event Time is 6:01a, the interval is 2 hrs and the next update is at 11:01a. Check the time zone in the HA settings and on your HA server. Also check the update times of other components to see if they are off to.

**Comment by corruptmods** [comment]
Im having the same issue. My time is off by 5 hours. Server, home assistant, etc are all set to the proper time zone.

**Comment by gcobb321** [comment]
@corruptmods
Does the time on the _Event Log_ line plus the interval time equal the arrival time or do they all look ok? Are you tracking from more than one zone or only the Home zone?

**Comment by gcobb321** [comment]
Reopen if you are still having this issue
