### ISSUE TITLE
Can't update Route Server Location

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#31]
Can't change the Waze Route Server location for my location (Brazil). It keeps saying my correct location is US/Canada. And there is a log stating that no data returned using US/Canada 

![image](https://user-images.githubusercontent.com/11551691/212497510-d5520d83-e7fd-47f2-a376-e03636f65c80.png)

![image](https://user-images.githubusercontent.com/11551691/212497549-e9240b13-ba38-412c-ab67-d74942d30160.png)

**Comment by gcobb321** [comment]
I am using the country code in your HA profile. Is that set to US or Brazil. 

The test is US/CA=US, IL=IL, Everyone else is Rest of the World.

**Comment by marceloaf** [comment]
![image](https://user-images.githubusercontent.com/11551691/212497874-fab479e8-b3f2-4a79-a92c-ccf1e15da189.png)

**Comment by gcobb321** [comment]
Looking at it now

**Comment by gcobb321** [comment]
[icloud3-beta-8.zip](https://github.com/gcobb321/icloud3_v3/files/10418962/icloud3-beta-8.zip)

I think this takes care of the Waze Server. I took out the code that set the server automatically and you can change it again. It displays the country code in Stage 1 of the Event Log and again when it sets up Waze. I did find one spot where it may have been erased and defaulted to 'us' later on.

**Comment by marceloaf** [comment]
> Looking at it now
> 
> Edit: When starting iC3, it looks at the country code and if it finds a mismatch with the waze, it adds a message to home_assistant.log file or the icloud3-debug.log file that shows the country code and the waze server that should be used.
> 
> Do you see any message like this?

Sent you the log files in your email. Just saw the new zip. Will test and report back.

Thanks!
Marcelo

**Comment by gcobb321** [comment]
When you send a thumbs up, I'll put it on GitHub. Thanks for the help.

**Comment by marceloaf** [comment]
I was able to update the region with the new code. I didn't notice any error during icloud3 initialization and was able to see the updated travel time for my devices.

![image](https://user-images.githubusercontent.com/11551691/212500059-1f8cba46-3aa1-4f57-bb25-7a246e95967a.png)

Now I could see in the debug.log a reference to country code US. Don't know why it is thinking i'm in US.... Anyway, it's working now.

![image](https://user-images.githubusercontent.com/11551691/212500112-cfadfff1-ea40-41d7-af0d-a1f031b45a1f.png)

**Comment by marceloaf** [comment]
I have more for you, but tomorrow or on monday! :-)

**Comment by gcobb321** [comment]
Fixed in Beta 8a
