### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by dmcnaugh15** [gcobb321/icloud3_v3#312]
My integration suddenly stopped working a couple days ago.  Wondering if it's just my instance or if others are having the same issue.

INSTALLATION:
HA Core: 2024.7.2
Superviser: 2024.06.2
OS: 12.4
 iCloud3 v3 version: v3.0.5

SCREENSHOT:
![Image 001](https://github.com/user-attachments/assets/c0c350a7-0b7e-4404-8489-ce4b91aed30a)

LOGS:
[home-assistant_2024-07-12T21-18-57.601Z.log](https://github.com/user-attachments/files/16200630/home-assistant_2024-07-12T21-18-57.601Z.log)

**Comment by Kaici433** [comment]
For me the integration also stopped working with OS 12.4

**Comment by JtwoA** [comment]
Or... https://github.com/gcobb321/icloud3_v3/issues/309

**Comment by gcobb321** [comment]
See [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon.

**Comment by dmcnaugh15** [comment]
Thank you!  I applied the temp fix and it works perfectly.

**Comment by gcobb321** [comment]
See [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon.

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.
