### ISSUE TITLE
Not showing in Integration list

### ISSUE THREAD

**Issue by kuturud** [gcobb321/icloud3_v3#313]
I deleted the integration as it was having problems just to re install it but i cannot find it in the add integrations. Ive done everything like manually putting the files back and reinstalling it from hacs rebooting installing older updates but i cant find it

**Comment by gcobb321** [comment]
Make sure iCloud3 has been installed in the _config/custom_components/icloud3_ directory. Then see [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon. 

Hopefully this will get it up and running again.
