### ISSUE TITLE
iCloud3 v3.0.5.5 (7/16/2024) Released

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#314]
### Change Log - v3.0.5.5 (7/16/2024)
1. **ICLOUD3 FAILED TO LOAD** (Fix) - iCloud3 injected special code into the HA history recorder to exclude various sensor entities from being added to the history recorder database. This caused problems with HA in the 2024.7 release.  The HA 2024.7.2 included special code that blocked iCloud3 from loading. A temporary patch was posted on the iCloud3 GitHub repository to disable the recorder injection.
 
    This update fixes this problem. Only sensor attributes  related to the battery, distance and timer sensors are now being added to the HA recorder history. Sensors that are predominantly text based (info sensors, the Event Log sensor, badge, tracking update times, zone, etc.) are not being added. The state value of all sensors are added.

    **NOTE:** The sensor state and attribute values are available on a real time base like they always have. This update only relates to the HA history recorder database.

    **SPECIAL NOTE**: If you get an HA error that a sensor attribute is not available, create an issue on the iCloud3 GitHub repository. Let me know the sensor name and attribute name that is causing the error. I will remove it from the exclusion list in the next update.

### Important Links:
**Migrating from v2.4.7_** - See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.1-migrating-v2-to-v3) for instructions on migrating from from an older version.
**Installing for the first time_** - See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring) for instructions on installing as a New Installation
**iCloud3 v3 Documentation** - iCloud3 User Guide can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)

**Comment by johndoe0815** [comment]
Just updated, after restart icloud 3 again fails to start. Could it be that you missed to increase the version number in the manifest?
I had manually added that to 3.0.5.3, after your update it was set back to 3.0.5.2.

![grafik](https://github.com/user-attachments/assets/3146637c-63c0-4307-889f-fbde582df611)

**Comment by gcobb321** [comment]
HACS was the problem. It was downloading the v3.0.5.2 release, not the v3.0.5.5 release even though the zip file for the release was correct and the files were correct. I will create a new release and see what happens.

Here is the v3.0.5.5 zip file.
[icloud3.zip](https://github.com/user-attachments/files/16253192/icloud3.zip)

**Comment by gcobb321** [comment]
It was my error. I did everything except update the _custom_components/icloud3_ code files on the GitHub repository so it was picking up v3.0.5.2 code instead. 

All is good now. HACS updates the files  with the v3.0.5.5 version after refreshing via the _Update Information_ option.

**Comment by Friedi1970** [comment]
@gcobb321 one question. When the new version is installed will it still blocked in 2024.7.2 or not?

**Comment by gcobb321** [comment]
No. It will load and run without any issues.
