### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3_v3#315]
I just installed v3.0.5.5 (7/16/2024) and then upgraded to 2024.7.2 and now ic3 does not load. Errors below

```
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
First occurred: 11:11:25 AM (1 occurrences)
Last logged: 11:11:25 AM

Failed to load integration for translation: Integration 'icloud3' not found.
```

```
Logger: homeassistant.setup
Source: setup.py:271
First occurred: 11:11:26 AM (1 occurrences)
Last logged: 11:11:26 AM

Setup failed for 'icloud3': Integration not found.
```

**Comment by broyuken** [comment]
manifest.json still shows 3.0.5.2, could that be the issue?

**Comment by broyuken** [comment]
I manually downloaded/installed it and it works.

Hacs was saying that 3.0.5.5 was available and selectable in the download list but I guess it was still downloading .2. Might need to fix that before other people break their installs

**Comment by gcobb321** [comment]
HACS was the problem. It was downloading the v3.0.5.2 release, not the v3.0.5.5 release even though the zip file for the release was correct and the files were correct. I will create a new release and see what happens.

Here is the v3.0.5.5 zip file.
[icloud3.zip](https://github.com/user-attachments/files/16253192/icloud3.zip)

**Comment by gcobb321** [comment]
It was my error. I did everything except update the _custom_components/icloud3_ code files on the GitHub repository so it was picking up v3.0.5.2 code instead. 

All is good now. HACS updates the files  with the v3.0.5.5 version after refreshing via the _Update Information_ option.
