### ISSUE TITLE
Errors Starting iCloud3

### ISSUE THREAD

**Issue by ShadowTakker** [gcobb321/icloud3_v3#318]
Error: The following issues were detected when starting iCloud3. Scroll through the Startup Log for more information: 1. Waze History > Home Zone has moved and will not be use

I can't find anything in a startup log after I exported it. Has anyone had a similar issue and know how to resolve? Only just started showing up in my iCloud Event Log Dashboard page. Thanks.

![image](https://github.com/user-attachments/assets/867c4578-e1bd-40bc-83a9-ce7b3d8c0701)

**Comment by gcobb321** [comment]
The message may be misleading and be using a generic first sentence. The Waze route time and distance from home is stored in a database to minimize the internet delays getting that info when you are driving close to Home.  The Home gps location that was used is stored in the Waze History database and would be wrong if the Home gps was moved. Normally, this would be recalculated at midnight when this happens. A message will be in the _Event Log_ around midnight if it was. You can manually request this by Selecting _Event Log > Actions > WazeHist-Recalculate Route Time/Dist_ to verify t the time and distance values from all of the location points in the Waze History database to schedule it to run. Select that again to run immediately. It may take some time if you have a large database but runs in the background so iCloud3 will still track your devices when it is running.

**Comment by ShadowTakker** [comment]
Ok awesome. Thanks for the quick response. 
Yes everything else is working, so will give a shot as you've mentioned, and won't worry about it if it pops up again.

**Comment by ShadowTakker** [comment]
Just confirming all sorted, no more error. 
Thanks again.
