### ISSUE TITLE
Phone Charging State

### ISSUE THREAD

**Issue by bkr1969** [gcobb321/icloud3_v3#319]
How often is this status polled (and can we change it)?  During the day at work my status updates nearly instantly when charging or disconnecting, but at home at night (when I want to trigger an automation when I charge my phone) the state never seems to update so my automation doesn't run.  Am I missing something or is there a more reliable way to get the charging state?

**Comment by gcobb321** [comment]
When you are in a zone, the polling interval it’s based on the _inzone interval_ value on the _Configure Settings > Update Devices_ screen screen for each device. That defaults to 2-hours so it will pool for the location update every 2-hours. The Mobile App also reports the value when it changes. However, when the phone goes into sleep mode, the Mobile App does too so it can not post a change. The only thing you can do is to reduce the _inzone interval_ value.

**Comment by JtwoA** [comment]
I've created an automation in iOS Shortcuts that refreshes the sensors upon connecting to power.  This solves that issue for me.

**Comment by bkr1969** [comment]
Excellent idea with the Shortcut.  Just did the same to try to improve accuracy.  Thanks!
