### ISSUE TITLE
Error configuring sensors

### ISSUE THREAD

**Issue by bbobrian** [gcobb321/icloud3_v3#320]
When trying to configure sensors, if any option is selected it will show an error on save:
Unknown error occurred

I believe this is the problem in the logs:
  File "/config/custom_components/icloud3/config_flow.py", line 3866, in _create_sensor_entity
    ic3_sensor._setup_recorder_exclude_sensor_filter(NewSensors)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.icloud3.sensor' has no attribute '_setup_recorder_exclude_sensor_filter'

**Comment by gcobb321** [comment]
Fixed in iCloud3 v3.0.5.6
