### ISSUE TITLE
HA 2024.7.4 CREATES PROBLEMS WITH ICLOUD3

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#321]
The 2024.7.4 HA update causes problems that I think are related to getting data from the Apple iCloud Account. 

This stops iCloud3 from tracking devices since it can not get location data and creates error adding and updating devices on the configuration screens since the devices in the Family Sharing account are not known.

Stay tuned...

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 does this also counts for 2024.8?

**Comment by gcobb321** [comment]
iCloud3 works fine with HA 2024.8

**Comment by smarthomefamilyverrips** [comment]
> iCloud3 works fine with HA 2024.8

OK thanks @gcobb321 then I know is safe to update to 2024.8 (at least regarding the icloud integration) 😀
