### ISSUE TITLE
ICloud 3 and Home Assistant encounter issues after upgrading to the latest version

### ISSUE THREAD

**Issue by siri10086** [gcobb321/icloud3_v3#323]
iCloud3 v3：3.0.5.6
Home Assistant Core:2024.7.3 Frontend :20240710.0
The error after upgrading is as follows. Deleting, uninstalling, and restarting all data will still result in the same error.

Check FamShr and image parameter values (not found or invalid)

When iCloud 3 starts, no FamShr device is returned from iCloud. Check the FindMy device list and home sharing list. View the event logs of Startup Stage 4 for more information and the list of devices returned from iCloud accounts

The image file name was not found in the HA config/www directory. Choose a new file name or check if it has been deleted

The value of this parameter in the iCloud 3 configuration file is unknown or invalid. Must reselect

[['Debug', '^i^iCloud3 v3.0.5.6 > Start up Complete'], ['4:08:41p', 'Requesting Initial Locate'], ['4:08:41p', '^a^The following issues were detected when starting iCloud3. Scroll through the Startup Log for more information: ⣇1. iCloud3 Integration not set up'], ['Debug', '^g^Stage 5 > Device Configuration Summary'], ['Debug', '^g^ Stage 4 > Setup iCloud & MobApp Data Source'], ['4:08:40p', 'Mobile App Devices > 0 of 0 used by iCloud3⣇⠋×⠉Macde Macbook Pro(?), macde_macbook_pro >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)⣇⠋×⠉Iphonebin 2(?), iphonebin_2 >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)⣇⠋×⠉Ipad Mini(?), ipad_mini >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)⣇⠋×⠉Iphone11Pro 2(?), iphone11pro_2 >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)⣇⠋×⠉Iphone11Pro Me(?), iphone11pro_me >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)⣇⠋×⠉Ipad Pro(?), ipad_pro >⣇⠛⠛◦⠈Not Assigned to an iCloud3 Device (Disabled)'], ['4:08:40p', 'iCloud Location Service interface > Verified (startup)'], ['4:08:40p', 'iCloud Location Service interface > Verified (initial)'], ['4:08:37p', 'iCloud Web Server URL Country Suffix > .cn'], ['4:08:37p', 'iCloud Account > Logging Into- (10........@qq....)'], ['Debug', '^g^Stage 3 > Prepare Configured Devices'], ['4:08:37p', 'Data Sources > FamShr, MobApp'], ['4:08:37p', '^a^CONFIGURATION ALERT > DEVICES MUST BE SET UP TO ENABLE TRACKING⣇⣇1. Select `Settings > Devices & Services > Integrations`⣇2. Select `+Add Integration` to add the iCloud3 integration if it is not dislayed. Then search for `iCloud3`, select it and complete the installation.⣇3. Select `iCloud3 > Configuration` to open iCloud3 Configure Settings screens.⣇4. Review and setup the `iCloud Account` and `Update Devices` configuration screens.⣇5. Exit the configurator and `Restart iCloud3`.'], ['Debug', '^g^Stage 2 > Prepare Support Services'], ['4:08:37p', 'Waze History Database > /config/.storage/icloud3/waze_location_history.db'], ['4:08:37p', 'Set Up Waze > Server-United States, Canada (US), CountryCode-CN, MinDist-1km, MaxDist-1000km, Realtime-False, HistoryDatabaseUsed-True'], ['4:08:37p', 'Special Zone Setup >⣇⠋•⠉Enter Zone Delay > DelayTime-30 secs⣇⠋•⠉Stationary Zone > Radius-100m, DistMoveLimit-125m, MinDistFromAnotherZone-200m'], ['4:08:37p', 'Set up Zones > zone, Display (fname)⣇⠋•⠉gong_si, 公司 (r42m/137.8ft)⣇⠋•⠉li_zhi_xiao_xue, 砺志小学 (r56m/183.7ft)⣇⠋•⠉xiao_tian_e, 小天鹅 (r49m/160.8ft)⣇⠋•⠉yi_dong, 家里 (r20m/65.6ft)⣇⠋•⠉home, 复地 (r100m/328.1ft)'], ['Debug', '^g^Stage 1 > Initial Preparations'], ['4:08:37p', 'Local Time Zone Offset > UTC+08:00 hrs, CST, Country Code-CN'], ['4:08:37p', 'iCloud3 Event Log > ⣇⠋•⠉Current Version Installed-v3.0.17⣇⠋•⠉File-/config/www/icloud3/icloud3-event-log-card.js'], ['4:08:37p', 'iCloud3 Configuration File > /config/.storage/icloud3/configuration'], ['4:08:37p', 'iCloud3 Directory > /config/custom_components/icloud3'], ['4:08:37p', 'Configure iCloud3 Operations >⣇⠋•⠉Load configuration parameters⣇⠋•⠉Set Display Text As Fields (0 used)⣇⠋•⠉Set Default Tracking Method (iCloud)⣇⠋•⠉Initialize Debug Control (debug-auto-reset)⣇⠋•⠉Set Unit of Measure Formats (mi)⣇⠋•⠉Set Event Log Record Limits (1500 Events)⣇⠋•⠉Device Tracker State Value Source ⣇⠿⠿(iCloud3 Zone Friendly Name)'], ['4:08:37p', 'Waze History Database > /config/.storage/icloud3/waze_location_history.db'], ['4:08:37p', 'Set Up Waze > Server-United States, Canada (US), CountryCode-CN, MinDist-1km, MaxDist-1000km, Realtime-False, HistoryDatabaseUsed-True'], ['4:08:36p', 'iCloud Web Server URL Country Suffix > .cn'], ['4:08:35p', 'Start iCloud Account Session Executor Job'], ['4:08:35p', 'Start iCloud3 Services Executor Job'], ['4:08:35p', 'Start HA Startup/Stop Listeners'], ['4:08:35p', 'Configure iCloud3 Operations >⣇⠋•⠉Load configuration parameters⣇⠋•⠉Set Display Text As Fields (0 used)⣇⠋•⠉Set Default Tracking Method (iCloud)⣇⠋•⠉Initialize Debug Control (debug-auto-reset)⣇⠋•⠉Set Unit of Measure Formats (mi)⣇⠋•⠉Set Event Log Record Limits (1500 Events)⣇⠋•⠉Device Tracker State Value Source ⣇⠿⠿(iCloud3 Zone Friendly Name)'], ['4:08:35p', 'Waze History Database > /config/.storage/icloud3/waze_location_history.db'], ['4:08:35p', 'Set Up Waze > Server-United States, Canada (US), CountryCode-CN, MinDist-1km, MaxDist-1000km, Realtime-False, HistoryDatabaseUsed-True'], ['Debug', '^i^iCloud3 v3.0.5.6 > Starting, Wednesday, Jul 31'], ['00:00:00', 'Control Record']

**Comment by siri10086** [comment]
[icloud3-0.log](https://github.com/user-attachments/files/16438445/icloud3-0.log)
log

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.7 appears to be working under HA 2024.7.4/HAOS 12.4

The zip file below contains an update to iCloud3 v3. I have not released it yet but would like you to try it to make sure there are no other issues I need to look at. Let me know if it now works. TThanks.

Gary

Unzip icloud3 v3.0.5.7 into the _config/custom_components/icloud3_ directory and restart HA.

[icloud3 v3.0.5.7.zip](https://github.com/user-attachments/files/16442898/icloud3.v3.0.5.7.zip)

**Comment by siri10086** [comment]
> iCloud3 v3.0.5.7 似乎在 HA 2024.7.4/HAOS 12.4 下运行
> 
> 下面的zip文件包含iCloud3 v3的更新。我尚未发布它，但希望您尝试一下，以确保没有其他需要我查看的问题。如果它现在有效，请告诉我。谢谢。
> 
> 加里
> 
> 将 icloud3 v3.0.5.7 解压到_config/custom_components/icloud3_目录并重新启动HA。
> 
> [icloud3 v3.0.5.7.zip](https://github.com/user-attachments/files/16442898/icloud3.v3.0.5.7.zip)

Okay, I'll give it a try. Thank you

**Comment by SvnH1s** [comment]
> Unzip icloud3 v3.0.5.7 into the _config/custom_components/icloud3_ directory and restart HA.

I have had the same issue. v3.0.5.7 works for me. No problems so far.

**Comment by gcobb321** [comment]
@siri10086 It looks like the iCloud device is correctly linked to the iCloud3 device. But you have me_iphone (icloud3 name) linked to iPhonewjx that is listed as ma. It could be the translation.

Go back into the Configuration Update Devices, verify each one, make some change (inzone interval so it will do an update) and Save. Then put the inzone interval back to what it was and save again. Exit and let iCloud3 restart. Then restart HA to get a new iCloud login in and see what happens.

**Comment by siri10086** [comment]
> @siri10086看起来 iCloud 设备已正确链接到 iCloud3 设备。但您已将 me_iphone（icloud3 名称）链接到 iPhonewjx，该名称被列为 ma。这可能是翻译。
> 
> 返回配置更新设备，验证每个设备，进行一些更改（区域间隔，以便进行更新）并保存。然后将区域间隔恢复到原来的状态并再次保存。退出并让 iCloud3 重新启动。然后重新启动 HA 以获取新的 iCloud 登录并查看会发生什么。

After deleting and re adding the device, it's fine. Thank you very much

**Comment by gcobb321** [comment]
Excellent
