### ISSUE TITLE
Apple ID Verification Code process broken

### ISSUE THREAD

**Issue by polskikrol** [gcobb321/icloud3_v3#324]
ICLOUD3 v3.0.5.6 on HA 2024.7.4 (docker)

After the latest iCloud3 update I cannot confirm the Apple ID verification code. I attempt to input it via the iCloud3 menu, but when I click submit on the code entry page, it kicks me out to the previous menu screen without sending the code nor confirming its acceptance. Tried with Brave and Firefox browsers. Tried the submit menu button and simply hitting enter.

**Comment by gcobb321** [comment]
The HA 2024.7.4 caused a lot of problems for iCloud3 v3.0.5.6

iCloud3 v3.0.5.7 appears to be working under HA 2024.7.4/HAOS 12.4

The zip file below contains an update to iCloud3 v3. I have not released it yet but would like you to try it to make sure there are no other issues I need to look at. Let me know if it now works. TThanks.

Gary

Unzip icloud3 v3.0.5.7 into the config/custom_components/icloud3 directory and restart HA.

[icloud3 v3.0.5.7.zip](https://github.com/user-attachments/files/16442898/icloud3.v3.0.5.7.zip)

**Comment by polskikrol** [comment]
Still broken. Here are the screens I cycle through. I request a new Apple ID code, and click submit, and just takes me back to the previous menu.

<img width="621" alt="Screenshot 2024-07-31 at 10 31 44" src="https://github.com/user-attachments/assets/fc1db030-39bf-4796-92a7-b4bf2eee99eb">
<img width="605" alt="Screenshot 2024-07-31 at 10 31 53" src="https://github.com/user-attachments/assets/c7fe2875-a3bd-45ba-b299-e19177ab9db4">

**Comment by gcobb321** [comment]
Are you using a hardware key? Like Yubikey? if so, iCloud3 does not support hardware keys. I'll be looking at that on the next update.

**Comment by polskikrol** [comment]
I am not... standard iPhone setup. Everything worked fine for months, and I was able to re-auth when needed. Ran updates today and broken.

**Comment by gcobb321** [comment]
Go to the _iCloud Account & Mobile App_ screen on the _Menu_ and make sure you are signed into your iCloud account. Your account will show on the LOG OUT... line at the bottom.

![image](https://github.com/user-attachments/assets/e660e02d-8509-4c67-a6ec-da366dce7f8f)

**Comment by polskikrol** [comment]
Dug into this a bit deeper. Somehow my account was locked for security purposes? No idea how that happened. Issue resolved now.

**Comment by gcobb321** [comment]
I don’t exactly know how the account got locked. Sometimes after a number of login errors, Apple will lock it. Apple sets a’ lock’ flag on the account and iCloud3 reports it but, if locked, it does not get info back to iCloud3.

**Comment by polskikrol** [comment]
Anyway to make GUI reporting a bit better for these cases? For example, if
you are trying to get or confirm a code and you are not logged in, display
an error message in the GUI with the failure reason? Or an extra pop up to
confirm iCloud credentials? Instead of just failing back to the previous
menu screen.

Another idea could be a credentials config screen to list all iCloud
accounts, if the login auth is valid, and when the next token or auth
refresh will happen?

**Comment by gcobb321** [comment]
@polskikrol Changes have been made on the the _Enter/Request Apple Account Verification Code_ screen in the next version, v3.1, to support multiple Apple Accounts. It shows if an account needing authentication is not logged in. A _Login to Apple Account_ option has been added to the Action if it is needed.

**Comment by barrilgroup** [comment]
Hey Folks

Are you done with receiving the constant verification(2FA) request popping up on your Apple Devices and having to insert the verification code into HA to keepicloud3 working?
I have found this [workaround](https://support.apple.com/en-za/102654) from Apple, to create an APP password.
This way you can log in once to iCloud3 and forget about it and no more annoying Verification Code requests on other Apple Devices connected to your iCloud.

Have Fun, loving the iCloud3, thanks @gcobb321 

Renato

**Comment by gcobb321** [comment]
On the iCloud3 _Configure Settings > Enter/Request Verification Code_ screen, When you request a new verification code, the current token/password and session cookies are deleted. iCloud3 then refreshes the iCloud data which causes a verification code request. If you enter the app specific code, is it accepted or do you get an invalid password error? 

I have been digging into this to see how it might work without success. So far, it keeps coming up with an invalid code message. There have been some in Australia that have had a partial success with the HA Apple integration using the an app specific password and I’m wondering if it depends on the Apple server location. I’m in the US. Where are you?

**Comment by raptile** [comment]
I am running v3.0.5.7 but all of a sudden i am logged out and i keep getting the verification code and am not able to insert it.
<img width="575" alt="image" src="https://github.com/user-attachments/assets/eac963da-6cc6-4ea5-942f-eebe8f4b7943">

I insert the code here:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/c0a9ef6f-2a73-4572-a7b6-8f6223490283">

Then i select this:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/5afcc13e-d568-4426-9a79-607780848c84">

Then i get this screen:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/961bb8a5-3b3a-48ee-b205-8ba574f32fbe">

Then i get this screen again:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/c381854d-3f38-4089-ace5-59666b576063">

But no code comes.
Not even when i select the option to get one.

Then when i retry it all...
It indicates the code is incorrect while i get a mail that i am logged in.
<img width="593" alt="image" src="https://github.com/user-attachments/assets/d8cd2510-5787-40f8-840a-81de88d55bea">

So i restarted HA and had to do it again and this time it worked.

So it looks like u need to retry it a couple of times.
