### ISSUE TITLE
iCloud3 Event log card

### ISSUE THREAD

**Issue by kurim** [gcobb321/icloud3_v3#325]
Everytime I update iCloud3 the path to icloud3-event-log-card.js is wrong.

What could be the root cause for it?

File-/local//local/icloud3-event-log-card.js
![image](https://github.com/user-attachments/assets/f56d9b40-2ec2-42a6-a6cb-42bcd4620fd1)

It should be /local/icloud3-event-log-card.js

**Comment by gcobb321** [comment]
I can not duplicate this but have added a check to make sure `/local//local` is changed to what it should be, `/local`, before the resource is updated. This should prevent this problem from occurring and will be in the next release.
