### ISSUE TITLE
Duplicate Home Zones

### ISSUE THREAD

**Issue by Bosty01** [gcobb321/icloud3_v3#328]
Looking through my event log and 2 of my devices have duplicate zones -> my Home zone has 7 listed (see photo).  My other devices do not have this.  How can I remove those?
![Screenshot_8-8-2024_115842_homeassistant local](https://github.com/user-attachments/assets/f7edba2a-1fe8-413c-8ba2-0d7591706845)

**Comment by gcobb321** [comment]
I suspect those duplicate Home zones do not really exist and it is just a message formatting issue. Ignore it. I'll take a look at it
