### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by GugZi** [gcobb321/icloud3_v3#329]
Why do i get this error? it seems to crash my HA
`2024-08-30 00:11:24.544 ERROR (SyncWorker_62) [custom_components.icloud3] Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/waze_history.py", line 354, in _get_all_records
    self.cursor.execute(sql)`

**Comment by gcobb321** [comment]
An error message like that just indicates you have an error with the waze history data base but gives no indication what it is. My guess is the data base has been corrupted. I would just delete it and let it rebuild itself. The data base just stores a history of gps points with the distance and travel times to the Home zone to reduce the number of internet requests to get that data when you are driving and it’s not required. 

Delete file _config/.storage/icloud3/waze_location_history.db_ and restart HA.

**Comment by GugZi** [comment]
i can't find that location

**Comment by gcobb321** [comment]
Closed with the v3.1.1 Release. Create a new issue if you continue to experience this problem.
