### ISSUE TITLE
I've tried disabling the battery entities for the 2 FmF devices, but they are re-enabled on HA restart.

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#33]
FmF devices do not report battery level. Trying to disable these entities so that they don't show up in low-battery notifications, etc.

I've tried disabling the battery entities for the 2 FmF devices, but they are re-enabled on HA restart.

_Originally posted by @derekoharrow in https://github.com/gcobb321/icloud3_v3/issues/27#issuecomment-1382960257_
            
It appears that iCloud3 is re-enabling/re-creating entities on HA restart and overwriting entities that are disabled.

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Reopen this issue if you are still having problems after installing and using it.
See the Configurator > Sensors > Exclude Sensors. Let me know if you have any problems with it.

Gary

**Comment by gcobb321** [comment]
Icloud3 Configuration > Sensors > Exclude Sensors at the bottom. Select the sensors to exclude. You can use the filter to only show ‘battery’ sensors

**Comment by derekoharrow** [comment]
> Icloud3 Configuration > Sensors > Exclude Sensors at the bottom. Select the sensors to exclude. You can use the filter to only show ‘battery’ sensors

Thanks, but can you set it to only exclude battery sensors for FmF devices and not FamShr?

**Comment by gcobb321** [comment]
Possibly. They are created before everything else but I have the config for the device. If the FamShr and iOSApp config is both None and it's a bettery, I could not create it, It would then create the next time HA restarts. That might work. Let me think about it.
