### ISSUE TITLE
FindMy Alert without any tracking?

### ISSUE THREAD

**Issue by thisiscam** [gcobb321/icloud3_v3#330]
Hi!

Is it possible to use the findmy alert script without enabling tracking for the device?

**Comment by gcobb321** [comment]
Try setting the ` Tracking Mode ` for the device to _Monitor_. The device will not be actively tracked but it’s info will be updated when other devices are updated. Do that on the _Configure Settings > Update Devices_ screen

**Comment by thisiscam** [comment]
Thanks! That works good for me!
