### ISSUE TITLE
Can you move Temporary work file outside of config folder.

### ISSUE THREAD

**Issue by andyblac** [gcobb321/icloud3_v3#331]
I use auto-backup integration, and it keep failing to do backups due to iCloud temp file being removed after a backup has started.

```
2024-09-04 12:00:00.453 ERROR (MainThread) [supervisor.homeassistant.module] Can't backup Home Assistant Core config folder: [Errno 2] No such file or directory: '/data/homeassistant/.storage/icloud3/tmpyf_o9nsu'
```

So, would it be possible to use a temp folder outside of the config folder structure ie use `/tmp/icloud3`

Thanks
Andrew

**Comment by gcobb321** [comment]
The iCloud3 log files are renamed at midnight. Change the time of your backup to a few minutes later (12:15, 1:00, etc,)

**Comment by andyblac** [comment]
> The iCloud3 log files are renamed at midnight. Change the time of your backup to a few minutes later (12:15, 1:00, etc,)

this was 12:00 pm midday. not 00:00 pm

**Comment by gcobb321** [comment]
The log file is actually a sublog file of the HA logger module and updated using the HA logger routines. Those routines  are probably putting a lock on the file while it is updated and out of my control. 

The only think I can think of doing is to change the time of your backup to the middle of the night and use the iCloud3 service calls to pause device tracking while the log is being done and resume tracking when it is finished. Or maybe exclude that file from being backed up. I do not see moving the file to another directory. 

I back up my files at night around 10pm using the Home Assistant Google Drive Backup add-on and again locally at 2am using an automation and have not had any issues.

**Comment by andyblac** [comment]
as I said I do hourly backups, and 95% of the it works fine, but about 2-3 backups a day fail. I'll see of it can ignore files using wildcards `/data/homeassistant/.storage/icloud3/tmp*`

**Comment by andyblac** [comment]
nope, unfortunately the integration `auto-backup` does not allow excluding files.

**Comment by gcobb321** [comment]
iCloud3 has no *.tmp files the iCloud3 log files in the _/config_ directory are _icloud3-0.log, icloud3-1.log and icloud3-2.log_ for today, yesterday and the day before. The files in the _.storage/icloud3_ directory that gets updated a lot is _restore_state_ (no extension). Is updated whenever a state value of the iCloud3 entities change and is used to restore those values on an HA restart. The _waze_location_history.db_ is a sql file that is updated when tracking is done and stores the time & distance to Home so internet calls do not have to be done when driving to get that info. Could that be the file the sql module is creating a tmp file?

**Comment by andyblac** [comment]
the files start with `tmpy`, no idea where this coming from, it looks like when it start the backup the file is there, but by the time it gets to the file to include it in the compress it gone, and why it cause the backup to fail. atm I have no `tmpy*` files n the folder.
