### ISSUE TITLE
Please remove the divding lines in the attributes section

### ISSUE THREAD

**Issue by Sascha-L** [gcobb321/icloud3_v3#332]
Hi,

could you please remove the dividing lines here:
![icloud3](https://github.com/user-attachments/assets/8f016fb4-f5c2-4914-83bd-3f8d286e595e)

Each line is an attribute, so the hyphens used as dividing line is also a name, but hyphens are not allowed in Home Assistant, only underscores. 
For example the code generation of NetDaemon has problems with those not allowed names:
https://github.com/net-daemon/netdaemon/issues/1166

Thanks!

**Comment by gcobb321** [comment]
v3.0.5.8 should take care of this

**Comment by Sascha-L** [comment]
Wow, this was fast! Thanks! :-)

**Comment by gcobb321** [comment]
I was doing an update to fix the mobile app issue and added your request since it was a simple one. Glad to do it.
