### ISSUE TITLE
iCloud location tracking is not available

### ISSUE THREAD

**Issue by pephumin** [gcobb321/icloud3_v3#335]
I have found errors on adding a new device, so I uninstalled and freshly installed icloud3_v3 development.

after a successful installation, I managed to successfully logged in to my iCloud account.

now I get an error on locating existing devices i previously had with an error of iCloud location tracking is not available.

I also give icloud3-0.log below if it helps…

`                                          ⡇   JUESIPADAIR4, FAMSHR, CURRZONE-LUZERN,  
                                          ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
09-23 21:19:19 CONFIG   Checking Mobile App Integration > Loaded, Devices-s8plus, pesiphone14pro, pesipadpro, juesiphone14pro, pesiphone14pro
09-23 21:19:23 ------   Checking Mobile App Integration > Loaded, Devices-s8plus, pesiphone14pro, pesipadpro, juesiphone14pro, pesiphone14pro
09-23 21:19:33 CONFIG   Checking Mobile App Integration > Loaded, Devices-s8plus, pesiphone14pro, pesipadpro, juesiphone14pro, pesiphone14pro
09-23 21:19:36 ------   Checking Mobile App Integration > Loaded, Devices-s8plus, pesiphone14pro, pesipadpro, juesiphone14pro, pesiphone14pro
09-23 21:19:49 CONFIG   Connecting to and Authenticating iCloud Location Service Interface (unknown)
09-23 21:19:49 CONFIG   Initialize PyiCloud Service, establish iCloud Location Services connection
09-23 21:19:49 CONFIG   Session file does not exist
09-23 21:19:49 CONFIG   Authenticating account  (ph....@sa..........) with token
09-23 21:19:52 ------   Authentication completed successfully, method-Password+Token
09-23 21:19:53 ------   iCloud Acct Auth #5 > Password+Token, Last-21:05:22
09-23 21:20:27 ------   Connecting to and Authenticating iCloud Location Service Interface (unknown)
09-23 21:20:27 ------   Initialize PyiCloud Service, establish iCloud Location Services connection
09-23 21:20:27 ------   Session file does not exist
09-23 21:20:27 ------   Authenticating account  (ph....@sa..........) with token
09-23 21:20:29 ------   Authentication completed successfully, method-Password+Token
09-23 21:20:30 ------   iCloud Acct Auth #6 > Password+Token, Last-21:19:53
09-23 21:20:50 ------   Service Action > Action-Locate All Devices with iCloud FamShr
09-23 21:20:50 ------   pesiphone14pro_app > iCloud Location Tracking is not available
09-23 21:20:50 ------   pesipadpro_app > iCloud Location Tracking is not available
09-23 21:20:50 ------   phumin > iCloud Location Tracking is not available
09-23 21:20:50 ------   juesiphone14pro_app > iCloud Location Tracking is not available
09-23 21:20:50 ------   juesipadair4 > Location will be updated at 21:20:55
09-23 21:20:55 MONITR ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                          ⡇   JUESIPADAIR4, , CURRZONE-LUZERN, FAMSHR@21:17:09 
                                          ⡇⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂
09-23 21:20:55 LOCATE ⡇ juesipadair4 > Located > FamShr-21:19:56 (59 secs ago)
09-23 21:20:55 MONITR ⡇ juesipadair4 > Zone > Luzern(1)-21m > NotSet(4), GPS-(13.70299, 100.64025/±16m)
09-23 21:20:55 MONITR ⡇ juesipadair4 > Results > Arrive-21:20, NextUpdate-23:20:55, Moved-0.0km , Battery-89%, ×Went3km, WazeMsg-×Under1km
09-23 21:20:55 MONITR ⡇⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂
                                          ⡇   JUESIPADAIR4, FAMSHR, CURRZONE-LUZERN,  
                                          ⡇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
09-23 21:20:59 ------   pesiphone14pro_app > The iCloud FamShr Device was not specified or is not available. The alert will be sent using the Mobile App
09-23 21:21:05 ------   Service Action > Action-Request Apple ID Verification Code
09-23 21:21:10 ------   Connecting to and Authenticating iCloud Location Service Interface (unknown)
09-23 21:21:10 ------   Initialize PyiCloud Service, establish iCloud Location Services connection
09-23 21:21:10 ------   Session file does not exist
09-23 21:21:10 ------   Authenticating account  (ph....@sa..........) with token
09-23 21:21:12 ------   Authentication completed successfully, method-Password+Token
09-23 21:21:13 ------   iCloud Acct Auth #8 > Password+Token, Last-21:20:55
`

**Comment by pephumin** [comment]
Oh no. Just saw the log format went bad… sorry…

**Comment by gcobb321** [comment]
The Event Log gives a lot of info on how the startup process has been set up, the devices that were returned from iCloud and how iCloud3 has been configured for each one. Have you reviewed the _Event Log_ and reviewed the setup for each device on the _Configure Settings > Update Devices_ screen? The iCloud3 docs give info on how to do this and what to look for.

**Comment by pephumin** [comment]
thank you for your reply. 

I will follow your advice on exploring details in the Event Log which should give me some clues on where to fix.

I am closing this issue.

**Comment by pephumin** [comment]
Closing

**Comment by pephumin** [comment]
thank you for your reply. 

I will follow your advice on exploring details in the Event Log which should give me some clues on where to fix.

I am closing this issue.

**Comment by JanneBoj** [comment]
Same problem for me. Famshr lookup stopped working around 1500 GMT yesterday.

**Comment by gcobb321** [comment]
@JanneBoj Review the Event Log to see if there are any communication errors with Apple. Also look at _HA Settings > System > Logs_ to see if there is anything there related to iCloud3.

**Comment by JanneBoj** [comment]
Hi!

The last rows in the Event Log looks strange as you can see below.

There isn’t any entries from the last days in the Event Log.

All the entities from all devices are from around 15.00 GMT (17.00 local time) yesterday (Sept 23)

So, there isn’t just a problem with FamShr I presume. It´s my installation that is corrupt in some way.

 

What do you think? Should I delete the integration and start over or should I try to delete the Event Log or….

 

Just to let you know; this is my first ever problem with Icloud3. 

__________________________________________________________________________________

17:12:35Configure iCloud3 Operations >

                • Load configuration parameters

                • Set Display Text As Fields (0 used)

                • Set Default Tracking Method (iCloud)

                • Initialize Debug Control (info)

                • Set Unit of Measure Formats (km)

                • Set Event Log Record Limits (11500 Events)

                • Device Tracker State Value Source 

                 (iCloud3 EvLog Zone Display Name)

17:12:35Set Up Waze > Server-Rest of the World (ROW), CountryCode-SE, MinDist-1km, MaxDist-999km, Realtime-True, HistoryDatabaseUsed-True

iCloud3 v3.0.5.9 > Restarting, Thursday, Sep 19

17:12:32Service Action > Action-Restart iCloud3

17:12:32Service Action Received > Action-restart

10:11:04iCloud Acct Auth #14 > Password+Token, Last-09:24:38

09:24:45Removed HA Zone > Stationary (..._1)

09:24:45HA Zone Deleted > Zone-Stationary/ic3_stationary_1

09:09:20Reusing Stationary Zone > Stationary (..._1)

01:40:39iCloud Acct Auth #3 > Password+Token, Last-00:40:13

01:00:00Local Time Zone Offset > UTC+02:00 hrs, CEST, Country Code-SE

6:48:33pSensor Entities > Created-98, Excluded-0

**Comment by JanneBoj** [comment]
And sorry, there is nothing i HA’s logs related to iCloud3 except for this one:

“This error originated from a custom integration.

 

Logger: custom_components.icloud3

Source: custom_components/icloud3/device.py:1922

integration: iCloud3 v3: iDevice Tracker (documentation, issues)

First occurred: September 17, 2024 at 18:48:50 (42211 occurrences)

Last logged: September 20, 2024 at 05:36:10

 

invalid literal for int() with base 10: 'unavailable'

Traceback (most recent call last):

  File "/config/custom_components/icloud3/icloud3_main.py", line 314, in _polling_loop_5_sec_device

    Device.update_battery_data_from_mobapp()

  File "/config/custom_components/icloud3/device.py", line 1922, in update_battery_data_from_mobapp

    battery_level  = int(battery_level_attrs[STATE])

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: invalid literal for int() with base 10: 'unavailable'”

**Comment by gcobb321** [comment]
@JanneBoj That is an error related to trying to get the battery level info from the Mobile App that has been fixed but then reverted to an older version somehow. I'll update iCloud3 tomorrow.

Unzip device.zip into the icloud3 directory and restart HA.
[device.zip](https://github.com/user-attachments/files/17121655/device.zip)

**Comment by JanneBoj** [comment]
Thanks Gary, your advice plus a re-add of my daughter’s phone did the trick. Now things are working again and my wife will get her fresh coffee when she arrives home from work. iCloud3 is the piece of software that is the greatest WAF in our home. It is just too bad I cannot convince her to install the Mobile App. Thanks again Gary for a great piece of software and for your great support.
