### ISSUE TITLE
Icloud V3 makes person entity jump location shorthly

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [gcobb321/icloud3_v3#336]
Hello @gcobb321, we already talked about this issue in #263 and #267 while it looked first it was working after some adjustments and updates, i still have the same issue being when i add the iCloudV3 tracker to person entity it all the time makes it jump short to previous know location home/away/home as example... I was a bit busy so for now i just added some failsafe conditions to automations using the person entity location. Now i had some free time again so i did set up a new person entity using same device trackers (icloudv3 tracker, ha mobile app tracker, life360 tracker, asuswrt tracker, ping tracker) as the original person entity having this issue but leaving the icloudv3 tracker out I added screenshots below of each person entity and the test person entity not showed the same behaviour and not did jump the location, to exclude any doubts on the second day I added the iCloudv3 tracker also to the newly created test person entity and the as you can see on screenshot below it started to get the same issue and jump location similar as the original person entity.... any idea how we can solve this?

for extra info I also added screenshot from the independent device trackers history logs of day 1 of test

DAY 1 (one person entity with icloudv3 tracker one without)

![media_20240924_085759_5411602558669283813](https://github.com/user-attachments/assets/4c1d8ab5-d0b5-4317-bfe4-ee648e11e9cc)

![media_20240924_085759_2301908038660773279](https://github.com/user-attachments/assets/8f09d9c1-503f-458c-aba8-9d352a0890da)

DAY 2 (both person entities using icludv3 tracker)

![media_20240925_082741_6717741746328952598](https://github.com/user-attachments/assets/0eb0c572-382b-4537-82ea-774704389ff6)

![media_20240925_082741_486097176735403489](https://github.com/user-attachments/assets/79b64d88-ea8e-4678-863b-c5d11d53a676)

Independent device tracker information DAY 1

![media_20240924_090241_5941290502452383451](https://github.com/user-attachments/assets/e9acf8af-05e4-4574-b3f5-c767fb78444f)

![media_20240924_090241_5017549438669186583](https://github.com/user-attachments/assets/5a3221ca-e71d-4f56-85e8-b1965b929fd6)

![media_20240924_090241_8165268456769463703](https://github.com/user-attachments/assets/da4dc8b6-72c9-4024-8672-8b9f7e166214)

**Comment by smarthomefamilyverrips** [comment]
I did try with and without the HA Mobile App tracker added to the person.entity and also with and without the HA Mobile App tracker added to the iCloudV3 configuration. None of these variations made any difference to the issue unfortunately

**Comment by gcobb321** [comment]
1. You should not have both the iCloud3 and mobile app device tracker entities. iCloud3 monitors the mobile app tracker and uses it’s info or the Apple iCloud info, whichever is later, to locate a device.
2. Personally, I think you are using too many trackers for the person. The way the person entity works it’s by monitoring the gps latitude and longitude attributes of each tracker entity. It does not look at the age or accuracy of a location, just grabs the data. So you can have a good location used on one update from one tracker entity that gets overwritten by an old location from another tracker entity. Each time it does an update, it sees if the gps is in the zone or out of the zone.  And you do not know which tracker entities data is being used. 
3. I’ve always just used the zone sensor in iCloud3 and never had a problem knowing where a device is
4. The iCloud3 _Event Log_ shows how iCloud3 is handling location and zones. That is the place to see what iCloud3 is doing and compare that with the other history info

**Comment by smarthomefamilyverrips** [comment]
1. I not have, as you told me same in the past. I just did try different options to see if made a difference. 
2. I just am using 2 other GPS based trackers and on my test person entity I not have the issue that it jumps to a old location before jumping back again to the new location when I not use the iCloudV3 tracker.
3. I do have this issue already a long time as we also discussed before in issues.
4. I use event logs but just says it updated location, I not would know what I should else see.


So why it only does thos to a person entity if also the iCloudV3 tracker is used?

**Comment by smarthomefamilyverrips** [comment]
So just to be clear my general person entity uses the iCloudV3 tracker (and the iCloudV3 integration is setup to use mobile app) and Life360 tracker and is jumping location as can be seen in screenshots

The test person uses the HA Mobile App tracker and Life360 tracker and not is having any issues with briefly jumping back to a previous location.

**Comment by smarthomefamilyverrips** [comment]
@gcobb321 now when checking event log I see it stopped using the mobile app instead of showing location it says "not used" and in configuration screen says Mobile App is not available (see screenshot), any idea why this is?

![Opera Snapshot_2024-10-02_110208_homeassistant local](https://github.com/user-attachments/assets/1320c7be-5581-49bf-9128-1e3c7824dde4)

**Comment by gcobb321** [comment]
Closed with the v3.1.1 Release. Create a new issue if you continue to experience this problem.
