### ISSUE TITLE
Many sensors broken in Monitor mode?

### ISSUE THREAD

**Issue by nzrutman** [gcobb321/icloud3_v3#337]
After restarting HA, many sensors for my Monitored phones do not get updates. Equivalent sensors for my Tracked phone does.
Even if phone moves Away and back Home, position/zone is reported correctly.
![Screenshot 2024-09-30 at 7 24 08 PM](https://github.com/user-attachments/assets/367798e5-c5d3-49e1-b7ee-bca10fc6651f)
![Screenshot 2024-09-30 at 7 18 26 PM](https://github.com/user-attachments/assets/c3e12425-9e54-4f68-a6a3-c8e112ef27bc)

I moved these to Monitored instead of Tracked because I'm trying to decrease the GPS update rates, which seem to be flatlining the batteries (I also wish there was a max update rate setting somewhere).

**Comment by gcobb321** [comment]
Check the _Configure Settings > Sensors_ screen to see what sensors are created for Monitored devices. There are three check boxes towards he bottom of the list - Badge sensor, Battery sensors and Location type sensors. Make sure all of them are checked.

**Comment by nzrutman** [comment]
Well now I feel foolish. "Location related sensors" was off. 
However, these were/are _on_ in the list, but still unavailable above:
- Device sensor _info
- Location sensors _last_updated, _last_located
- Time sensor _arrival_time
- Distance sensors _home_distance, _dir_of_travel

Oh wait, now I see it: "Monitored Device Sensors" apply to Monitored devices, with the implication that these other checkboxes apply only to Tracked devices.

Thank you for an awesome integration!
