### ISSUE TITLE
Getting Error trying to add Integration

### ISSUE THREAD

**Issue by Exit2Studios** [gcobb321/icloud3_v3#34]
When I click "add integration" from the Integration Configuator, I get the following error:

This device can not be added from the UI
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.

I am doing this from a Mac, not an ios device.  I got the same error when I used my iPhone as a test.

**Comment by gcobb321** [comment]
In the`/config/custom_components/icloud3` directory, do you see a file `icloud3_main.py`, 'const.py` or just a 'device_tracker.py` file? Are the dates of these file in 2023 or is the `device_tracker.py` file in 2021?

If you see `const.py`, the open it, the version number will be at the top and look like `VERSION = 'v3.0.0b8'.
What is the version if you see it?

If you do not have an `icloud3_main.py` or `const.py` files and only the `device-tracker.py` file, you have not installed v3 and still have v2 installed. Download the v3 zip file and unzip it (the icloud3 directory portion) into the `/config/custom_components/icloud3 directory. Restart HA and try again.

**Comment by Exit2Studios** [comment]
I only have the device_tracker.py (I have not installed v3).  I unzipped the folder, but am getting some errors loading the component.  Do I put the entire folder in the /config/custom_components/icloud3 directory or just the contents (I'm using the beta 8 version)?

**Comment by gcobb321** [comment]
The contents of the iCloud3 directory in the zip file (including sub-directories) are installed in the icloud3 directory.

**Comment by Exit2Studios** [comment]
That's what I did, but I'm getting config errors.  Can I delete everything and just put the beta folder contents in?

**Comment by gcobb321** [comment]
Yes, you can delete everything in the iCloud3 folder and unzip it again but take a screenshot of the iCloud3 directory and post on this note. I would like to see how I it is set up right now. 

The zip file has the /custom_components/icloud3 structure. Make sure you are not ending up with ‘/config/custom_components/icloud3/custom_components/icloud3’ structure.

**Comment by Exit2Studios** [comment]
I posted above how it looks when I pasted the beta contents into the existing folder.

**Comment by gcobb321** [comment]
I just uploaded Beta 8b to fix a migration issue. Delete everything in the iCloud3 directory and unzip Beta 8b into it.

Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-8b.zip. Click download on the right side of the screen.

**Comment by JtwoA** [comment]
I just refreshed and everything still looks like beta8a.  I’ll give it a few.

**Comment by gcobb321** [comment]
The only change between b8a and b8b was to change the v2v3migration.py module which had ha_country_code in it. I changed it to just country_code in line 570.

**Comment by Exit2Studios** [comment]
I got v3 installed, and completed the 2FA but my sensors aren't updating frequently. For example, my battery charging status was last updated yesterday.

**Comment by gcobb321** [comment]
@Exit2Studios  There tracking type of sensors are updated each time the device is located, which in a zone, might be every 2-hours, depending on your inzone_interval.  The battery_status sensor only updates when the device goes from charging to not charging, the battery sensor is updated when the battery level changes. Beta 9 does deal with some battery issues and will be out later this week.

**Comment by gcobb321** [comment]
Version ?

**Comment by Exit2Studios** [comment]
When will it be available?  I'm on 8a.

**Comment by Exit2Studios** [comment]
I updated to 8b and the sensor data is way out of date.  It's giving me battery status (the only thing I really know how to check in real time since I'm home) from yesterday.

**Comment by gcobb321** [comment]
This week, probably Thursday after I finish the item I'm working on.

**Comment by Exit2Studios** [comment]
Is the behavior I'm seeing to be expected or is there something I can try to get it reporting accurately?  It is simply not updating at all.

**Comment by gcobb321** [comment]
Lets see if b9 fixes it. 8b only changed the v2v3migration program, nothing else so 8a=8b except for that. B9 has a lot of other changes.

**Comment by Exit2Studios** [comment]
Interestingly (?), the ios device is showing the exact same values.

**Comment by gcobb321** [comment]
ic3 looks at the ios app battery info every 5-seconds and gets it when it changes. The other source is famshr when an icloud famshr tracking update is done.

**Comment by Exit2Studios** [comment]
When I go to Sensors in the companion app, it is accurate (i.e. charging), but neither sensor is being updated in HA.

**Comment by gcobb321** [comment]
I know. That has been fixed in b9.. Which will be out in a few days.

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Reopen this issue if you are still having problems after installing and using it.

Gary
