### ISSUE TITLE
iCloud3 V3 doesn’t update to 3.0.5.9

### ISSUE THREAD

**Issue by Remcovf** [gcobb321/icloud3_v3#342]
I downgrade to 3.0.5.7, then update to 5.9 but in integration I see the version 3.0.5.8.

Also requesting a code doesnt work and I get a
Error logging in.

**Comment by Remcovf** [comment]
![IMG_2289](https://github.com/user-attachments/assets/0b8d9c6c-b216-494c-a528-5dac518024fa)

**Comment by gcobb321** [comment]
The problem is an issue signing into the Apple account. See [issue here](https://github.com/gcobb321/icloud3_v3/issues/341)
