### ISSUE TITLE
AppleWatch battery drain

### ISSUE THREAD

**Issue by thogens** [gcobb321/icloud3_v3#353]
Hi!

I'm tracking an AppleWatch SE and after adding it to the newest version of iCloud3, the battery goes down like crazy.
I set the update interval to 1h, but I noticed that the battery state is updated much more frequently.
Is there something wrong with my config?

Please note: I'm not having this battery drain issue with my AppleWatch Ultra, but maybe due to the bigger battery, I don't notice.

Any idea?

**Comment by gcobb321** [comment]
Probably not. Even though it is on a long time span, it will be located when the other devices on the Family List are updated. And there is nothing you can do about than.

**Comment by thogens** [comment]
I could forget about tracking my Ultra and only track the SE. Would that help?

**Comment by gcobb321** [comment]
@thogens 
I don’t really have an answer on if that would help. You will just have to try it and see. Apple does all of the device locating. I just handle the data. You could change the _Tracking Mode _ to Monitor on the _Configure Settings > Update Devices_ screen also. Then iCloud3 will not request a location u update for it and only update it when another device is updated.

**Comment by GLG9** [comment]
Hi, I have an Apple Watch 11 and went to sleep at 11pm with 57% battery. When I woke up at 7am it only had 10% battery left. I had previously tested v3.0.5.9 b1 and everything was normal. Yesterday I updated to the current version v3.1.1 and then the problem occurred.

**Comment by GLG9** [comment]
Hi, unfortunately there is nothing noticeable in the log for the Apple Watch. I have set the in zone interval to 5 minutes to always see quickly when I charge the watch and to see the exact progress of the battery when it charges and discharges

**Comment by gcobb321** [comment]
Try changing that to 15-min and see what happens.

**Comment by GLG9** [comment]
Everything is now running normally again. I stayed with the 5-minute interval and the battery is now discharging normally again. So maybe the problem was more to do with Apple and the WachOS. Thank you very much.
