### ISSUE TITLE
Connexion impossible

### ISSUE THREAD

**Issue by Tays005** [gcobb321/icloud3_v3#354]
Hello,

I am stuck at this step when I validate the window does not close.

I have never had any problems with this integration except since the beginning of the month.
I deleted everything to redo everything, but I am still blocked by something

![image](https://github.com/user-attachments/assets/afe637a5-7f5f-456a-8b9a-312cfec61eee)

thk

**Comment by gcobb321** [comment]
Update to v3.1.1, which was just released. Then see what happens.

**Comment by Tays005** [comment]
Hello,
I still have the same problem, and the devices do not go back up.

![image](https://github.com/user-attachments/assets/7dab408d-b85b-406d-8542-86ba548ac5d3)
We cannot exit and therefore validate the window

![image](https://github.com/user-attachments/assets/839aa219-8ad4-454a-9dfb-d0fa3acadc85)

**Comment by gcobb321** [comment]
Click the ‘X’ in the right corner and it will close the window.

**Comment by Tays005** [comment]
Yes I did that :) no big deal. 

but suddenly I don't have the impression that the account is setting up correctly. he sees me no device

**Comment by gcobb321** [comment]
Restart HA, verify the devices in the Event Log > Stages 3 & 4 to see if the Apple accts are signed into correctly.

**Comment by Tays005** [comment]
![image](https://github.com/user-attachments/assets/10506fe3-3973-4443-8d73-5c87072f0756)

![image](https://github.com/user-attachments/assets/b50f4958-2712-4ec4-b17c-f7e8a2e4c029)

still no device...

**Comment by Tays005** [comment]
![image](https://github.com/user-attachments/assets/d2f93da2-c953-428d-8e09-ef7dbe861df5)
