### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by tripp396** [gcobb321/icloud3_v3#356]
When I attempt to go through the setup and type in my username and password, it only returns that the username and password is invalid. When trying same username and password on the iCloud site, it works just fine.

Unsure what logs I could pull to see what’s happening here. If I try to request a code there is no account to select in the drop down because I don’t think it’s saving my account due to the error.

**Comment by gcobb321** [comment]
Install v3.1.1 and see how if it works. If it is a valid password, but it gives you an SRP (Secure Remote Password), it explains why and you are going to need to change your password. See my note [here](https://github.com/gcobb321/icloud3_v3/issues/341#issuecomment-2458440469) about this

**Comment by gcobb321** [comment]
This is probably fixed in v3.1.4. Create a new issue if you encounter this problem again.
