### ISSUE TITLE
Unable to get validation code

### ISSUE THREAD

**Issue by jspeckman** [gcobb321/icloud3_v3#358]
Installed 3.1.1, and after deleting my old account information under .storage, I am able to create an account.
However after putting my username and password in and requesting a code, it never shows up and the following entry is in icloud3-0.log each time I try to get a code.

11-07 14:21:42 iCloud3 v3.1.1
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 655, in __init__
    self.authenticate()
  File "/config/custom_components/icloud3/support/pyicloud_ic3.py", line 827, in authenticate
    raise PyiCloudFailedLoginException(err_msg)
custom_components.icloud3.support.pyicloud_ic3.PyiCloudFailedLoginException: jspeckman, Authentication Failed, Python SRP Library Credentials Error. The Python module that creates the Secure Remote Password hash key has calculated an incorrect value for a valid Username/Password. Try changing the Password to see if the Apple Acct can be logged into. ErrorCode-401

**Comment by gcobb321** [comment]
See my note [here](https://github.com/gcobb321/icloud3_v3/issues/341#issuecomment-2458440469) about that. Changing the password has helpted with others. Please send me the one that will not work so I can pass it along to the guys that wrote the SEP code.

**Comment by Rodik2** [comment]
Changing password at apple simply forces more problems to come up wit other software using the apple account...

**Comment by gcobb321** [comment]
This is probably fixed in v3.1.4. Create a new issue if you encounter this problem again.
