### ISSUE TITLE
Home Assistant doesn't recognize fmf icloud3 devices inside zones

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#36]
**Home Assistant doesn't recognize fmf icloud3 (Beta8a) devices inside zones...**

![image](https://user-images.githubusercontent.com/11551691/212687012-5017ee3a-c330-41c2-8b35-bbe526951aba.png)

**Same devices using icloud3 v2.4.7....**
![image](https://user-images.githubusercontent.com/11551691/212686638-57f4edea-e7c2-4397-a6e6-2360343c7321.png)

**Comment by gcobb321** [comment]
I can see the counts are different but I don’t think that is an iCloud3 issue with FmF not detecting when someone is in a zone. I’d check the entity names being counted. 

iCloud3 gets the location data from iOS app, famshr and fmf, picks the latest one and then that data runs through the same routine to determine the location, Zone status and everything else. For testing, my wife is using fmf and iOS App data right now and everything is ok. 

Check the Event Log and iCloud3 entities to see what their values are.

**Comment by marceloaf** [comment]
**I'm not sure if I followed you but ic3 recognizes iphone_martha as being in the zone CasaDaMartha but HA doesn't. I'm using iphone_martha as a reference. See images below:**
![image](https://user-images.githubusercontent.com/11551691/212722784-01ea14f8-2752-4578-8188-8387c00cd2ac.png)



**On the other hand, HA does not recognize anyone being in zone casa_da_martha in the past hours:**
![image](https://user-images.githubusercontent.com/11551691/212722639-a98c3cab-14f4-42a4-9920-fc68e9814b5d.png)

**Comment by gcobb321** [comment]
What you are looking at is the HA history. The source of this data can be seen on the Developer Tools > States screen. Look at the following entities to see where the device is right now:
device_tracker.[devicename] & device_tracker.[devicename] zone attribute
sensor.[devicename]_badge

The EvLog shows the device is in a zone. Verify the zone.[zone] name entity, not the friendly name of the zone, to make sure the zone names match

You can also go into the iC3 configurator, Event Log screen and select how the zone name is displayed. Select the zone entity to make sure the history is correct

If ic3 has it in a zone, then it is must be a HA history display/selection issue. I would check again what is being displayed on the history screen by  checking the zone entity names

**Comment by marceloaf** [comment]
Here are the images...


device_tracker.[devicename] & device_tracker.[devicename] zone attribute
![image](https://user-images.githubusercontent.com/11551691/212732474-5ecb346e-a2d5-4e1f-a7c4-3ae9e0c95f49.png)

Badge is in CasaDaMartha state...
![image](https://user-images.githubusercontent.com/11551691/212734749-c33613e8-853e-4139-ba7c-600487c741b6.png)


zone.{zone] entity. Still no one in there.
![image](https://user-images.githubusercontent.com/11551691/212734019-2d863713-82e1-4cfe-8416-88950ae73ece.png)

selected zone_entity as how the zone name is displayed, just to make sure.
![image](https://user-images.githubusercontent.com/11551691/212733185-35090964-618b-444f-b00f-e5f0ebd304ac.png)

**Comment by gcobb321** [comment]
Now I see. Looking at it now. My badge says not_set too.

**Comment by marceloaf** [comment]
Now the badge updated the zone_fname but shouldn't the zone_fname include de spaces and show the actual Friendly Zone name?
![image](https://user-images.githubusercontent.com/11551691/212743640-6598bf31-4a3a-479a-9e86-c5358616e22f.png)

**The zone.[zone] entitly still thinks no one is in there....**
![image](https://user-images.githubusercontent.com/11551691/212743840-41880b2b-b0d2-4d41-b92d-0c0ad84f7a9b.png)

**Comment by gcobb321** [comment]
Yes. I have to run out and will fix that later.

**Comment by marceloaf** [comment]
**The zone.py did correct the zone_fname sensor...**

![image](https://user-images.githubusercontent.com/11551691/212765776-17848848-82ae-4fbd-8924-68710a6246e8.png)

**But the devices are still not recognized within a zone... Don't know what I am doing wrong... It is configured the same way in v2.4.7**
![image](https://user-images.githubusercontent.com/11551691/212767380-931779cb-c338-47e6-949c-ad0b742be90a.png)

**Comment by B-Hartley** [comment]
Are these files correct in the 8b beta ?
Zones for my devices are only showing as home or not_home, icloud3 doesn't seem to be aware of the home assistant zones? is it worth me trying either of these files ?

Thanks

**Comment by gcobb321** [comment]
No. the files I sent you are not in b8b. The only thing changed in b8b was the v2v3migration.py file. The other files (zone.py, device.py, etc) will need to be reinstalled until I put a b9 together.

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Reopen this issue if you are still having problems after installing and using it.

Gary

**Comment by marceloaf** [comment]
Hi, good morning. The issue persists...

**Beta 9:**
![image](https://user-images.githubusercontent.com/11551691/214037434-1ec37e97-8e2b-4732-854c-984bce2822ce.png)

![image](https://user-images.githubusercontent.com/11551691/214038109-c1c49c77-67f3-44a1-af96-a9237d1392d5.png)



**versus v2.4.7:**
![image](https://user-images.githubusercontent.com/11551691/214037655-68501b8f-c65e-4617-8e81-97f2d5267fc5.png)

![image](https://user-images.githubusercontent.com/11551691/214037982-5c361eb4-da6a-42bf-817e-4c58d1a4421a.png)
