### ISSUE TITLE
Reload appends new increment "_#" appended to entity ids

### ISSUE THREAD

**Issue by gmcui** [gcobb321/icloud3_v3#360]
Every time I click "Reload" (under 3-dots next to Configure), all entity ids have their end "_[number]" incremented by 1.  I am up to _7 now, LOL.  This breaks the lovelace card, as well as any automation/nodered.

This is seen on HAOS running as VM on Proxmox, everything is up-to-date.  Freshly installed iCloud3 V3 (3.1).

Thanks for looking into this.  Also, is there anyway to manually remove the _# suffix of all iCloud3 entities?

**Comment by gcobb321** [comment]
That is caused by the Reload. HA still has iCloud3 running when it is reloaded so the entities with the previous startup still exist. HA makes them unique by adding the prefix. You must do a Restart, not a Reload and you will not have this problem.

**Comment by gmcui** [comment]
OK, thanks!
