### ISSUE TITLE
Still unable to login with v3.1.2

### ISSUE THREAD

**Issue by NR3Y** [gcobb321/icloud3_v3#363]
Gary.

I still can't seem to log in to my iCloud account (or get a Verification code from Apple) with the latest version. I completely uninstalled iCloud3, re-downloaded it from HACS and added it back as a new integration, and the symptoms are still the same. However, when I re-added it, it didn't seem to be a completely fresh installation, as it had my AppleID cached someplace, so I've no confidence the 'refresh' was a true refresh.

<img width="392" alt="Screenshot 2024-11-09 at 9 59 07 AM" src="https://github.com/user-attachments/assets/18ac57d7-005e-4815-8546-ac07056a63b8">

BTW, clicking on the purple gear icon (below) does nothing. It just refreshes the same page.

<img width="490" alt="Screenshot 2024-11-09 at 9 57 45 AM" src="https://github.com/user-attachments/assets/859144f1-6e9d-461d-8f94-eb3a8c167e66">
Is there any way to completely remove my Apple account and credentials and start again as if I were a brand new user, preferably without a another uninstall/install scenario? (Yea, I tried the remove account using the configuration menu, but that didn't seem to do anything useful.)

**Comment by gcobb321** [comment]
The configuration parameters are stored in _.storage/icloud3/configuration_ file. Delete the _.storage/icloud3_ directory and restart HA

**Comment by Remcovf** [comment]
Hi @gcobb321,


i have also a _.storage/cloud_ and a _.storage/icloud3.apple_acct_ So actual i have 3 maps in with the name iCloud in _.storage/_ Delete all 3?

**Comment by gcobb321** [comment]
Delete .storage/icloud  - Old Apple cookies and login session files
Delete .storage/icloud3 - iCloud3 config and associated files
Keep .storage/icloud3.apple_accts - New Apple cookies and login session files

**Comment by NR3Y** [comment]
Making some progress, but also getting frustrated with adding devices.

I deleted _.storage/icloud_ and _.storage/icloud 3_ directories, and the integration now let me log on to my Apple account and I was able to get (and submitted) the verification code - all good so far.

<img width="604" alt="Screenshot 2024-11-09 at 4 43 49 PM" src="https://github.com/user-attachments/assets/5885571a-3462-41e2-afed-bacfbbc268fb">


However, now I'm having issues adding my and my wife's iPhones in again. I deleted all the entities associated with both phones (which were shown with a red circle besides them - and there were a lot!).

When I tried to add a new device (the first example being my wife's phone), it asks for an "ICLOUD3 DEVICE_TRACKER ENTITY ID". What goes here? "device_tracker.barbara_s_iphone_14_pro" or simply "barbara_s_iphone_14_pro"? Because when I entered the former, I now get **four** monitored devices in splash screen instead of the traditional three.

<img width="1637" alt="Screenshot 2024-11-09 at 5 02 15 PM" src="https://github.com/user-attachments/assets/b214b0d1-5c55-49d1-af10-576a573029d7">. 

Only the one with "device_tracker" in the name contains any data; the rest simply say: "This device has no entities". So, now I'm confused:

1. Why are the old (empty) iPhone devices showing up, even if they have no data (and I deleted the old configuration file)?
2. What name should I be using for adding new (replacement) devices? Should it contain the prefix "device_tracker."?

Also, it claims I need to do a browser refresh for the latest log file monitor, but Ctrl-Shift-Del on a MacOS does nothing. The browser is Safari.

**Comment by gcobb321** [comment]
I would suggest reviewing the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring?id=step-32-icloud3-devices-screen ) for info on adding devices. You may also want to review some of the other chapters in the docs. 

Some on it is out of date, it is v 3.0, and some screens have changed but it will explain a lot. You can click the (?) icon on the _Event Log_ go also get there

**Comment by Remcovf** [comment]
I give it up...

Deleted all maps, from HACS, from Intergrations.. Restarted severel times.

Downloaded the new version 3.1.3 via HACS, then started the intergration and try to configure a new account...

0 - 0 devices and no password is send.

I restore a back up and shut the PC down.

My phones are at home so the automations at home work. Only not when we are away.

**Comment by NR3Y** [comment]
Working ! Yea!
I had to disable the old phones that were listed and re-add them again. After that, it looked iffy as none of the entities were showing up, so I completely renooted (not restarted) my HA Yellow box and all the entities are now present.

**Comment by NR3Y** [comment]
Ooops. I think I closed MY issue, but I may have closed the thread. Apologies to anyone else on it.

**Comment by gcobb321** [comment]
This is probably fixed in v3.1.4. Create a new issue if you encounter this problem again.
