### ISSUE TITLE
Distance shown in miles even though HA is set to kilometres

### ISSUE THREAD

**Issue by stormshaker** [gcobb321/icloud3_v3#365]
iCloud3 v3.1.3 is displaying distance attributes in miles, however HA is set to use kilometres for distances.

![image](https://github.com/user-attachments/assets/9001d8e3-7cac-4c22-880f-eb2a0ebc247a)

![image](https://github.com/user-attachments/assets/7b523f25-0345-4891-90ed-571b3adc2e59)

**Comment by gcobb321** [comment]
Well. Go to _Configure Settings > Page 2 > Format Parameters_ screen and you can change it.

**Comment by stormshaker** [comment]
Ha! So you can. Thankyou!
