### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by maxm77-RC** [gcobb321/icloud3_v3#371]
Hi Gary - thanks again for all the efforts the other day. I'm not sure if this is related but I get this in my log.

Everything _seems_ to be working but not sure what this means.
Any pointers? 
Many thanks
Max

This error originated from a custom integration.

Logger: custom_components.icloud3
Source: custom_components/icloud3/helpers/messaging.py:497
integration: iCloud3 v3 (documentation, issues)
First occurred: 10:14:15 (25 occurrences)
Last logged: 11:15:06

iCloud3 Error > Error extracting device info from Apple Acct data, Device-Max iPhone (iCloud3) (max_iphone_icloud3), AppleAcct-. iCloudName-

**Comment by maxm77-RC** [comment]
By way of an update, I now get this every few seconds. I'm not sure this is giving much info but hopefully it's a known issues?

Many thanks.

2024-11-19 17:34:40.794 ERROR (SyncWorker_16) [custom_components.icloud3] iCloud3 Error > Error extracting device info from Apple Acct data, Device-Max iPhone (iCloud3) (max_iphone_icloud3), AppleAcct-. iCloudName-

**Comment by gcobb321** [comment]
It looks like the Apple account is not set up for max_phone _icloud3. Go to _Configure > iCloud3 Devices_ screen > _Select Device_ and verify the configuration for the Apple Acct field

**Comment by maxm77-RC** [comment]
Thanks. The strange thing is that it's working. It's the main family account and tracking of all the phones in the family is working.

The only thing that was not set correctly was the linking "Apple account iCloud device". It was set to none.

Could this have been the reason?

Thanks

Max Mlinaric
07931 505 330

**Comment by maxm77-RC** [comment]
Thank you - sorted :-)
