### ISSUE TITLE
Is it possible to track tags such as pebblebee?

### ISSUE THREAD

**Issue by jstride** [gcobb321/icloud3_v3#373]
They don't appear in the drop down, but do in the app on the iPad.

**Comment by gcobb321** [comment]
Apple AirTags can not be tracked. They do not contain the hardware an iPhone out iPad device does and Apple does not provide location info for them.

**Comment by jstride** [comment]
Thanks @gcobb321 - I guess they must provide the 'last location' via an internal/apple-only API in the iOS apps as it's not available on the icloud site.
