### ISSUE TITLE
3.1.3 Cannot Login

### ISSUE THREAD

**Issue by easez88** [gcobb321/icloud3_v3#374]
I cannot log in for my life after first install. No errors in logs, The event log  simply says Initial Installation configuration required. I always get incorrect  username and password. No matter what. I've reinstalled, changed my password,  used an app password nothing works. Can someone give me some guidance.

**Comment by gcobb321** [comment]
Apple reverted to the old way of validating passwords. v3.1 no longer works. Reinstall v3.0.5.9 from HACS and reelect Family Sharing on the _Configure > Data Sources-Apple Accts & MobApp _ screen

**Comment by gcobb321** [comment]
This is fixed in v3.1.4
