### ISSUE TITLE
Apple Devices not found

### ISSUE THREAD

**Issue by Holck1971** [gcobb321/icloud3_v3#377]
Hi, 
is there a new problem with Apple Login? 
Since Saturday my devices have not been found and tracked despite the correct login. 
Before it works correct...
What can I do?

<img width="475" alt="Screenshot by Snip My on 25 11 2024, 09 26 24" src="https://github.com/user-attachments/assets/f424e7ef-b93b-43d6-9faa-bd29537c6365">

**Comment by gcobb321** [comment]
This is fixed in v3.1.4
