### ISSUE TITLE
Duplicate FamShr device found

### ISSUE THREAD

**Issue by bpennypacker** [gcobb321/icloud3_v3#379]
Let me start by saying that I recently downgraded to version 3.0.5.9 in order to address the login issue. While we were traveling recently my wife had her iPhone stolen, and we immediately erased it remotely and disabled it in iCloud as well as with our mobile provider. We were told by multiple people to keep the stolen phone in our Apple account so that the thieves can't reactivate it. The employees at our local Apple Store reiterated this when we picked up a new iPhone for her. So now in icloud.com, the Find My app, etc. I see two phones both named `Heather's iPhone`, and this is apparently triggering the `Duplicate FamShr device found` error I see in the iCloud3 logs. The stolen phone shows up in icloud.com as both Erased and Offline, so it's clear there's some way of distinguishing between the two. Unfortunately I can't rename the stolen phone now or do anything else with its entry other than deleting it.

Is there any way iCloud3 can ignore the erased/offline phone? Or am I just stuck with either deleting the stolen phone from our account, or using a different name for my wife's new phone?

**Comment by gcobb321** [comment]
@bpennypacker 
Change the name of the new phone. Then select that on in the _Configure > iCloud3 Devices > Select > Update Device_ screen as your wife’s Apple account device

**Comment by bpennypacker** [comment]
Thanks, changing the name of the phone did indeed clear the error. Curiously enough I didn't actually need to reconfigure anything in iCloud3. By the time I got to the _Update Device_ screen it was already showing that it was tracking the correct phone.

**Comment by gcobb321** [comment]
iCloud3 stores three Apple devices And checks to see if the name was changed on the phone. If it was, the Apple name is updated to the new name
