### ISSUE TITLE
Issues with Apple ID login (Connection Error 503) and 0 of 0 iCloud Devices Tracked

### ISSUE THREAD

**Issue by anhell** [gcobb321/icloud3_v3#383]
Hello, I' have been trying for hours to set iCloud3 up, it's the latest version, 3.1.3.
I followed the New Installation Guide, got HACS set up, installed iCloud3 and HA Mobile App. I'm using Home Assistant OS.

Right now I'm trying to set up my Apple ID, Integrations > iCloud3 > Configure > DATA SOURCES > ADD A NEW APPLE ACCOUNT
I'm able to enter my info and I think it's doing its thing, because I tried a wrong password on purpose and it returned an error, but it always say 0 of 0 iCloud Devices Tracked and I have devices to be tracked on my iCloud account, if I try to request a verification code it never arrives, not on my iPhone, not on my e-mail... on the event log it always says Failed to log into the Apple Account (Connection Error 503), will retry every 15-minutes (but I don't know if it will really retry, I left it for an hour and no more events were registered in the event log), with luck after restarting Home Assistant OS I will get Apple Acct > Setting up account, but I don't know what it means and again nothing happens after, I don't now what else to do.

I'm thinking about how can I clear all cache from iCloud3 and start over, but I couldn't find anything, when I reinstall it, somehow it always have my previous config, also thinking about trying without the MA Mobile App.

At some point this message also appeared "The configured device was not found in any of the Apple Accounts", but I've been trying for so long I forgot where exactly.

Any guidance will be appreciated.

**Comment by JtwoA** [comment]
Rollback to v3.0.5.9.  You'll see all sorta threads about Apple's nonsense with changing their login process.

**Comment by gcobb321** [comment]
This is fixed in v3.1.4
