### ISSUE TITLE
iCloud v3 - How to fallback to iCloud location when iOS App is not connected

### ISSUE THREAD

**Issue by tyanai** [gcobb321/icloud3_v3#388]
Hi,

I'm using the latest version (3.1.4.1), but I've noticed this issue previously as well. It appears that when I select both HA and iCloud as data sources for family members, they need to keep their HA App open at all times for the location tracker to update.

Did I overlook any specific configurations?

Thanks,

Tal.

**Comment by gcobb321** [comment]
Make sure location sharing for the app is set to Always. The mobile so also has a Periodic Update Interval on its Configuration page. I have mine set to 5-mins.  

 If the app is asleep like it is in the middle of the night, no location updates will be sent by the mobile app. It will send them when running in the background.

**Comment by tyanai** [comment]
Thanks Gary, I'm aware of that and all is working well.

My question is different:
What are the option to not use the iOS HA App at all?  Is all I need to do it to untick the "HA Mobile App" from the Data Source selection?

**Comment by gcobb321** [comment]
Yes, disable the Mobile App as a data source and it will not be used for any device. 

The item it watch out for is zone exit triggers will no longer be issued so the device’s location will not be updated immediately when you leave a zone. It will be updated at the next update time. The inzone for the devices should be no longer than 15-mins. You could also set up an automation based on your network connection status (at home or work) and trigger a location update after you have been disconnected for 30-secs or so. Stationary zones and other zones would use the inzone interval or the Stationary inzone interval for the update trigger
