### ISSUE TITLE
2FA by hardware token - ios 16.3

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#39]
Not sure if you are aware, but from ios 16.3 2FA by hardware token becomes a possibility.
This replaces the 6 digit 2FA code process.

Do you have any way of supporting this ?

Thanks

**Comment by gcobb321** [comment]
This is the first time I have heard about this and will look into it. I’m running 16.2 on my phones. 

I’ll look at the b8b zip file later to make sure the country_code issue is correct.

**Comment by gcobb321** [comment]
I dug into this and It appears it is for allowing access to the device like facetime or a passcode does. Since iCloud3 is a program, not an app. I don't think it will apply.

**Comment by B-Hartley** [comment]
The reason I thought it was relevant was that it disables the 6 digit code 2FA process.  
when accessing iCloud.com on the web. Or login into iCloud account on the phone it asks for the token rather than sending a 6 digit code to another device. 
Now I’ve got the beat up and running. I’ll experiment with it and see if it causes a problem with iCloud3 authenticating.

**Comment by gcobb321** [comment]
When you enter the 2fa code in ic3, you are actually authenticating the device running HA, not the phone. In my case, it’s an RPi. I can enter the code on my phone or iPad thru the ios app (acting like a browser) or on my windows computer thru a web browser (Google, edge). But the cookies and session Authentication tokens are on the RPi. What I think that would mean is the hardware authentication device would need to be tied to the RPi and HA, not the phone.

**Comment by B-Hartley** [comment]
Yes, this is why I was assuming it would cause a problem.
I'll have a play and see what happens.
