### ISSUE TITLE
Cannot choose a zone other than home when zones defined in yaml

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#41]
Hi,

I want to track some devices back to a different zone, not home.
I have multiple home assistant zones setup, but I cannot choose them from the config flow in home assistant ?
Am I missing something?

Great work on the config screens btw, definitely the most complex config flow screens I have ever seen !!

**Comment by gcobb321** [comment]
There is a 'Primary Home Zone'; field on the Update iCloud3 Devices screen where you can designate another as the one you want to track from. It will act as the primary zone for that device. See if that will work.

![image](https://user-images.githubusercontent.com/35449479/212930621-ee259e2e-9d4f-44d4-8dc9-beea6113ef53.png)

**Comment by B-Hartley** [comment]
That list doesn't show any other zones than "Home"
I have added the zones.py and the other two files from the other zones thread. I still don't see any understanding of zones from icloud3?

All trackers are either home or not_home. they are are not showing in the zones they should ?

Any debug I can send you to help look into this ?

**Comment by B-Hartley** [comment]
My zones are created through a yaml file.
I just created one through the UI and icloud3 now knows about it.

**Comment by gcobb321** [comment]
When iC3 , the HA zone entities are loaded into it's internal tables. They are shown in the Event Log in Stage 1. With Debug logging on, the following is in the icloud3-debug.log file:
![image](https://user-images.githubusercontent.com/35449479/212933258-430f0d58-f340-4e3c-a3e2-d02f4eaf2abb.png)

2. Rawdata debug logging expands the information to show what is being loaded from HA:
![image](https://user-images.githubusercontent.com/35449479/212934093-5c290125-c778-4165-bac4-5238b0761de2.png)

**Comment by gcobb321** [comment]
Good to know. I'll create one using yaml and see what the difference is.

**Comment by gcobb321** [comment]
This must have been fixed somewhere
