### ISSUE TITLE
One device location not updating (Beta 8a)

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#42]
I have a phone who's location isn't updating in IC3. It's setup as a FamShr device and in the FindMy app the location is displaying just fine. It seems to be just this one device - I have other FamShr devices in my account that are updating just fine.

icloud3 says:

![image](https://user-images.githubusercontent.com/38404530/212968065-c148e890-3096-496a-93b4-9d93c7a1faa1.png)

and, even after restarting and forcing a location refresh:

![image](https://user-images.githubusercontent.com/38404530/212969326-cd23af2f-1da9-4989-bda0-d3b820620921.png)

(As an aside, I notice the log says CountryCode-US, even though I've set Waze to be RoW and my HASS setup is set for UK/GB).

**Comment by derekoharrow** [comment]
I think this might have been caused as I tried changing the Zone Name Format. Changing it back to HA Format seems to have resolved it.

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Reopen this issue if you are still having problems after installing and using it.

Gary

**Comment by derekoharrow** [comment]
This is still happening with Beta9. One device still says it's home, but the FindMy app recognises that the phone isn't home.

This is a FamShr device.

I tried doing an Update Location at 09:24. Results below.

![image](https://user-images.githubusercontent.com/38404530/214005340-c721e332-8df6-4991-8469-a2e9bc01f952.png)

**Comment by gcobb321** [comment]
Set log level Rawdata (Configuration > Event Log >Log Level), restart ic3 let it run until the phone is not located and send me the icloud3-debug.log file. 

Also, the headings on the screenshot are shifted to the right. What are you displaying it on?

**Comment by derekoharrow** [comment]
> Set log level Rawdata (Configuration > Event Log >Log Level), restart ic3 let it run until the phone is not located and send me the icloud3-debug.log file.
> 
> Also, the headings on the screenshot are shifted to the right. What are you displaying it on?

Will do.

Re the screenshot - that happens as soon as I make the HA window wider then a certain width.

**Comment by derekoharrow** [comment]
GRRRRRR - Bloomin' kid!

Looking at the log and it says:

` STAGE 5 >  Tracked Device > ryans_iphone_ic3 (Ryan's iPhone (IC3))   •  FamShr Device: iPhone X (NOT IN FAMILY SHARE LIST)`

So, basically, the little 'angel' has turned it off! I've changed it to a FmF device instead of FamShr and it's picked it up instantly!

Should devices use both FmF and FamShr if it's possible? Does this cause any issues?

Thanks for your continued help!

**Comment by derekoharrow** [comment]
Hmmm. Interesting - he hasn't turned off Family Sharing, but the log is saying it is off...

**Comment by gcobb321** [comment]
So he doesn’t want daddy to know where he is all the time. Sounds like a regular kid. How old is he? At least now you the first place to look when Silvie or Lauren stop tracking. 

A mixture of FamShr and Fmf work well together. Since it gets all device locations on a location update, it can use info from both data sources, the latest location is selected. You will see the times and what was selected in the Event Log

**Comment by gcobb321** [comment]
Now that b9 is out, I'm going to close this to keep things tidy. Open a new issue if it continues in b9.
