### ISSUE TITLE
Location updates slow

### ISSUE THREAD

**Issue by chupacabra71** [gcobb321/icloud3_v3#44]
Not sure if it is a configuration issue or something else, but it seems that my devices don't update nearly as fast on v3 as compared to v2.  the reason i noticed is when i take the dogs for a stroll, i would get a notification that i left home almost as soon as i was about a block away from the house.   now that same alert does not happen until about 6-7 blocks away.  Not sure what I can look at to see what may be causing the issue.

**Comment by gcobb321** [comment]
Look at the Event Log to see what the intervals are, if the iOS App is triggering exits that are getting picked up, if there are location errors and retries. Normally, when the zone is exited, the next update will be in 4-minutes.

**Comment by gcobb321** [comment]
Now that b9 is out, I'm going to close this to keep things tidy. Open a new issue if it continues in b9.
