### ISSUE TITLE
Device Tracker not updating person entity with zone ?

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#45]
I have the IC3 device tracker assigned to a person so that person can be located.
The zone name doesn't seem to be passing from the device tracker to the person ?

It will just show "Home" or "Unknown" instead of the zone name, it worked correctly on the released (non beta) icloud3.

Am I doing something wrong ?

**Comment by gcobb321** [comment]
Unzip this into the icloud3 directory, restart HA and see if it takes care of your problem

[zone.zip](https://github.com/gcobb321/icloud3_v3/files/10447650/zone.zip)

**Comment by B-Hartley** [comment]
Still the same problem, I think it might be a case issue.
device_tracker.sophie_iphone_ic3 : oaktree
device_tracker.sophie_iphone_app: Oaktree

person.sophie -> which follows ic3 one, shows unknown.

**Comment by B-Hartley** [comment]
It is set to that option already ?

**Comment by gcobb321** [comment]
Go to Developer Tools > States, scroll to the bottom and see what the zone's Friendly Names are and if they are capitalized or not capitalized. Also see Stage 2 and see if it zone/fname and shows how the zone is displayed in the Friendly Name field. With capitalization and spacing. If it shows the same as the 'name', it may be running the old 'zone.py' module.

![image](https://user-images.githubusercontent.com/35449479/213267782-d0cd4f5e-9b04-490e-bf00-f2901d01e308.png)

**Comment by B-Hartley** [comment]
The friendly names have capitals at the front:
The stage 2 has capitals at the front:

**Comment by B-Hartley** [comment]
I can't upload the image, but is shows fnames with capitals.

**Comment by B-Hartley** [comment]
I think the case issue is a red herring.
I've renamed the zone so its name and its friendly names are "sycam"
ic3 location shows as sycam.

But the person. entity is not being updated with the zone info ?

**Comment by gcobb321** [comment]
iCloud3 doesn’t do anything anything with the person entity. That it’s strictly HA. I’ll set one up for myself and see if I have any issues. 

My understanding from reading something a while ago is that it will take several device tracker state values and use them to determine if a device is in a zone. If that is true, doesn’t the iCloud3 device tracker do that? If that is true, shouldn’t you use the iCloud3 device tracker zone and not use person. Maybe the person is meant to be used if you are only relying on beacons, routers, proximity located, etc to know where you are. I don’t know since I haven’t used it.

**Comment by B-Hartley** [comment]
Normally. Any device tracker that is linked to a person will make that person show the zone that the device tracker shows. 

it worked fine with iCloud3 v2. 

I’ll try and figure out what it doesn’t like.

**Comment by marceloaf** [comment]
Comparing the devices from version 2.4.7 to 3beta8 I see the fields below are different:

**Version 2.4.7:**
![image](https://user-images.githubusercontent.com/11551691/213464070-b925173b-6b65-4cb6-9519-5bde49cbe461.png)

**Version 3beta8:**
![image](https://user-images.githubusercontent.com/11551691/213464700-6d42792f-cdec-4990-ad53-fdda954f6914.png)

------

I also noticed that when the ic3 device is in a known zone, the person entity shows it as unknown but when it is Away, the person entity reflect is status correctly as Away:

![image](https://user-images.githubusercontent.com/11551691/213460523-b097a934-b4cb-4f2a-b87f-c9b09e441116.png)

**Comment by B-Hartley** [comment]
in device_tracker.py, I changed the relevant lines to:

```
    @property
    def source_type(self):
        """Return the source type, eg gps or router, of the device."""
        return "gps"
```

the person entity, then behaves as expected.

According to const.py in Home Assistant, the only valid values for the source_type field are.........

```
class SourceType(StrEnum):
    """Source type for device trackers."""

    GPS = "gps"
    ROUTER = "router"
    BLUETOOTH = "bluetooth"
    BLUETOOTH_LE = "bluetooth_le"
```

**Comment by gcobb321** [comment]
I changed the Source type to 'gps' and added a 'Data source' attribute with the FmF/Famshr (iCloud3)' value.
