### ISSUE TITLE
Distance Sensors in wrong Locale

### ISSUE THREAD

**Issue by kingy444** [gcobb321/icloud3_v3#48]
Distance Sensors are appearing in Miles and not m / kM as i would expect for my HA instance configuration

All the configuration options have km as the setting, but the sensors created for devices are showing miles

![image](https://user-images.githubusercontent.com/7148670/213960743-6916fc17-2d06-41e0-a88b-a3c1cc98824c.png)

![image](https://user-images.githubusercontent.com/7148670/213960818-72a00ff0-09f7-48fb-ab16-7652abd5b8e0.png)

**Comment by gcobb321** [comment]
That can be set on the configuration > Event Log Parameters screen. Do you have Imperial or Metric for the Unit of Measurement?

**Comment by kingy444** [comment]
Thanks.

I did look for it under 'other parameters' on page 2 - didnt think to look in the Event Log page, maybe there is a better place for it ? I can see it written on the 'things on this page' section but i never read thouroughly given the title of the page (made me focus on its purpose)

Additionally - Could you maybe do a check for which country the OS is set to and default to KM for anywhere else in the world 😄 
I believe only 3 countries use miles still ?

**Comment by gcobb321** [comment]
It would be simple to have it in both places. The other options screen has items that almost never get changed. Do you think that changing that screen to one that has all of the parameters in alphabetical order makes sense? Or create one more screen with everything?

. The UM i is converted from the v2.4 config if you were running ic3 before or from the HA setting on new installs.

**Comment by kingy444** [comment]
This was a brand new installation 

I thought you could be able to get the country code from the actual HA instance itself (though I have not dug for that property myself)

I don’t know you want another whole config screen, I think it’s better for everything to have it’s home as to not confuse people too much. I did look at the v3 doco too but didn’t see anything about the locale

Maybe it makes more sense to be in the ‘SENSORS’ -> DISTANCE SENSORS section as it relates to those?

**Comment by gcobb321** [comment]
By brand new installation, I meant when the Configuration file was first initialized. It looks at the HA ‘use metric’ value when the config file is created but not after that. Will consider looking at the HA value it each time

**Comment by kingy444** [comment]
HA locale would have been AU the whole time (one of the first things you set up) but I did have that bad beta 8 with the country code issue as my first install so perhaps it failed there?

it seems that even after a removal not all elements are removed (raised an issue re credentials for that) but if there are other elements related to locale stored too I would say removal should remove all and not just the display

I don’t think you need to do it every time the ic3 add in is loaded

**Comment by gcobb321** [comment]
FYI- On a removal of the Integration, the configuration files are also not removed in case of a reinstall to avoid setting it up again. I’ve make a note of the iCloud account cookies. I’ve also left them, as you know for the same reason. I’ve tried to remove all device tracker and sensor entities. HA actually doesn’t remove them but puts them in a deleted status in the entity r Registry and will restore them on a reinstall. It may delete them after a period of time but i have not seen that.

**Comment by gcobb321** [comment]
Not that b9 is out, I'm closing this for now just to keep things tidy. Open another issue if needed.
