### ISSUE TITLE
I am having some basic issue getting the component to work.

### ISSUE THREAD

**Issue by hvddrift** [gcobb321/icloud3_v3#5]
I have installed everything and set up one device. However....

STAGE 4 > SETUP ICLOUD & IOSAPP TRACKING METHODS, RETRYING ICLOUD DEVICE SETUP
UNTRACKABLE DEVICE ALERT > DEVICES ARE NOT BEING TRACKED:
•HANS_IPHONE_ICLOUD, HANS IPHONE ICLOUD/IPHONE
━━━━━━━━━━━━━━━━━━━━
THIS CAN BE CAUSED BY:
•ICLOUD3 DEVICE CONFIGURATION ERROR -- NO ICLOUD (FAMSHR/FMF) DEVICE AND NO IOS APP DEVICE HAVE BEEN SELECTED, OR

![chrome_m68NrfYH8z](https://user-images.githubusercontent.com/972926/208297500-61d27b0d-0a53-4aa1-acb1-a622ded235cc.png)

And for some reason my lovelace card look like this (event log is not loading)

![chrome_fWGEM3uGxl](https://user-images.githubusercontent.com/972926/208297501-6440c017-3d26-4194-a39e-0765b2b4bb4f.png)

**Comment by gcobb321** [comment]
Beta 2 has been posted. You will find it [here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-2)
