### ISSUE TITLE
HA doesn't recognize fmf ic3 devices inside zones

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#50]
Hi, good morning. The issue persists on beta 9...

**Beta 9:**
![image](https://user-images.githubusercontent.com/11551691/214037434-1ec37e97-8e2b-4732-854c-984bce2822ce.png)

![image](https://user-images.githubusercontent.com/11551691/214038109-c1c49c77-67f3-44a1-af96-a9237d1392d5.png)

**versus v2.4.7:**
![image](https://user-images.githubusercontent.com/11551691/214037655-68501b8f-c65e-4617-8e81-97f2d5267fc5.png)

![image](https://user-images.githubusercontent.com/11551691/214037982-5c361eb4-da6a-42bf-817e-4c58d1a4421a.png)

_Originally posted by @marceloaf in https://github.com/gcobb321/icloud3_v3/issues/36#issuecomment-1400254485_

**Comment by gcobb321** [comment]
Right now, I am using FamShr and ios app, My wife is using FmF and iOS App. We are both Home and it shows 2 people in the Home zone and lists them in the person attribute. She was out to lunch and in the Quail zone and it showed one person at home (me) and one at Quail (her). I could not tell if that was coming from FamShr, FmF or the iOS App.


I set up the persons for each of us and did have to go to the zone and update the quail zone, it was showing Quail but it didn't look like it was displaying it correctly (quail instead of Quail) so I set it as Quail. I went back to iC3 and saw I had the 'name' selected for the Event Log Zone format, I changed it to the HA Zone friendly name and then she showed up in the Quail zone person count. Changing the Zone Format may not have mattered. 

I have not used the person.entity before and will see what happens if I do not associate the iOS App with it.

**Comment by gcobb321** [comment]
I fixed a problem where the non-numeric sensors were not showing in the History correctly (HA thought they were numbers instead of text because the unit_of_measurement for text sensors was wrong). I don't know if it has anything to do with the person issue but here it is just in case,

Unzip it into the /config/icloud3 directory and restart HA.

[sensor.zip](https://github.com/gcobb321/icloud3_v3/files/10494697/sensor.zip)

**Comment by marceloaf** [comment]
Hi Gary, how are you? I still think there is a bug somewhere and, unfortunately, I’m not being able to explain/show it to you. Maybe because of the language barrier...
I noticed that, no matter which option you choose in the Zone Name Format, the zones are being shown the very same way.  In all the images below you can see that despite of the zone name format, the home zone is shown with capital (probably the friendly_name) and the other zones like the entity_ids. Between evey change on the zone name format I restarted icloud3 to make sure the change was being recognized:


  1.  Equivalent to fname in v2.4.7
[Graphical user interface, text, application, email  Description automatically generated]
[Graphical user interface, text, application  Description automatically generated]




  1.  Equivalent to zone in v2.4.7

[Timeline  Description automatically generated]
[Graphical user interface, text, application  Description automatically generated]




  1.  Equivalent to name in v2.4.7
[Graphical user interface, text, application, email  Description automatically generated]
[Graphical user interface, application  Description automatically generated]



  1.  Equivalent to title  in v2.4.7
[Timeline  Description automatically generated with medium confidence]
[Graphical user interface, text, application  Description automatically generated]

I chose one of the zones to make an experiment. I changed the zone entity id from zone.casa_da_lena to zone.lena and the Friendly Name from Casa da Lena to Lena. This was the only way HA could  “recognize” fmf ic3 devices inside the zone. See below:
[A picture containing graphical user interface  Description automatically generated]

If I change the zone name OR the zone entity_id back to more than 1 word, it doesn’t recgonize it as inside the zone.... ☹
[A picture containing graphical user interface  Description automatically generated]




In v2.4.7 if I play around with the zone_display_name the results are consistent as shown below:
display_zone_format: fname
[Graphical user interface, text, application, chat or text message  Description automatically generated]



display_zone_format: zone
***@***.***



display_zone_format: name
[Graphical user interface, text, application, chat or text message  Description automatically generated]



display_zone_format: title
[Graphical user interface, text, application, chat or text message, Teams  Description automatically generated]


In version 2.4.7 if I use the zone_friendly_name as fname or title the devices are correctly recognized inside the zone. The image below I’m using as title

***@***.***


Thanks in advance
Marcelo

**Comment by marceloaf** [comment]
Hi Gary, how are you? I still think there is a bug somewhere and, unfortunately, I’m not being able to explain/show it to you. Maybe because of the language barrier... 

I noticed that, no matter which option you choose in the Zone Name Format, the zones are being shown the very same way.  In all the images below you can see that despite of the zone name format, the home zone is shown with capital (probably the friendly_name) and the other zones like the entity_ids. Between evey change on the zone name format I restarted icloud3 to make sure the change was being recognized:

1.	Equivalent to **fname** in v2.4.7
 ![image](https://user-images.githubusercontent.com/11551691/214925460-4ad2442e-55ce-484e-bd18-4a4f70e68b50.png)
![image](https://user-images.githubusercontent.com/11551691/214925563-7e4651f4-c0e0-4c7a-b846-9aaa27ec516a.png)

 
2.	Equivalent to **zone** in v2.4.7
![image](https://user-images.githubusercontent.com/11551691/214925637-9d4aded1-603e-49f1-9781-39ec6c4b90f4.png)
![image](https://user-images.githubusercontent.com/11551691/214925665-d077b55f-9c17-401d-bda2-b8a08c2e9ad5.png)


3.	Equivalent to **name** in v2.4.7
 ![image](https://user-images.githubusercontent.com/11551691/214925714-82037570-7cb0-46ac-8025-b73528c4e6ed.png)
![image](https://user-images.githubusercontent.com/11551691/214925749-fe4a5f67-fc15-4774-b241-e817c2e7e2fd.png)


4.	Equivalent to **title**  in v2.4.7
 ![image](https://user-images.githubusercontent.com/11551691/214925807-9e7f9f8b-fb23-4ef6-af0a-1e653afe2fe0.png)
![image](https://user-images.githubusercontent.com/11551691/214925839-b2f6601f-3264-43ef-b72e-f19216ddd56e.png)



I chose one of the zones to make an experiment. I changed the zone entity id from zone.casa_da_lena to zone.lena and the Friendly Name from Casa da Lena to Lena. This was the only way HA could  “recognize” fmf ic3 devices inside the zone. See below:
![image](https://user-images.githubusercontent.com/11551691/214925916-d30a8d98-55f6-45ae-93db-53248c3a8e89.png)
 

If I change the zone name OR the zone entity_id back to more than 1 word, it doesn’t recgonize it as inside the zone.... ☹
 ![image](https://user-images.githubusercontent.com/11551691/214925962-0a2817a6-b715-4a47-9fa2-98b1afdf7c45.png)



In v2.4.7 if I play around with the zone_display_name the results are consistent as shown below:
**display_zone_format: fname**
![image](https://user-images.githubusercontent.com/11551691/214926006-1ed786aa-7ca0-487d-b62f-7ebb12c176bb.png)

 
**display_zone_format: zone**
![image](https://user-images.githubusercontent.com/11551691/214926048-b3635b17-0bcb-4e31-bb99-5cb8ab78590e.png)


**display_zone_format: name**
![image](https://user-images.githubusercontent.com/11551691/214926095-1adc5374-5dae-49a2-9ea0-526af8c52a55.png)


**display_zone_format: title**
![image](https://user-images.githubusercontent.com/11551691/214926144-1bead0c8-99b9-4200-8608-97d8d2254136.png)



In version 2.4.7 if I use the zone_friendly_name as **fname** or **title** the devices are correctly recognized inside the zone. The image below I’m using as title
![image](https://user-images.githubusercontent.com/11551691/214926199-8448e81e-2c3c-470e-8885-b7602895cb33.png)


Thanks in advance
Marcelo

**Comment by gcobb321** [comment]
OK. I set up everything like you . Even moved my home zone and set up a Casa de Test. Yes, there was a bug. It was in v2.4.7, not v3. It is recommended by HA that all state values be lower case with underscores ('_') for spaces, just like entity names. v2.4.7 did not follow this standard, v3 does, or there is a new option to follow it or not follow it. You can now decide.

I added an option on the Event Log Parameters screen to use the Zone format selected for the Event Log or to follow the HA standard. It is in b10 which I am going to upload tomorrow.

**Comment by marceloaf** [comment]
Ok, thanks for taking a look into this. So, if I understand correctly, now v3 will honor the Zone Name Format, right?

Best regards,
Marcelo

**Comment by gcobb321** [comment]
Yes. There is new option on the Event Log Parameter screen. You can select to override the HA format and use the zone name format you are using on the Event Log. I hope to have it out later today.

**Comment by marceloaf** [comment]
Working now! Thanks!!

![image](https://user-images.githubusercontent.com/11551691/215289091-03cabd26-0a14-4edb-bc9c-3d4400023421.png)
