### ISSUE TITLE
Restart seems to log a 0,0 type location ?

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3_v3#58]
Just did a restart icloud3.
When I look at a map it now shows everyone having visited a point that I assume is 0,0 on the map.

![image](https://user-images.githubusercontent.com/30037005/216299941-720f6df4-13be-4d08-8c04-5cf1483ca995.png)

**Comment by gcobb321** [comment]
Yes that is 0,0. A nice boat would be nice. It would be getting picked up from the last/long values on the device tracker entity. I’ll add a check nd not do a device tracker update if it 0, 0.. can you tell if it ihappened right after an update, HA restart or some other event?

**Comment by kamkilt** [comment]
I'm getting same behaviour, right after iCloud3 restart (during all the startup processes) after iCloud3 will update position from iCloud position is getting back to normal.

**Comment by B-Hartley** [comment]
It was an iCloud3 restart in this case. 
could be other reasons to I guess.

**Comment by gcobb321** [comment]
The state values were being restored to the last saved state but not the attributes. The map uses the lat/long attributes  from the device_tracker entity to get the location. I'll fix that.
