### ISSUE TITLE
Can't set pass-through zone interval

### ISSUE THREAD

**Issue by pauly7300** [gcobb321/icloud3_v3#61]
I don't see the ability to change the delay for the pass-through zone delay any longer.  I saw a note on beta 10 that you had made it easier to turn off but I no longer see an ability to set a delay time like documentation shows [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.0-config-parms?id=configuration-parameters-github-commit). 

Also, the reason I want to try and set the interval is because my wife's phone is with her at work but it still is showing that it may be in a passthrough zone.  I increased the size of the zone a little and it seems to be showing correctly now.  I haven't noticed this behavior in that zone in the past but it's very possible that it has been doing it even in V2.4 and I never noticed it.  

This is what I see now.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/11494052/217034224-925e4e53-7f0a-4140-b3fc-a0948414d282.png">

**Comment by gcobb321** [comment]
I'm seeing it on mine. Does it show if you refresh your browser?

**Comment by gcobb321** [comment]
And you are on b11?
Line 263 in icloud3/translations/en.json (2/6 file date)  contains the field name for the passthru time. It should be:
```
"passthru_zone_time": "ENTER ZONE DELAY TIME - Delay processing a Zone Enter Trigger in case you are passing thru a zone",
```

**Comment by FredWst** [comment]
I'm in the same case with b11, line 263 is ok.

![Capture d’écran 2023-02-07 à 19 22 49](https://user-images.githubusercontent.com/41281764/217332515-1714fb03-72be-4315-89bb-35a4d3736fbb.png)

` {
    "profile": {
        "version": 1,
        "ic3_version": "3.0.0b11",
        "config_update_date": "2023-02-07 19:02:30",
        "event_log_card_directory": "www/custom_cards",
        "event_log_card_program": "icloud3-event-log-card.js"
    },
    "data": {
        "tracking": {
            "username": "removed",
            "password": "«removed»",
            "encode_password": true,
            "icloud_server_endpoint_suffix": "",
            "setup_icloud_session_early": true,
            "data_source": "icloud,iosapp",
            "devices": [
                {
                    "ic3_devicename": "frederic_iphone",
                    "fname": "Frédéric",
                    "picture": "www/icloud3/Frédéric.jpg",
                    "evlog_display_order": 0,
                    "unique_id": "",
                    "device_type": "iphone",
                    "inzone_interval": "00:04:00",
                    "tracking_mode": "track",
                    "famshr_devicename": "frederic_iphone",
                    "famshr_device_id": "removed=",
                    "raw_model": "iPhone12,8",
                    "model": "iPhone",
                    "model_display_name": "iPhone SE",
                    "fmf_email": "None",
                    "fmf_device_id": "",
                    "iosapp_device": "frederic_iphone_2",
                    "track_from_base_zone": "home",
                    "track_from_zones": [
                        "home"
                    ],
                    "stat_zone_fname": "Stationnaire",
                    "old_devicename": "frederic_iphone"
                },
                {
                    "ic3_devicename": "pascale_iphone",
                    "fname": "Pascale",
                    "picture": "www/icloud3/Pascale.jpg",
                    "evlog_display_order": 0,
                    "unique_id": "",
                    "device_type": "iphone",
                    "inzone_interval": "00:04:00",
                    "tracking_mode": "track",
                    "famshr_devicename": "pascale_iphone",
                    "famshr_device_id": "removed",
                    "raw_model": "iPhone13,1",
                    "model": "iPhone",
                    "model_display_name": "iPhone 12 mini",
                    "fmf_email": "None",
                    "fmf_device_id": "",
                    "iosapp_device": "pascale_iphone_2",
                    "track_from_base_zone": "home",
                    "track_from_zones": [
                        "home"
                    ],
                    "stat_zone_fname": "Stationnaire",
                    "old_devicename": "pascale_iphone"
                }
            ]
        },
        "general": {
            "log_level": "info",
            "unit_of_measurement": "km",
            "time_format": "24-hour",
            "display_zone_format": "fname",
            "max_interval": "00:04:00",
            "offline_interval": "00:20:00",
            "iosapp_alive_interval": "00:03:00",
            "old_location_threshold": "00:01:00",
            "gps_accuracy_threshold": 50,
            "travel_time_factor": 0.6,
            "tfz_tracking_max_distance": 8,
            "passthru_zone_time": "00:05:00",
            "track_from_base_zone": "home",
            "track_from_home_zone": true,
            "center_in_zone": false,
            "discard_poor_gps_inzone": false,
            "inzone_intervals": {
                "iphone": "00:04:00",
                "ipad": "02:00:00",
                "watch": "00:15:00",
                "airpods": "00:15:00",
                "no_iosapp": "00:15:00",
                "other": "02:00:00"
            },
            "waze_used": true,
            "waze_region": "row",
            "waze_min_distance": 1,
            "waze_max_distance": 9999.0,
            "waze_realtime": false,
            "waze_history_database_used": true,
            "waze_history_max_distance": 20,
            "waze_history_track_direction": "north_south",
            "stat_zone_fname": "Stationnaire",
            "stat_zone_still_time": "00:08:00",
            "stat_zone_inzone_interval": "00:04:00",
            "stat_zone_base_latitude": 1,
            "stat_zone_base_longitude": 0,
            "display_text_as": [
                "#1",
                "#2",
                "#3",
                "#4",
                "#5",
                "#6",
                "#7",
                "#8",
                "#9",
                "#10"
            ],
            "old_location_adjustment": "00:00:00",
            "distance_between_devices": false,
            "device_tracker_state_format": "fname"
        },
        "sensors": {
            "monitored_devices": [],
            "device": [
                "info",
                "badge",
                "battery",
                "name"
            ],
            "tracking_update": [
                "interval",
                "last_update",
                "next_update",
                "last_located"
            ],
            "tracking_time": [
                "travel_time",
                "travel_time_min"
            ],
            "tracking_distance": [
                "zone_distance",
                "moved_distance",
                "dir_of_travel",
                "home_distance"
            ],
            "track_from_zones": [],
            "tracking_other": [
                "trigger",
                "waze_distance",
                "calc_distance"
            ],
            "zone": [
                "zone_fname"
            ],
            "other": [
                "gps_accuracy"
            ],
            "excluded_sensors": [
                "None"
            ]
        }
    }
}`

**Comment by pauly7300** [comment]
I am on b11 and it does show the line that you referenced...
Also, it probably have nothing to do with it but notice how the dashes wrap
in that pop-over window.
[image: image.png]

[image: image.png]

**Comment by gcobb321** [comment]
The other file to check is /icloud3/config_flow.py. It is the Configurator module. The code that displays the screen is:
```
3778                vol.Optional('passthru_zone_header',
3779                           default=pass_thru_zone_used):
3780                            selector.BooleanSelector(),
3781                vol.Required(CONF_PASSTHRU_ZONE_TIME,
3782                           default=self._hhmmss_to_duration(CONF_PASSTHRU_ZONE_TIME)):
3783                            selector.DurationSelector(),
```
Does that match with what you have. If it does, refresh the browser again, I guess...
- Devices & Services > Integrations > iCloud3 Configure
- Menu Page 2 > Special Zones
- Ctrl-Shift-Del > Settings Clear Data
- Select HA Tab again > Special Zones
- Refresh browser, this will display the Integrations page again
- iCloud3 Configure
- Menu Page 2 > Special Zones
It should display.

**Comment by pauly7300** [comment]
File seems correct.  
I performed all the steps you described multiple times and still it's not showing.


<img width="837" alt="image" src="https://user-images.githubusercontent.com/11494052/217361155-5153586e-9870-425e-bdce-37e8b739acaa.png">

**Comment by FredWst** [comment]
Same for me

**Comment by gcobb321** [comment]
About the line that continues to the next line, the length is static and in the /translations/en.json file. The characters were based on the width of the screen from HA in google on windows. It will wrap to the next line if it is displayed on a smaller screen (iPad)

**Comment by gcobb321** [comment]
Unfortunately, HA and the HA frontend and browsers are running the show that displays those screens.

**Comment by FredWst** [comment]
Same issue with iPhone, iPad, will check log tomorrow (23h00 here)

**Comment by pauly7300** [comment]
> The characters were based on the width of the screen from HA in google on windows
You might just reduce the # of characters by one or two on either side to make it more compatible to different screen sizes, or you might consider removing the text based separators all together?  I edited the en.json file to do the below.  But certainly not vital.  Just an idea and doesn't seem like it has anything to do with the original issue...

<img width="595" alt="image" src="https://user-images.githubusercontent.com/11494052/217376018-a98984da-5af2-46c1-9296-ff1d6bd8c1fd.png">

**Comment by gcobb321** [comment]
I've been playing around with the formatting, number of characters, etc. It's a trial-and-error because the text is not a fixed space font so you can not line things up. The line above Action items at the bottom is the same width on google as an iPad. The difference is it just overflows the screen on an ipad. The boolean selectors prevent that from happening on the other fields. I remember a check box that sits on the left that I used a long time ago that would allow for a separator line without overflowing to the next line. I'm trying to find that code now to see if it works.

I still have no idea why the pass thru time field is not displaying.

**Comment by pauly7300** [comment]
> Try it on another device (ipad, iphone) and see if it shows up there if you are using the ios app on those devices. Are there any errors in the ha log file?

Same across all my devices (iphone, ipad) and multiple browsers (Chrome, Firefox and Safari).  

Are you saying it's working for you?  

In fact I'm also noticing that the time pickers aren't showing for other sections on this page.  
<img width="253" alt="image" src="https://user-images.githubusercontent.com/11494052/217380260-5cd6a530-1a60-4636-ad61-1e7e78d5b3f4.png">
Shouldn't these be under Stationary zone?
<img width="577" alt="image" src="https://user-images.githubusercontent.com/11494052/217380393-4f0e0526-cacd-42aa-a897-3f0bce4d96bb.png">

**Comment by gcobb321** [comment]
On my system with a different check box

![image](https://user-images.githubusercontent.com/35449479/217381319-a497f2e8-2d8c-494b-8329-26b90a8c12e6.png)

**Comment by gcobb321** [comment]
I'm on HA 2023.2.0, upgrading to 2023.2.2 now.. Maybe that will break it for me.

**Comment by pauly7300** [comment]
Peculiar that your Chrome is rendering it as an actual checkbox versus a boolean switch.  You might also update Chrome to see.  I'm on Chrome Version 109.0.5414.119 (Official Build) (x86_64).  And HA Versions...
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by pauly7300** [comment]
One other question.  Do those time pickers show up dynamically when you check the box or are they visible at all times?

**Comment by gcobb321** [comment]
The checkbox if from HA. The old style used a boolean with a checkbox. (config_validation - cv.boolean) where the new style uses one from the HA Selector module (selectorBoolean)

My time entry fields now are gone.

![image](https://user-images.githubusercontent.com/35449479/217382726-9932a7bb-a339-49f6-8201-1141cbc18310.png)

**Comment by pauly7300** [comment]
So it looks like those sections are collapsing for you.  That's not happening on mine.  Here's a video.

https://user-images.githubusercontent.com/11494052/217383479-eb81d691-845f-46c4-83b6-2b9a3ab4fc7b.mp4

**Comment by gcobb321** [comment]
The check boxes on the left are the same as the boolean selector on the left. The 2023.2.2 HA update stopped displaying the time entry fields (Passthru time, stationary still time, inzone time, etc). The hh:mm:ss parameters are not showing on any screen.

**Comment by pauly7300** [comment]
ahh.  At least we've found the discrepancy.  I guess there's a diff issue now.

**Comment by engeles20** [comment]
is there a fix for this yet?

**Comment by gcobb321** [comment]
See Release 12 notes [here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-12)

**Comment by engeles20** [comment]
@gcobb321 i would hate to open a new thread, but when i try to update to release 12 (from iCloud3 v3.0.0b11)  i get this error

Logger: homeassistant.setup
Source: setup.py:213
First occurred: 4:30:30 PM (1 occurrences)
Last logged: 4:30:30 PM

Setup failed for custom integration icloud3: Unable to import component: cannot import name 'RANGE_DEVICE_CONF' from 'custom_components.icloud3.const' (/config/custom_components/icloud3/const.py)

**Comment by gcobb321** [comment]
Unzip this to the /icloud3 directory and restart ha

[const.zip](https://github.com/gcobb321/icloud3_v3/files/10717496/const.zip)

**Comment by engeles20** [comment]
fixed thank you very much!

**Comment by gcobb321** [comment]
Thanks for the heads up. I forgot to include theat module in the release beta 12, which has now been updated.
