### ISSUE TITLE
Beta 11, Keeps Trying To Authenticate

### ISSUE THREAD

**Issue by townsmcp** [gcobb321/icloud3_v3#63]
I updated to beta 11 yesterday however today Icloud3 keeps trying to reauthenticate. First time it came through, I had the HA bell icon notification asking for the code which I entered and all seemed ok. However 10 minutes later I get the authentication and code pop up on iOS devices, get the code, go back into iCloud configuration, select to use the new code, add the code. 10 minutes later, the cycle starts again.

To be clear, I’m on HA 2023.2.2

![EF190954-0B6E-412A-994F-09F40C5AC334](https://user-images.githubusercontent.com/14061617/217352073-ae7382f8-6e00-402a-8da9-6dfa36bce5bd.jpeg)

**Comment by gcobb321** [comment]
Does it clear up if you restart HA or iCloud3?

**Comment by townsmcp** [comment]
@gcobb321 sadly no. I have tried restarting the iCloud3 service a few times and rebooting HA a few times

**Comment by gcobb321** [comment]
Select Event Log > Actions >Reset iCloud Interface which will delete the files (cookies & session tokens)  that control this and give you a new verification code via the popup. Enter that code and hopefully, it will be ok.

**Comment by townsmcp** [comment]
Just gave that a go. Log showed the new code was successful, devices updated, and then asked to authenticate on iOS pop up about 30 seconds later. Event log shows a green ‘iCloud authentication is needed’ strap line 😥

**Comment by gcobb321** [comment]
Try ignoring the pop ups. Just hit allow in the window. Clear the Event Log green message. Refresh the Event Log from the icon in the upper right. See if that works

**Comment by townsmcp** [comment]
@gcobb321 accepting the popup on iOS/OSX devices, OK'ing the new 6 digit code and hitting allow appears to work - data is still coming back from the devices (I just tried putting my phone on charge and it is reflected in the iCloud 3 battery device state) which is strange as the event log still shows authentication needed. Just damn annoying to keep getting the popup on Apple devices - time interval can be anything from every 5 minutes to every half an hour.
I did try installing beta 10a but even after reboot of HA Im still getting the same. 
Before installing beta 11, I had beta 9 installed - might try going back to that just to see if that makes a difference to the constant popups

**Comment by gcobb321** [comment]
The Event Log is probably just the message not getting cleared. I’ll look at that. What device are you using for HA. RPi, Mac, ?

**Comment by townsmcp** [comment]
Im running HA in a VM on Proxmox, (HAOS 9.5)

**Comment by gcobb321** [comment]
Maybe the code is never really getting out. You should be able to bring up the iCloud3 configurator and enter it on a phone or iPad

**Comment by townsmcp** [comment]
Think I have fixed the issue. I uninstalled the integration, removed the icloud3 directory from custom_components, removed the HACS icloud3 integration from HACS store, rebooted, created the icloud3 directory, populated with all beta 11 files, rebooted, added integration, rebooted and then went into the config. 2 hours now and no iOS pop up on watch, iPad, iPhone or osx apart from the initially pop up to setup authorisation
