### ISSUE TITLE
Geographic Region Entered Events Don't Trigger An Update

### ISSUE THREAD

**Issue by scotty1395** [gcobb321/icloud3_v3#68]
App Geographic Region Entered events don't seem to be triggering iCloud3 to do an update.
iCloud3 waits until the next scheduled update time.

I have the pass through zone setting turned off and delay time set to 0.

**Comment by gcobb321** [comment]
The only thing that triggers an update is the iOS app triggers. This includes Zone enter/exit, background refresh, significant location update and other. I don’t know what App Geographic Region Entered Event you are referring to. It’s it tied to a specific Integration, entity, d_t,etc. One thing you can do is to have an automation that triggers an iCloud3 service call to do a locate for the device. That Svc was added in b12.

**Comment by scotty1395** [comment]
Sorry, "Geographic Region Entered" is the state of sensor.xxxx_iphone_2_last_update_trigger from the Mobile App integration when a zone is entered.
In v2 this (or the underlying event) triggered an iCloud3 update. In v3 it seems to be getting missed.

**Comment by gcobb321** [comment]
Is v3 not getting the Enter trigger all the time or just one time? The Event Log shows the Update Trigger entity for a device at the end of the set up process, along with FamShr, FmF, iOS app, and other items. Are v2 and v3 monitoring the same entities?

if they are, I’m going to need some Log files to look at. The Export Event Log from both might show something.

**Comment by scotty1395** [comment]
Yes, they are monitoring the same entities.
From the logs it seems v3 is getting the enter trigger but isn't using the data to update the iCloud3 location.
I've emailed you a section of the log file to have a look at.

**Comment by gcobb321** [comment]
I commented on this in your other issue.
