### ISSUE TITLE
Installation Note #2 - About the Event Log card and the Lovelace Resource

### ISSUE THREAD

**Issue by Seger85** [gcobb321/icloud3_v3#69]
[Installation Note #2 - About the Event Log card and the Lovelace Resource](https://gcobb321.github.io/icloud3_v3/#/chapters/2.0-installing-and-configuring?id=installation-note-2-about-the-event-log-card-and-the-lovelace-resource)

[Update the Lovelace Resource](https://gcobb321.github.io/icloud3_v3/#/chapters/2.0-installing-and-configuring?id=update-the-lovelace-resource)

I have installed Beta 12, but unfortunately the event log card is not displayed. I deleted the cache, everything was automatically copied to the specified path, but unfortunately the card is not displayed, even if I adjust the resource and follow the instructions. Can anyone help me to find out what I am doing wrong?

**Comment by freshairr** [comment]
Are you using UI Mode or YAML? 
Are there any errors messages? 
Did you migrate from v2 or is v3 beta 12 your first time installing icloud3_v3?
What does your config/www directory look like? (There should be an icloud3 folder with the eventlog.js file inside)

**Comment by Seger85** [comment]
I am using the UI mode and have not found the map. The resource is entered and also the path and the iCloud3 folder with the associated file is there. Never had v2 installed, am a new user and went straight to version 3 with the beta as I am not in production mode yet. Will unzip Vision Beta 13 again tomorrow evening and drag it into the folders. Do you have any other ideas what the problem could be? I'm on the road until tomorrow evening, just wanted to let you know.

Many greetings
Seger

**Comment by gcobb321** [comment]
Did you put `map` in configuration.yaml. See HA Map docs [here](https://www.home-assistant.io/integrations/map/)

**Comment by Seger85** [comment]
> Did you put `map` in configuration.yaml. See HA Map docs [here](https://www.home-assistant.io/integrations/map/)

I wanted to confirm after closing the problem that it was exactly the problem. I didn't find this note in your documentation, so I couldn't know. Have I perhaps overlooked it, or should it be included? I also had to change the resource, but I don't know if I set it wrong myself before, because of the error analysis. In any case, THANK YOU, will be happy to test the following versions further. 

OT: have always seen with my Apple Watch in the last beta that it is in a completely different location/contigent (on the map in HA) than all other devices (current location Germany and the Apple Watch is in Africa :-). I will monitor the issue separately and open a separate topic if necessary.

THANK YOU!

**Comment by gcobb321** [comment]
The docs were written before beta 1 was released. A lot has changed and the docs need u updating and reorganizing. I’ve captured all of the screens and hope to start that next week. 

The map card probably uses the lat/long values in the device_tracker entity. Open ha Developer tools, select it, scroll back to the top and verify the location values and the data source. If it’s in Africa, it might be 0,0.
