### ISSUE TITLE
Family share with a iPhone without HA app

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#7]
Hi,

Beta 2 is running much better. My own iPhone is working. See all the sensors etc.
But my partners iPhone isn't coming up at all. He doesn't have HA app installed.
So the information but be come from my iCloud account with family share.
(this worked great with iCloud3_v2)

```
------------------------------------------------------------------------------------------------------------------------
09:52:25	   Initializing iCloud3 v3.0.0b2 > Monday, Dec 19
09:52:25	   Set Up Waze > Region-EU, MinDist-10km, MaxDist-500km, Realtime-True, HistoryDatabaseUsed-True
09:52:25	   Waze History Database > Compressed, Record Count-0
09:52:25	   Configure iCloud3 Operations >, •Load configuration parameters, •Set Display Text As Fields (0 used), •Se
					t Default Tracking Method (FamShr), •Initialize Debug Control (info), •Set Unit of Measure Formats (
09:52:29	   AUTHENTICATE PyiCloud, -pe..........es@ic........om, init
09:52:29	   ADDED FamShr PyiCloudDevice-, Apple Watch van Peter/QkKnPAD4aj
09:52:29	   NO LOCATION FamShr PyiCloudData-Peter’s MacBook Pro
09:52:29	   ADDED FamShr PyiCloudDevice-, iMac van Peter/2DdaH7FTtm
09:52:29	   ADDED FamShr PyiCloudDevice-, Peter iPhone/5yAbrrC4uE
09:52:29	   NO LOCATION FamShr PyiCloudData-cenkay’s iPhone
09:52:29	   NO LOCATION FamShr PyiCloudData-cenkay’s iPhone
09:52:29	   NO LOCATION FamShr PyiCloudData-iPhone
09:52:29	   ADDED FamShr PyiCloudDevice-, Cenkay 13/nA/v6NXyDu
09:52:29	   ADDED FamShr PyiCloudDevice-, AirPods van Cenkay/nKz8eqmhd1
09:52:29	   CREATED PyiCloud FamShr, pe..........es@ic........om, init
09:52:29	   ADDED FmF PyiCloudDevice, (Njc5MTcz)
09:52:29	   ADDED FmF PyiCloudDevice, (MTc0MjY2)
09:52:29	   CREATED PyiCloud FmF, pe..........es@ic........om, init
09:52:29	   iCloud Account Authenticated (#1) > LastAuth-Never (Initializing), Method-Account/PasswordSignin, Took-4 
					sec
09:52:29	   iCloud Location Services interface > Verified
```

**Comment by gcobb321** [comment]
There are 2 cenkay’s iPhone devices with NO LOCATION. After that, in the Event Log is the List of all famshr and fmf devices with the device model and an Id number (5yAbrrC4uE). Are these your partners phone? One might be an old phone that is n no longer but was selected as the Family Share device in the Configurator. The old one, if this is the case, should be deleted from the iCloud act. That it’s why I added model numbers. 

 Also try Event Log > Actions > Relocate All Devices or Event Log > Actions > Restart iCloud3.

 I have seen times that not all famshr devices are reported during startup (usually my wife’s watch).  V3 check this and does a refresh if the counts of the devices do not match but that just looks at the devices returned vs the county of all devices.

**Comment by poudenes** [comment]
He has some old phones indeed. Both are broken and not working anymore

```
  - device_name: "cenkay_13"
    picture: "local/images/person/kay-home.png"
    name: "Kay"
    iosapp_installed: false
```
This was the device name I used with V2 of iCloud3

**Comment by poudenes** [comment]
In Update Tracked iCloud3 Device I just see 1 iPhone :  Cenkay 13/nA/v6NXyDu that has been used for famshr

**Comment by gcobb321** [comment]
You said your phone is doing ok and your partner’s is not being located? Is that still the case or is it working now? If not, export the Event Log and I’ll look at it. Send to geekstergary@gmail.com

**Comment by poudenes** [comment]
> You said your phone is doing ok and your partner’s is not being located? Is that still the case or is it working now? If not, export the Event Log and I’ll look at it. Send to geekstergary@gmail.com 

I will send you the log tomorrow. In Amsterdam now we gonna sleep :)

**Comment by poudenes** [comment]
Log send

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary
