### ISSUE TITLE
MFA Timeout

### ISSUE THREAD

**Issue by kingy444** [gcobb321/icloud3_v3#70]
how often should the MFA token be re-requested?

I have had it happen once, but on v2 there used to be a notification in HA to click and enter it (this wasn’t present when I got the 2FA code)

I never entered it anywhere and everything is still working, but should the notification still be there ?

**Comment by gcobb321** [comment]
It’s hard to say how often it needs to be done. Apple never says but probably every 30-60 days. You will normally get the bell notification, then open the notification msg. That will take you to the devices and settings which will show a red reauthentication screen, enter the code and submit. 

If it does not show up but you get a notification from Apple, you can go to the icloud3 configuration > iCloud username/password screen > Enter verification code. Enter the code and submit. 

At one time, it was in the docs but it’s not there now. My next project is to go back over the docs and update the screens

**Comment by gcobb321** [comment]
General Housekeeping -- Closed with b13, Reopen is this is still an issue
