### ISSUE TITLE
Your Apple ID was used to sign in to iCloud via a web browser

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3_v3#72]
In the v2 version of iCloud, I used to get an email from Apple saying that my Apple ID has been used to sign-in.

In v3, I get this every day (it actually looks like about every 23 hours).

I don't know what the difference is in the authentication mechanisms, but it would be great if there was a way to reduce this somehow, especially as this could mask someone actually trying to hack in to our icloud accounts.

Thanks!

**Comment by gcobb321** [comment]
There are a lot of changes in the interface module but the authentication code is the same in v2 and v3. Unfortunately, Apple is the one controlling this. The account token is reverified about every 30 minutes or so. If you are in a zone and the interval is longer than 30 minutes, then that will be done when you request the next icloud location update. Again controlled by Apple. Over the years I, and others, have tried to determine if the emails can be stopped or reduces without success.

**Comment by ChrisBuHa** [comment]
Did I get it right that I will get these e-mail notifications as long as I use icloud3? 
I am very sorry but this would be a reason not to use it. I already got in when I used the official icloud integration and that was the only reason why I wanted to try icloud3.
For me it is a safety concern because the daily recurring mails would prevent me from taking them serious and I wouldn‘t check my account. As @derekoharrow already has written, that could mask a real account attack. 
Futhermore my wife would be very annoyed of the e-mails.

**Comment by JtwoA** [comment]
Before hitting the panic button, I’m not seeing this behavior.  I just re-authed this weekend (surprisingly without issue via mobile, I usually do it from desktop) and do not see the iCloud emails.

**Comment by gcobb321** [comment]
You get these emails whenever there is a login to your iCloud account. Icloud3 has no control over the timing or frequency of these emails. Remember, you have 2fa on your account and you have verified the usage of it to locate the devices. Within iCloud3, a great deal of care has been taken to prevent the display of your password in any reports or files. It is encrypted in the configuration file and not displayed anywhere except when you choose to display on the configuration screen. 

I have a filter set up in my gmail account that sends these emails to a special folder so they do not clog up my inbox. Over the past 4 years, I have seen no issues with iCloud3 logging into my account for location info, which is the only information it can get. 

But I understand your security concern and hope you find another way to track your devices. One thing you may want to consider is that you can use iCloud3 in iOS app only mode. You do not need to access your iCloud account.  On the iCloud Credentials configuration screen where you normally enter your username/password, do not put that in and set the data source to iOS app only. 

Gary

**Comment by JtwoA** [comment]
Curiosity was killing me, so I went and investigated. I, too, apparently set up a rule a long, long time ago to route those emails to a folder.On Feb 23, 2023, at 19:28, Gary Cobb ***@***.***> wrote:﻿
You get these emails whenever there is a login to your iCloud account. Icloud3 has no control over the timing or frequency of these emails. Remember, you have 2fa on your account and you have verified the usage of it to locate the devices. Within iCloud3, a great deal of care has been taken to prevent the display of your password in any reports or files. It is encrypted in the configuration file and not displayed anywhere except when you choose to display on the configuration screen.
I have a filter set up in my gmail account that sends these emails to a special folder so they do not clog up my inbox. Over the past 4 years, I have seen no issues with iCloud3 logging into my account for location info, which is the only information it can get.
But I understand your security concern and hope you find another way to track your devices. One thing you may want to consider is that you can use iCloud3 in iOS app only mode. You do not need to access your iCloud account.  On the iCloud Credentials configuration screen where you normally enter your username/password, do not put that in and set the data source to iOS app only.
Gary

**Comment by diothar** [comment]
I will also say that I got many more prompts for my authentication code and e-mail when I was using the regular icloud integration with Home Assistant.  iCloud3, while I still get them (v2 and v3), I get far fewer.

**Comment by gcobb321** [comment]
General Housekeeping -- Closed with b13, Reopen is this is still an issue
