### ISSUE TITLE
device_tracker attributes incorrectly set as strings instead of float

### ISSUE THREAD

**Issue by retroneo** [gcobb321/icloud3_v3#77]
This is giving all sorts of broken functionality with other device_trackers as well as logs like "TypeErr: must be a real number, not str". There are multiple reported issues that this will fix. The device_tracker isn't working correctly with other plugins such as proximity (this will do away with the need to write your own distance_to).

Looking at the state attributes in the Developer Tools > States > Set State > State Attributes YAML  shows the **latitude, longitude and gps_accuracy** are set as strings. This is not the case for other correctly functioning device_trackers.

**Comment by gcobb321** [comment]
1. HA truncates the latitudes, longitude to 2–decimal  places when displaying the device_tracker attributes ona Lovelace card so you would never see the location with any precision. Instead of seeing 27.73664829; -109.8136478, you see 27.74, -109.81. I have changed this in Beta 14 to set  them as numeric fields and use a new gps attribute that shows them with their full values. The gps accuracy is also set as a numeric field instead of a string. 
2. It’s difficult to understand blanket statements like “it doesn’t work well with other device trackers”. A detailed description of what you are trying to do and how you are doing it with examples helps fix a problem. Logs, sample automations, etc helps identify a problem.  What is it doing with proximity that creates problems for you. 
3. There are several sensors that show the distance_to home or another tracked zone. Are you trferring ot any specific one that is creating a problem.

**Comment by retroneo** [comment]
Thank you. Very excited about beta 14! 

_By “it doesn’t work well with other device trackers” i mean:_
I have 12 zones set up in HA. HA calculates the distance between any device_tracker using the built-in proximity integration. This works with the mobile app and automower device_trackers. Their state also automatically maps on to all of the zones without creating additional sensors. It's very precise and instant - the 12 zones are on the lawn and the mower will stop when entering a zone where the sprinkler is running until it has finished. The built-in history_stats make it easy to calculate how long a device_tracker has spent in certain zones in a day or week.

Attempting to use the device_tracker with the proximity generates an error in the log "TypeErr: must be a real number, not str"and nothing happens.

By switching to the icloud3v3 device_tracker over the mobile app device_tracker, the existing setup will work more reliably. The HA phone app - which intermittently doesn't transmit location at all - doesn't even need to be installed. Plus the phone doesn't even need to be on.

_"There are several sensors that show the distance_to home or another tracked zone. Are you trferring ot any specific one that is creating a problem."_
Those sensors will not be required with this fix. The built in distance calculation also shows the distance to other device_trackers, which the sensors you refer to only calculates the distance to other icloud sensors. This does away for the need for me to make even more sensors for each of the zones using this device_tracker.

**Comment by gcobb321** [comment]
Thanks. An interesting use of iCloud3. I noticed one thing that needs a quick fix and I’ll send b14 to you before it’s released to see if everything works ok.

**Comment by gcobb321** [comment]
Here is the beta 14. It has not been released yet so be sure to let me know if you run into anything weird.. Unzip into the icloud3 directory. See #4.

Here are all the changes in this beta:
1.  iCloud Account Authentication - When the iCloud Account is verified using a password, a session access 
    token is created and stored as a cookie. The password login also generates an email saying someone has 
    logged into your iCloud account. This beta changes the method of authenticating the account to using 
    the token first and then using the password if it has expired. This should eliminate or greatly reduce 
    the login emails generated by Apple.
2.  Configuration Wizard > iCloud Account Credentials screen - Updated it to improve readability and make 
    it easier to set up the account information. Several rare problems were also fixed where (1) logging 
    into an iCloud Account with an incorrect password would still allow access when there was a valid token 
    and (2) logging into an iCloud Account with a changed password would not work if the token has expired. 
    Now, logging in with a new password causes a new 2fa request to be made.
3.  Zone enter/leave event for an iCloud3 device_tracker entity - This can now be used as an automation 
    trigger.
4.  Latitude/longitude values - They are now stored as numeric fields in the device_tracker attributes instead 
    of a string field. They are now displayed with 2-decimal places on a Lovelace device_tracker/attributes 
    window (an HA limitation). A new gps attribute has been added to display the latitude/longitude with it's 
    full precision.
5.  Passive Zones - Fixed a problem where passive zones could be selected. Also found out that the iOS App 
    will generate enter/exit triggers for passive zones. These will now be ignored by iCloud3.
6.  Configuration Wizard > Sensors screen - Changed it  for readability and to list the important sensors 
    first.
7.  Event Log - Made some minor formatting changes. Also added a new icon to the top-right of the Event Log 
    so you can become an iCloud3 Stargazer. Click it to go to the iCloud3_v2 GitHub repository. Then click 
    the star in the top-right corner.

[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10886370/icloud3_v3-beta-14.zip)

**Comment by retroneo** [comment]
Hi,

I get the following error when restarting HA in the log. But so far, it seems to be working as expected.

The state of the device_tracker now updates automatically with the correct zone too!
Proximity integration is correctly reporting distances,


The error at startup for HA is:

Last logged: 11:55:18 AM

  *   Error adding entities for domain device_tracker with platform icloud3
  *   Error while setting up icloud3 platform for device_tracker

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 814, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 253, in state
    zone_state = zone.async_active_zone(
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 130, in async_active_zone
    within_zone = zone_dist - radius < zone.attributes[ATTR_RADIUS]
TypeError: unsupported operand type(s) for -: 'float' and 'str'


Kind regards,

David
On 4 Mar 2023 at 8:57 AM +1100, Gary Cobb ***@***.***>, wrote:

Here is the beta 14. It has not been released yet so be sure to let me know if you run into anything weird.. Unzip into the icloud3 directory. See #4<https://github.com/gcobb321/icloud3_v3/issues/4>.

Here are all the changes in this beta:

  1.  iCloud Account Authentication - When the iCloud Account is verified using a password, a session access
token is created and stored as a cookie. The password login also generates an email saying someone has
logged into your iCloud account. This beta changes the method of authenticating the account to using
the token first and then using the password if it has expired. This should eliminate or greatly reduce
the login emails generated by Apple.
  2.  Configuration Wizard > iCloud Account Credentials screen - Updated it to improve readability and make
it easier to set up the account information. Several rare problems were also fixed where (1) logging
into an iCloud Account with an incorrect password would still allow access when there was a valid token
and (2) logging into an iCloud Account with a changed password would not work if the token has expired.
Now, logging in with a new password causes a new 2fa request to be made.
  3.  Zone enter/leave event for an iCloud3 device_tracker entity - This can now be used as an automation
trigger.
  4.  Latitude/longitude values - They are now stored as numeric fields in the device_tracker attributes instead
of a string field. They are now displayed with 2-decimal places on a Lovelace device_tracker/attributes
window (an HA limitation). A new gps attribute has been added to display the latitude/longitude with it's
full precision.
  5.  Passive Zones - Fixed a problem where passive zones could be selected. Also found out that the iOS App
will generate enter/exit triggers for passive zones. These will now be ignored by iCloud3.
  6.  Configuration Wizard > Sensors screen - Changed it for readability and to list the important sensors
first.
  7.  Event Log - Made some minor formatting changes. Also added a new icon to the top-right of the Event Log
so you can become an iCloud3 Stargazer. Click it to go to the iCloud3_v2 GitHub repository. Then click
the star in the top-right corner.

**Comment by gcobb321** [comment]
I checked all the zone radius sensor values and did not see any non-numeric fields. See if the error is still generated after this b14 version.

This b14 version addresses sensor precision:
8.  Distance Sensors - (1) Changed the distance precision so the distance value is within 6-inches/
    10-centimeters of the measurement between the device and the zone center. (2) Changed the
    '_moved_distance' sensor to display in feet/meters when less than 1mi/1km. (3) Added moved from time
    and moved to time to the '_moved_distance' sensor.

[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10889344/icloud3_v3-beta-14.zip)

**Comment by gcobb321** [comment]
And here is the latest b14 (0305pm)
8. Distance Sensors:
(1) Changed the distance precision so the distance value is within 6-inches/1-millimeter of the
measurement between the device and the zone center - (4-decimal places for miles, 5 for meters)
(2) Changed the '_moved_distance' sensor to display in feet/meters when less than 1mi/1km
(3) Changed the '_moved_distance' to display the distance from one poll to the next when in a zone
(4) Added attribute to '_moved_distance' to show the from and to location time
(5) Added attribute to all 'zone_distance' sensors - 'meters_distance' shows the distance in meters
to the zone with 5-decimal place accuracy
(6) Added attribute to all 'zone_distance' sensors - 'miles_distance' shows the distance in miles
to the zone with 4-decimal place accuracy if the unit_of_measure is miles.

[icloud3_v3-beta-14-0305pm.zip](https://github.com/gcobb321/icloud3_v3/files/10893214/icloud3_v3-beta-14-0305pm.zip)

**Comment by gcobb321** [comment]
This is the beta14 I,ll upload tomorrow. I've added a '_meters_distance_to_zone_edge attribute to the zone_distance sensors you may be interested in. The meters_distance attribute is the distance to the center of the zone, the meters_distance_to_zone_edge is the distance to the outside edge.

8.  Distance Sensors:
    (1) Changed the distance precision so the distance value is within 6-inches/1-millimeter of the
        measurement between the device and the zone center - (4-decimal places for miles, 5 for meters)
    (2) Changed the '_moved_distance' sensor to display in feet/meters when less than 1mi/1km
    (3) Changed the '_moved_distance' to display the distance from one poll to the next when in a zone
    (4) Added attribute to '_moved_distance' sensors:
        -   '_moved_from' shows the from location time
        -   '_moved_to' shows current location time
    (5) Added attribute to all 'zone_distance' sensors:
        -   '_meters_distance' shows the distance in meters to the zone with 5-decimal place accuracy,
        -   '_meters_distance_to_zone_edge' shows the distance in meters to the edge of the zone
    (6) Added attribute to all 'zone_distance' sensors:
        -   '_miles_distance' shows the distance in miles to the zone with 4-decimal place accuracy if the
            unit_of_measure is miles.

[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10935718/icloud3_v3-beta-14.zip)
