### ISSUE TITLE
Driving Flag has stopped detecting under a half mile

### ISSUE THREAD

**Issue by JtwoA** [gcobb321/icloud3_v3#79]
I am using ZoneDistance to set two different Driving Flags.  The first is set to .1 MI, the second to 5 MI.

I visit a location nightly that is .48 MI away from Home and, until the latest 13 beta version (not 14) it worked flawlessly.  Now it will not recognize until I'm at least a mile away.

**Comment by JtwoA** [comment]
Beta 14 has not resolved this issue.

**Comment by gcobb321** [comment]
Are you talking about the b14 I posted about an hour ago or the one yesterday? I found the original b14 was rounding the zone distance values to a whole number instead of using the actual value. .48 was rounded to 0. I am now seeing Zone distances like .11 mi to a nearby zone

**Comment by gcobb321** [comment]
This is the one I worked on today And the distance to a close zone
![image](https://user-images.githubusercontent.com/35449479/222932298-f911f5e1-0f6d-41b5-9a4f-7a89030da7aa.png)


[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10889827/icloud3_v3-beta-14.zip)

**Comment by JtwoA** [comment]
I updated with the version that was available around noon ET.On Mar 4, 2023, at 17:49, Gary Cobb ***@***.***> wrote:﻿
Are you talking about the b14 I posted about an hour ago or the one yesterday? I found the original b14 was rounding the zone distance values to a whole number instead of using the actual value. .48 was rounded to 0. I am now seeing Zone distances like .11 mi to a nearby zone

**Comment by broyuken** [comment]
How do you set a driving flag?

**Comment by gcobb321** [comment]
Here is my Gary Arrives Home Automation:
```
alias: Gary - Arrives Home
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.gary_iphone_zone_name
    to: Home
  - platform: numeric_state
    entity_id: sensor.gary_iphone_home_distance
    below: 0.35
condition:
  - condition: numeric_state
    entity_id: sensor.gary_iphone_home_distance
    attribute: max_distance
    above: 2
action:
  - service: script.notify_gary_iphone
    data_template:
      title: Gary Arrives Home
      message: >-
        Zone: {{ trigger.from_state.state }} → {{ trigger.to_state.state }},
        Distance: {{ states('sensor.gary_iphone_home_distance') }}
  - service: script.gary_arrives_home
    data: {}
mode: single
```

I use the `condition` to know when I am driving. You can use the same thing to trigger a 'turn_on'  input_boolean sensor, then turn the sensor off when you enter the zone.

**Comment by broyuken** [comment]
Is it possible to tap into the focus mode, or driving auto reply that iPhones can do?

**Comment by gcobb321** [comment]
I don't think so but I'll do a rawdata without a filter on the icloud data.

Can you take a screenshot of the config wizard > format screen. I want to verify that what you are seeing is the same as the screenshots I have taken that show the Chrome browser inspect code before I post an HA FrontEnd Issue . They made major changes to the frontend so I think they broke it.

**Comment by broyuken** [comment]
Sure, here you go. This is from the HA app, but I see the same thing in chrome. 

![AE158BB2-DD7F-4CEC-B11D-85BA0B3E6B02](https://user-images.githubusercontent.com/1593391/223101518-4f99f344-c162-4000-b6cd-29994cad3409.png)

**Comment by broyuken** [comment]
you could also just make your home zone bigger

**Comment by t077584** [comment]
And how would I do this? Sry, don't want to hijack this thread to discus HA basics, but I couldn't find ways to make the home zone bigger. It seems to be fix, unlike other zones one can create in HA.

**Comment by broyuken** [comment]
looks like it has to be done via yaml, I thought it was easier. You could either do this, or customize.yaml

https://www.home-assistant.io/integrations/zone/
or
https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by gcobb321** [comment]
The trigger:
```
trigger:
  - platform: state
    entity_id:
      - sensor.gary_iphone_zone_name
    to: Home
  - platform: numeric_state
    entity_id: sensor.gary_iphone_home_distance
    below: 0.35
```
Background info:
This fires if the zone_name changes to 'home' OR the home_distance goes below .35mi. (not AND) I am at the far edge of a cell phone area and usually get about 1-bar so triggering events can sometimes lag. Actually it usually lags. (Note: I'm on AT&T right now and am trying T-Mobile. So far T-Mobile seems more responsive). I'm now using NabuCasa so the Zone Enter has to be recognized by the iOS App, sent to NabuCasa which then goes to DuckDNS to get my home IP address, and then sends the Enter trigger to my home router, that sends to my Rpi. (Another Note: I recently switched to NabuCasa after doing my own DuckDNS and think response time is a little slower then going from my iOS App to DuckDNS to my home IP address). (Note 3: I went with NabuCasa for voice support of some Sonoff/ESPHome switches buried in the walls that I used to use AWS for support but that was getting cumbersome working with their servers).

Anyway, there are a lot of moving parts. iC3 runs on a 5-second internal interval so it will pick up the iOS App Enter trigger within 5-seconds of the HA/RPi getting it (It picked up your enter trigger within 3-sec) . The 15-sec interval is so HA will send a location request to iCloud/FamShr/FmF to update the location. 

Your situation:
You got the Enter trigger at 12:00:12 which was picked up and processed at 12:00:15 and put in your Home zone.
Also at 11:58:00, it shows you were 1.7km from Home and then got there 2-min later. So you were going about 30 mph which makes sense.

Thoughts:
In the automation trigger, I put the .35mi distance so if I was close to home on the last 15-sec poll before getting home, my automation would execute and open the garage door just before I got there. In my open routine, I check to not open it again when the zone changes to home so it wouldn't then close it. This seems to work find for me about 80% of the time. The other 20%, I'm sitting in the driveway wondering why it didn't open. I get the phone, launch the iOS App, it sends a launch trigger and I go into the Home zone and the door opens. Looking at my logs, it usually (99%) was the iOS App had gone to sleep or was not connecting or I was getting a lot of old location errors & retries, 

Hope that helps explain what is going on.

**Comment by gcobb321** [comment]
And another thought:
There are several ways to issue the trigger in HA and I want to experiment to wee if one is faster but haven't had the time.
1. Use the zone_name entity going to 'home'
2. Using the home_distance entity going less than .05
3. Using the new meters_distance attribute of the zone_distance or home_distance going less than 200m.
4. Using a zone trigger tied to the device_tracker entity doing an 'enter'
5. Setting a BigHome zone also centered at the same location as the Home zone (Home-100m radius, BigHome=400m radius) and triggering on entering the BigHome. That would work on b14 when I changed the method of entering a zone within a zone.
And there are probably a couple of other triggers that might also fire.

**Comment by gcobb321** [comment]
@JtwoA When You are in a zone, iCloud3 sets the distance to the zone to 0. A new ` meters _distance` (and miles) attribute within the zone_distance and home_distance sensors will always show your distance to the zone center location, even when in the zone.

**Comment by gcobb321** [comment]
Here is the latest b14 that I am going to upload tomorrow. Maybe there is something in the version you are running that isn't playing nice with ha.

My config:
Home Assistant 2023.3.1
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230302.0 - latest

Gary 
[icloud3_v3-beta-14.zip](https://github.com/gcobb321/icloud3_v3/files/10923983/icloud3_v3-beta-14.zip)

**Comment by JtwoA** [comment]
Home Assistant 2023.3.1
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230302.0 - latest

**Comment by JtwoA** [comment]
This newest build did not resolve the issue @gcobb321 

I just received a notification to bump to 2023.03.2 so gonna do that now.

**Comment by JtwoA** [comment]
That didn't resolve the issue, unfortunately.

**Comment by gcobb321** [comment]
Power cycle your HA server and see what happens.

**Comment by gcobb321** [comment]
I just updated and all ok here

**Comment by JtwoA** [comment]
Rebooted the RPi and no difference.

**Comment by gcobb321** [comment]
Are you running in a plain or in a virtual environment or something like that. When I had the problem, it was running a docker dev setup on my windows system. Ok on my production rpi

**Comment by JtwoA** [comment]
Straight up on a RPi.Wondering if I should do a clean sweep of the icloud3 directory and place just the latest beta 14 files into a new one?On Mar 8, 2023, at 16:37, Gary Cobb ***@***.***> wrote:﻿
Are you running in a plain or in a virtual environment or something like that. When I had the problem, it was running a docker dev setup on my windows system. Ok on my production rpi

**Comment by JtwoA** [comment]
Ok, oddly, that did not resolve the issue, either.  Renamed the old folder and dropped 14 beta in, cleared caches, and exactly the same outcome.

**Comment by broyuken** [comment]
Try moving the old folder out of the custom components folder and do a fresh install, renaming in the same folder might not remove everything

**Comment by gcobb321** [comment]
I just went to my docker/dev/win10/vscode dev environment that gave me the same problem last week. I was getting ready to put b14 on top of what was there and saw I had the iCloud3 directory set to icloud3_v3. I changed that to icloud3 and restarted HA. I then dropped b14 on top of it! Restarted HA and everything was showing up when last week it wasn’t. It might have been good with the code before b14 but I don’t remember. 

Uninstall the iCloud3 integration (all config files and iCloud cookie are not deleted) restart HA without ic3. Restart it again. Add iCloud3 integration. Restart HA and check it see if what it looks like. 

I’m wondering if changing the directory name and doing several restarts cleaned out the HA cache. You might even do a power cycle between restarts

**Comment by JtwoA** [comment]
![image](https://user-images.githubusercontent.com/12992040/223877458-ca5f72fc-c56d-433b-99eb-a2284c0f314e.png)

Completely removed `icloud3-14-missing-titles` (the rename) and restarted.  Cleared cache again, restarted again.  Then restarted again just because.

Seems to have resolved the issue as I can now see full menus again.

**Comment by gcobb321** [comment]
Super

**Comment by gcobb321** [comment]
When you leave a zone, iCloud3 was setting the next interval time to 3-minutes. That time is now a parameter on the Tracking and Other Parameters screen. It defaults to 3-minutes. Try reducing that time.

**Comment by JtwoA** [comment]
I’ve set it to 2 minutes.On Mar 9, 2023, at 08:54, Gary Cobb ***@***.***> wrote:﻿
When you leave a zone, iCloud3 was setting the next interval time to 3-minutes. That time is now a parameter on the Tracking and Other Parameters screen. It defaults to 3-minutes. Try reducing that time.

**Comment by gcobb321** [comment]
I just set up an automation to fire (send me a message) when the zone_distance > .1mi. There must be something in your automation trigger that is not working.
```
alias: Gary Above .1mi
description: Gary Above .1mi
trigger:
  - platform: numeric_state
    entity_id: sensor.gary_iphone_zone_distance
    above: 0.1
condition: []
action:
  - service: script.notify_gary_iphone
    data:
      title: Gary Out of Zone Notice
      message: Above .1mi
mode: single
```
I walked my dog this morning:
![image](https://user-images.githubusercontent.com/35449479/224062841-c20843f3-136d-41af-b70d-b8da6a6ecd2d.png)
![image](https://user-images.githubusercontent.com/35449479/224063027-83397d48-7a8e-46e6-829b-bc4d5d0aaf89.png)

Then walked a little further:
![image](https://user-images.githubusercontent.com/35449479/224063233-b5a8b0d4-0dc7-454d-b72d-fc3156e6ff34.png)

And a little more:
![image](https://user-images.githubusercontent.com/35449479/224063532-6fa43779-0566-4815-a281-7393352817ba.png)

And I got a notification from HA:
![image](https://user-images.githubusercontent.com/35449479/224063791-ff5ee4fa-f5be-46ff-b43b-0541148a7c50.png)

I then started walking back home and got an attribute screenshot:
![image](https://user-images.githubusercontent.com/35449479/224064256-285c750b-2075-4dd8-bf86-5f6d4ba12072.png)

The zone_distance state and miles_distance attribute are all correct and I was still in the Home zone. iOS App had not fired the exit trigger.

**Comment by JtwoA** [comment]
I’ve change a couple triggers and will test here shortly.On Mar 9, 2023, at 10:03, Gary Cobb ***@***.***> wrote:﻿
I just set up an automation to fire (send me a message) when the zone_distance > .1mi. There must be something in your automation trigger that is not working.
alias: Gary Above .1mi
description: Gary Above .1mi
trigger:
  - platform: numeric_state
    entity_id: sensor.gary_iphone_zone_distance
    above: 0.1
condition: []
action:
  - service: script.notify_gary_iphone
    data:
      title: Gary Out of Zone Notice
      message: Above .1mi
mode: single

I walked my dog this morning:


Then walked a little further:

And a little more:

And I got a notification from HA:

I then started walking back home and got an attribute screenshot:

The zone_distance state and miles_distance attribute are all correct and I was still in the Home zone. iOS App had not fired the exit trigger.

**Comment by JtwoA** [comment]
I switched up how I pull the data from zone_distance AND (fully one to admit mistakes) also discovered that, somehow - and I've no idea how because this was working flawlessly and I tend not to touch working things, only broken ones - the `>` had become a `=` and that's never gonna work.

![image](https://user-images.githubusercontent.com/12992040/224139333-c202f603-5fba-4e20-b685-d3943ad9b830.png)

**Comment by gcobb321** [comment]
Two mysteries solved. (the other being the missing text on the Configuration Wizard screens.. Thanks for testing the code, I'm uploading tomorrow morning (and I've added another distance attribute - meters_distance_(zone_edge) to make it easier to use that to trigger when you are within Xm of going out of the zone. 

BTW-If this trigger only applies to the Home zone and not others, you might want to use the _home_distance sensor so it does not trigger when you leave a non-home zone.

**Comment by JtwoA** [comment]
It absolutely does pertain only to Home and distance from home.

--
John Alan

01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110110 01100001 01101100 01110101 01100001 01100010 01101100 01100101 00100000 01100110 01100101 01100001 01110100 01110101 01110010 01100101 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01101100 01101100 01101001 01100111 01100101 01101110 01110100 00100000 01101100 01101001 01100110 01100101 00101110

**Comment by gcobb321** [comment]
I thought it might. Using the home_distance means you do not have to also test the zone_name sensor

**Comment by JtwoA** [comment]
Bizactly - one less point of failure.  Perfect.

--
John Alan

01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110110 01100001 01101100 01110101 01100001 01100010 01101100 01100101 00100000 01100110 01100101 01100001 01110100 01110101 01110010 01100101 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01101100 01101100 01101001 01100111 01100101 01101110 01110100 00100000 01101100 01101001 01100110 01100101 00101110
