### ISSUE TITLE
NextUpdate trigger "hangs" at -85secs

### ISSUE THREAD

**Issue by t077584** [gcobb321/icloud3_v3#81]
I noticed some strange behaviour of the NextUpdate trigger, which seems to "hang" at -85secs, irrespectively of being stationary in a zone or on the move.

Per screenshot below, Pina left the office at 05.44.35pm, causing the zone to change from "Office Pina" to "Away" until being home at 05.:53:45pm. In between, she was 250km away(?) and the Next update trigger started a count-down when she left the office starting at +29secs every 5secs until -85secs and stopped there. While driving, it all of a sudden jumped to 05:51:10pm to be the next update and then looped again from +29secs to -85secs before arriving home.

![2023-03-08_14-26-23](https://user-images.githubusercontent.com/121488015/223729796-3e46b58f-82ec-41c0-8ffe-efe730706252.png)

Logfile:

![2023-03-08_14-32-05](https://user-images.githubusercontent.com/121488015/223729860-5d3dd4d7-72dc-471b-b50c-c9ecbc142f2c.png)

Any idea what I configured wrong, or is it a bug in b13? Thx for your help. Cheers, Mike

**Comment by gcobb321** [comment]
Lets see if this happens again in b14. At some time, I've seen that from time-to-time myself and it always/seems to correct itself.
