### ISSUE TITLE
iCloud3, Beta 14 (3/9/2023) has been uploaded

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#83]
@avd706 @B-Hartley @broyuken @bgnzo818 @beyondwatts @bakerkj 
@confusedsecuritydudes @chupacabra71 @chr04213
@daneboom @denac @derekoharrow @diothar
@Exit2Studios @freshairr @gekberlin @garyak
@hvddrift @hellotomtom @ihf1 @JtwoA @J-Fartz 
@kalkocz @kamkilt @kingy444 @lukkigi 
@marceloaf @MarkGardiner @MartinG @mobiledude @myMartek
@pauly7300 @poudenes @polskikrol
@rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3
@townsmcp @tm24fan8 @t077584 @u20p17

### Important Links:

**Download** - Go to the iCloud3 [Releases page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip. Download the zip file and unzip it into the /config/icloud3 directory. Then restart HA.
**iCloud3 v3 Documentation** - It is still in process, does not include the latest updates to iCloud3 and can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)
**Change Logs** - They can be found [here](https://github.com/gcobb321/icloud3_v3/blob/v3.0.0-beta-14/custom_components/icloud3/ChangeLog.txt)

-----
### Change Log
1.  **iCloud Account Authentication**:
    - When the iCloud Account is verified using a password, a session access token is created and stored
    as a cookie. The password login also generates an email saying someone has logged into your iCloud
    account. This beta changes the method of authenticating the account to using the token first and
    then using the password if it has expired. This should eliminate or greatly reduce the login emails
    generated by Apple.
    - Did a lot of code cleanup in the account authentication routines to insure the 2fa-code is requested
    when needed, to be able to reauthenticate and log into the current account with a new password and to
    be able to log into a different account in the Configuration Wizard.
2.  **Configuration Wizard > iCloud Account Credentials screen** - Updated it to improve readability and make
    it easier to set up the account information. Several rare problems were also fixed where (1) logging
    into an iCloud Account with an incorrect password would still allow access when there was a valid token
    and (2) logging into an iCloud Account with a changed password would not work if the token has expired.
    Now, logging in with a new password causes a new 2fa request to be made.
3. **Zone enter/leave event for an iCloud3 device_tracker entity** - This can now be used as an automation
    trigger.
4.  **Latitude/longitude values** - They are now stored as numeric fields in the device_tracker attributes instead
    of a string field. They are now displayed with 2-decimal places on a Lovelace device_tracker/attributes
    window (an HA limitation). A new gps attribute has been added to display the latitude/longitude with it's
    full precision.
5.  **Passive Zones** - Fixed a problem where passive zones could be selected. Also found out that the iOS App
    will generate enter/exit triggers for passive zones. These will now be ignored by iCloud3.
6. **Configuration Wizard > Sensors screen** - Changed it  for readability and to list the important sensors
    first.
7.  **Event Log** - Made some minor formatting changes. Also added a new icon to the top-right of the Event Log
    so you can become an iCloud3 Stargazer. Click it to go to the iCloud3_v2 GitHub repository. Then click
    the star in the top-right corner.
8.  **Distance Sensors**:
    (1) Changed the distance precision so the distance value is within 6-inches/1-millimeter of the
        measurement between the device and the zone center - (4-decimal places for miles, 5 for meters)
    (2) Changed the `moved_distance` sensor to display in feet/meters when less than 1mi/1km
    (3) Changed the `_moved_distance` to display the distance from one poll to the next when in a zone
    (4) Added attribute to `_moved_distance` sensors:
         `_moved_from` shows the from location time
         `_moved_to` shows current location time
    (5) Added attribute to all `zone_distance` sensors:
         `_meters_distance` shows the distance in meters to the zone with 5-decimal place accuracy,
         `_meters_distance_to_zone_edge` shows the distance in meters to the edge of the zone
    (6) Added attribute to all `zone_distance` sensors:
         `_miles_distance` shows the distance in miles to the zone with 4-decimal place accuracy if the
            unit_of_measure is miles.

**Comment by derekoharrow** [comment]
Thanks - great update!!
