### ISSUE TITLE
Beta14a - Some fmf devices are not being tracked - iCloud3 Error from iCloud Loc Svcs > Error Authenticating account or no data was returned from iCloud Location Services

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#87]
Started receiving this error after installing 14a. I have already reset authentication and checked devices configuration which actually were working before 14a. **In icloud3 v2.4.7 these devices are being tracked without problem.**

![image](https://user-images.githubusercontent.com/11551691/224424815-40a21190-ff04-4f40-a685-b2ce2bbd1e07.png)

This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/helpers/messaging.py:152
Integration: iCloud3 v3 (documentation, issues)
First occurred: 16:32:13 (2 occurrences)
Last logged: 16:33:10

* iCloud3 Error from iCloud Loc Svcs > Error Authenticating account or no data was returned from iCloud Location Services. iCloud access may be down or the Username/Password may be invalid.

This error originated from a custom integration.

Logger: icloud3
Source: custom_components/icloud3/support/start_ic3.py:1307
Integration: iCloud3 v3 (documentation, issues)
First occurred: 16:32:13 (2 occurrences)
Last logged: 16:33:10

xxxxxxx
Traceback (most recent call last):
  File "/config/custom_components/icloud3/support/start_ic3.py", line 1307, in setup_tracked_devices_for_fmf
    _RawData = PyiCloud.RawData_by_device_id_fmf[device_id]
KeyError: xxxxxx

**Comment by gcobb321** [comment]
Set log level to rawdata. Restart HA. If you get error, send me the iCloud3-debug.log file to geekstergary@gmail.com. Don’t comment anything out so I can see what data you are getting. No usernames or passwords are in the file. I’ll turn on fmf here and see if I get any errors on my end.

**Comment by marceloaf** [comment]
Will do that. Just tried reverting back to 14 and no errors. Devices are being tracked... Will do as you request and send you the logs.

**Comment by marceloaf** [comment]
Reverted back to 14a and guess what? No errors... :-( I'll keep monitoring and will send you the logs if it happens again! Tks

**Comment by gcobb321** [comment]
Not sure what you meant by “reverted back to b14a” since that it’s the latest.

**Comment by marceloaf** [comment]
On the comment above that I said I had reverted to 14 and no errors occurred. So I needed to reinstall 14a to try to capture the logs you requested. Hope it is clearer now.
