### ISSUE TITLE
State attributes exceed maximum size 

### ISSUE THREAD

**Issue by kingy444** [gcobb321/icloud3_v3#89]
This warning makes complete sense considering the size of the log. I couldnt see anything about it in the doco, but also curious if there is something in the code you can do to exclude this sensor from the recorder.

Otherwise we perhaps a note to exclude the sensor manually noting the context is already in a txt file ?

``
2023-03-13 08:33:40.883 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.icloud3_event_log exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
``

**Comment by gcobb321** [comment]
iCloud3 adds this sensor, all date related sensors, the info sensor and some others when it starts  from the history recorder. I’ll add a check to not let the Event Log Sensor from being longer than this value.

**Comment by gcobb321** [comment]
Checked in b15. The sensor.icloud3-event-log-card entity is automatically excluded from the recorder. loet me know if you get this error again and i'll take another look at it. When i was checking the state entity length, the lengtn of my entity was already up to 30k.
