### ISSUE TITLE
Beta 2 - User input malformed: battery_status is not a valid option for dictionary value @ data['device']

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#9]
Got this error when trying to review SENSORS (Beta 2).

![image](https://user-images.githubusercontent.com/11551691/208422502-9cb912b5-75de-463f-a303-7985b5888e8c.png)

**Comment by gcobb321** [comment]
Fixed in beta 3. Ill close this issue when beta 3 is available.

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary
