### ISSUE TITLE
iCloud3 v3, Beta 15 (3/19/2023) has been uploaded

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#93]
@avd706 @B-Hartley @broyuken @bgnzo818 @beyondwatts @bakerkj
@confusedsecuritydudes @chupacabra71 @chr04213 @criticallimit
@daneboom @denac @derekoharrow @diothar
@Exit2Studios @freshairr @gekberlin @garyak @freekode
@hvddrift @hellotomtom @ihf1 @JtwoA @HA_n00b @J-Fartz @joselito1
@kalkocz @kamkilt @kingy444 @lukkigi
@marceloaf @MarkGardiner @marting @mobiledude @myMartek
@pauly7300 @poudenes @polskikrol
@rdstodda @Snuffy2 @spamsal @Seger85 @scotty1395 @sj3fk3
@townsmcp @tm24fan8 @t077584 @u20p17

Important Links:
Download - Go to the iCloud3 [Releases page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip. Download the zip file and unzip it into the /config/icloud3 directory. Then restart HA.
iCloud3 v3 Documentation - It is still in process, does not include the latest updates to iCloud3 and can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)
Change Logs - They can be found [here](https://github.com/gcobb321/icloud3_v3/blob/v3.0.0-beta-14/custom_components/icloud3/ChangeLog.txt)

Change Log
-----
1.  Adding/Deleting Devices - Fixd a problem initializing the _interval sensors when adding a new device on the
    Update_iCloud3 Devices Configuration Wizard screen. Also added some additional error checking when creating
    sensors for new devices.
2.  Configuration Wizard -
    1. Added Alert messages to some screens when there are Inactive devices that will not be located or tracked.
    2. Added a Untracked (Inactive) Devices screen that can be displayed when exiting the Wizard and an iCloud3
    restart is needed.
    3. Added a 'cancel' option to the Restart iCloud3 screen to return to the Main Menu.
3.  Debug Logging - Now, the  'Log Level' is automatically set to 'debug' if a beta version is being used or
    if a non-beta version (released version) was installed less than 5-days ago.
4.  Configuration File - The configuration file is now reloaded when iCloud3 is restarted from the Event Log.
5.  HACS - Prepared iCloud3_v3 for HACS. It has been submitted and awaiting approval from HA.
6.  Debug Code - Removed debug trace code from beta15p2.

**Comment by FredWst** [comment]
Hi,

__init__.py is missing in zip file.

Fred

**Comment by gcobb321** [comment]
Fixed in beta15p2.

**Comment by GerdRuetten** [comment]
II've been testing with Beta 15 since today.
Before that I used the v2 for a long time.

Thank you for all your work @gcobb321
