### ISSUE TITLE
Reconfigure not working (Beta 15 3/18/2023)

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3_v3#96]
Hi All,

I got message to do a reconfigure. But far before that I god from Apple a auth code (6 numbers) and didn't why.
So denied it and later on I saw the reconfigure attention in HA.

Now it's not possible to get a new auth code. I filled in 6 numbers and the tool say it will request a new code.
This new code is never coming.

Greets,

**Comment by gcobb321** [comment]
Event Log > Actions > Reset iCloud Interface (last one)

**Comment by poudenes** [comment]
How easy can it be
