### ISSUE TITLE
Apple ID verfication not working

### ISSUE THREAD

**Issue by JeroenTuinstra** [gcobb321/icloud3_v3#97]
I migrated from Icloud3 2.4.7 to Icloud3 beta 15. All seemed to be working at least as far as the migration. Once I restarted HA if says that the integration has to be reconfigured. It needs the Apple ID Verification code. When I click on Reconfigure it says I should have received a code on one of my devices - yet nothing happen. No code appears on my Ipad, Iphone or Apple Watch. It seems that the code is not requested from Apple.

What can I do to get it to request one or reset it? 
<img width="239" alt="Screenshot 2023-03-30 143424" src="https://user-images.githubusercontent.com/47460053/228837266-ac9a5081-64b8-4ba4-be4f-93079e2d715e.png">
<img width="320" alt="Screenshot 2023-03-30 143517" src="https://user-images.githubusercontent.com/47460053/228837395-30278be6-37a2-4315-9ea9-d8890ac2561a.png">

I cannot select anything else in the integration.

**Comment by JeroenTuinstra** [comment]
Managed to get the apple ID triggered. I had to delete the folder /config/.storage/icloud. After a restart of HA was the Apple ID triggered.

**Comment by gcobb321** [comment]
FYI - There ae 2 ways to get it to trigger:
1. Event Log > Actions > Reset iCloud Interface
2. Devices & Services > iCloud3 > Configure > iCloud Login Credentials > Reset and Reauthenticate

This does what you did, delete the .storage/icloud cookies and session files.
