### ISSUE TITLE
Lovelace Resources not migrated

### ISSUE THREAD

**Issue by JeroenTuinstra** [gcobb321/icloud3_v3#98]
Updating from 2.4.7 to beta 15 doesn't copy the lovelace resources in the folder /config/www/icloud3. After migration there is no folder created nor any cards copied. What remains is /config/www/custom_cards
<img width="903" alt="Screenshot 2023-03-30 151128" src="https://user-images.githubusercontent.com/47460053/228846499-c439fefc-5230-46e5-a8a8-9b4da4b3495c.png">

According to installation note #2 this should happen automatically: 
```iCloud3 installs the Event Log card program into the config/www/icloud3 directory and updates it when a new version is available.```
``` iCloud3 checks the Lovelace Resource when it starts. The directory containing the icloud3-event-log-card.js file is added or updated so you should not have to do anything.```

Currently this is what is shown:
<img width="726" alt="Screenshot 2023-03-30 151536" src="https://user-images.githubusercontent.com/47460053/228847589-33639fe5-c887-461c-b44c-aa6edaf5597e.png">

Attached the migration log 

[icloud3-migration.log](https://github.com/gcobb321/icloud3_v3/files/11112775/icloud3-migration.log)

*edited/updated the post, because the log file has my email address all over the place - would be good to hide that.

**Comment by JeroenTuinstra** [comment]
I did a manual move to /config/www/icloud3 and changed according to this text: 

```
Note: Using another custom card directory - If you move the Event Log card to another directory, the Lovelace Resources should automatically be changed. If something happens and it is not changed, change the directory (icloud3) in the URL statement on the above screen to the new directory name. Then select the new directory name in the Event Log Directory field on the iCloud3 Configurator > Menu Page 2 > Other Parameters screen.

```

But it resulted in the same screen. The log is actually not working at all. It remains empty and all sensors are not showing anything.

**Comment by JeroenTuinstra** [comment]
Having copied the content from the zipfile directory /event_log_card/ into /config/www/icloud3 made the card work.
Had to delete and re-add all devices in order for them work. So migration actually doesn't (at least in my case) migrate the devices properly.

**Comment by gcobb321** [comment]
When it migrates, it uses the directory from v2.4.7 (custom _cards) so the resources do hot have to be upgraded. I’ll make a note to clarify this in the docs. 

Try refreshing your browser.

**Comment by JeroenTuinstra** [comment]
I did see that all devices were inactive, but the devices were all there (sensor.jeroens_iphone, etc.) they didn't show the right value, battery state was 0% for example. Even after activating them and filling in the right things with family sharing and tracking, they still didn't show the right value. Not untill I deleted the devices and added them again, did they show the value.

**Comment by JeroenTuinstra** [comment]
In the lovelace card, the battery level of the iphone is very strange. It jumps constantly 100%. So from the actual % to the 100%. It gives this log:

<img width="1703" alt="Screenshot 2023-04-02 200449" src="https://user-images.githubusercontent.com/47460053/229370663-79363ca4-b853-49a7-bb02-ce6b9e692109.png">

What is causing this? As you can see in the log, it worked yesterday, but today it says 100%, while it clearly isn't.

**Comment by gcobb321** [comment]
I found a problem where an old iosapp battery level would overwrite a newer famshr battery level. The iOS app battery level is checked every 15-secs so it would cause a bouncing like you are seeing. I have added an update Time so old info will not replace newer info. This will be on the next release in a few days.

**Comment by morrisonpeter** [comment]
Hi, I noticed my locations and battery levels were not updating and when I went to check the log with the lovelace card it looks just like JeroenTuinstra's screenshot above, showing a partial header but no contents.

I recently switched to the iCloud3.0.0 beta 15 from the HA iCloud integration and it seemed to be working perfectly for a while (weeks?).  I'm not sure what changed on my end before it stopped updating locations/etc. and when it stopped showing most of the lovelace card contents, perhaps after HA system restart or two. 

Am I bringing this up in the right issue#? Should I make a new one?

**Log notes:**
- It looks like I have icloud3-event-log-card.js  in the /config/www/custom_cards/ and  /config/www/icloud3/ folders. I also found it in /config/custom_components/icloud3/ folder. I did not migrate from an earlier version but it's possible I tried iCloud3 a long time ago on my system, if that explains why I have the file in both folders. I installed v3.0.0 b15 from HACS.

- The last line in /config/icloud3-debug-1.log has a timestamp of 2023-04-15 00:00:00 which was midnight yesterday at this point. I did not find any error messages in icloud3-debug-1.log that stand out, mostly just occasional Waze connection errors.
- /config/icloud3-debug.log shows today's log starting at 2023-04-16 12:38:16 but again, it shows nothing remarkable (just creating sensor entities, setting up zones, etc.). There were no errors in that file.

- icloud3-event-log_2023.03.23-21.57.51.log seems normal although the date in the filename was about three weeks ago. Perhaps that was the date I installed iCloud3 v3.0.0 b15? There are no icloud3-event-log~~~.log files in the /config/ folder that are more recent.

- I also have a /config/icloud3-migration.log file that seems normal with no errors.

Do I wait patiently for the next beta version to roll out or would it help if I provided more information or full logs?

**Comment by gcobb321** [comment]
I submitted iCloud3 v3 to be added to HACS several weeks ago but, as far as I can tell, it has not been added yet. Doing a search in HACS only lists iCloud3 v2. How and where did you find v3 b15?

**Comment by morrisonpeter** [comment]
I added the v3 beta custom repository to HACS and installed through that. 
It was recommended to me on a GitHub message chain for one of the issues on the official iCloud integration that mentioned how they should remove it since it wasn't being maintained anymore. Someone suggested the v3 beta of iCloud3 because the GUI would make it easier to manage my family's phones than with v2 (my kids constantly change their phone names so I was manually reconfiguring iCloud3 v2 a lot when I initially tried it a year or so ago). So far the beta has worked great other than this issue's minor hiccup which is very minor for a beta! Thank you for making it!

**Comment by gcobb321** [comment]
b16 released
