### ISSUE TITLE
Feature request - Apple iCloud: Lost device

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#99]
Hi Gary, 

Is it possible to implement the equivalent to icloud.lost_device (Apple iCloud: Lost device) service call? I still use icloud integration just because of this feature (I have an automation that call it). If this is possible, I could stop using the icloud integration completely and only icloud3.

Thanks in advance
Marcelo

**Comment by gcobb321** [comment]
I’ll look at it

**Comment by gcobb321** [comment]
b16 has it
